### ISSUE TITLE
google play屡次停止服务

### ISSUE THREAD

**Issue by izaktan** [kooritea/fcmfix#1]
edxposed v0.5.0.6_4586(YAHFA) 
MIUI12 Android 11
刚启用就显示停止服务，改完重启后就频繁显示停止服务，fcm也变成无服务

**Comment by izaktan** [comment]
另外考虑支持一下太极吗，edxposed更新适配比较慢到现在都是金丝雀版本

**Comment by kooritea** [comment]
频繁停止服务多半是改错了…
不过因为我手上只有安卓10我也不清楚是不是还是一样的

没用太极也应该不会支持太极抱歉

**Comment by izaktan** [comment]
我刚刚又试了一次，确认没改错，还是不行，改完重启就跳出来屡次停止服务

**Comment by kooritea** [comment]
现在已经支持安卓11了
