### ISSUE TITLE
FCM能保持连接，但收不到推送

### ISSUE THREAD

**Issue by lsjiaowo** [kooritea/fcmfix#10]
作者你好，我又来打扰了 (^^*)
WiFi状态下，可以一直长时间保持连接Connected，但是收不到推送，没有提示Successful，会一直显示[fcmfix]Send Broadcast GCM_RECONNECT，如图。
但是切换到数据流量就马上收到推送了，切换回WiFi就又是一直能连接，但收不到推送，不知道是什么原因。
目标APP是推特和Gmail

https://sm.ms/image/k1hsLbm7ISid9Hy
https://sm.ms/image/XhbCAtxaSvuq2dk

**Comment by kooritea** [comment]
看起来是重连时机判断出问题了，导致一直在重连。
但是我这里没法复现…先发一下你的配置文件让我看看？/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml

**Comment by lsjiaowo** [comment]
和你前面给出的例子是一样的配置，gms_version和我手机上也是一致的

`<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="heartbeatInterval" value="0" />
    <string name="timer_intent_property">d</string>
    <string name="timer_next_time_property">f</string>
    <boolean name="enable" value="true" />
    <string name="timer_settimeout_method">c</string>
    <string name="timer_class">acrp</string>
    <string name="gms_version">21.18.16 (150400-374723149)</string>
    <boolean name="isInit" value="true" />
</map>`

**Comment by kooritea** [comment]
![IMG_20210614_195352.jpg](https://user-images.githubusercontent.com/28976621/121888207-4bec8d80-cd4a-11eb-9cd4-b5af8a5545b1.jpg)
把这一部分的信息也截图我看一下

然后把配置文件的enable项的value改成false之后重启看看还会不会出现一直重连的问题

**Comment by lsjiaowo** [comment]
截图：https://sm.ms/image/gXJQ3YFEeCMWBkU
我现在通过clash修改host将mtalk.google.com固定到64.233.188.188这个IP。目前可以一直保持连接并收到推送。
方法是在这里看到的https://v2ex.com/t/769215

**Comment by kooritea** [comment]
如果改host可以的话那就是网络问题了。。

**Comment by lsjiaowo** [comment]
嗯，应该是网络问题，我改了host之后一直可以连接并推送，测试了几天也是正常的
