### ISSUE TITLE
什么时候能添加安卓13的支持？

### ISSUE THREAD

**Issue by chan1108** [kooritea/fcmfix#101]

**Comment by TigerBeanst** [comment]
Android 13 正常兼容啊

**Comment by chan1108** [comment]
> Android 13 正常兼容啊

我看最新版的release里写了

> 安卓API版本提升到32(Android 12)

而且我在coloros13勾选模块重启后无法正常开机

**Comment by TigerBeanst** [comment]
> > Android 13 正常兼容啊
> 
> 我看最新版的release里写了
> 
> > 安卓API版本提升到32(Android 12)
> 
> 而且我在coloros13勾选模块重启后无法正常开机

安卓API版本提升到32(Android 12) 指的是 targetSdkVersion 提升到 32，并不直接表示系统兼容性

勾选模块后无法开机的话需要提供 Xposed 日志，不然也没办法排查……

**Comment by kooritea** [comment]
不能开机有可能是fcmfix本体拉不起来，看看系统有没有自启动之类的设置给fcmfix本体放开一下。

**Comment by chan1108** [comment]
> 不能开机有可能是fcmfix本体拉不起来，看看系统有没有自启动之类的设置给fcmfix本体放开一下。

给fcmfix设置自启动权限后可以正常开机了
