### ISSUE TITLE
安装后无论是否勾选应用，依然会收到推送？

### ISSUE THREAD

**Issue by himan85** [kooritea/fcmfix#102]
系统MIUI13国际版，第一次（不清楚是否第一次？)勾选app后，之后不论是否再勾选应用依然收到通知，甚至停用卸载模块依然可以收到。

**Comment by kooritea** [comment]
用的是最新版吗，最新版应该修复了这个问题才对

**Comment by himan85** [comment]
Fcmfix是最新版，系统是miui13国际版，我甚至怀疑这系统fcm本来就是好的，但证实这一点只能刷机了，顺便问一下，fcmfix本身是要保持后台运行的吗

**Comment by kooritea** [comment]
开机的时候需要启动，之后都不需要后台。

**Comment by kooritea** [comment]
你这个国际版的任务管理器是不会直接停止应用的，去应用设置里面强制停止app看能不能收到通知就知道是不是fcmfix在工作了

**Comment by himan85** [comment]
仔细测试后发现应该是你估计的app并没有真正的停止，现在不勾选会显示Failed to broadcast to stopped...

目测是可以正常工作了

**Comment by himan85** [comment]
![IMG_2988](https://user-images.githubusercontent.com/30474616/221422697-1b4a8a3c-d041-4924-808f-18414fd160e6.JPG)
![IMG_2989(20230227-001736)](https://user-images.githubusercontent.com/30474616/221422704-675ce2a6-dbb0-450b-bfc9-2fc08d192b38.JPG)
继续测试下，Telegram不勾选会显示广播失败，但发现还有app是没有勾选但是会收到推送消息，比如多邻国
