### ISSUE TITLE
被墓碑的App不弹通知

### ISSUE THREAD

**Issue by jordanyoong1** [kooritea/fcmfix#106]
我在使用NoActive开启V2模式后只要进入墓碑后的App就无法弹出通知，只能在开启App之后才会弹出

**Comment by cxzlw** [comment]
> 我在使用NoActive开启V2模式后只要进入墓碑后的App就无法弹出通知，只能在开启App之后才会弹出

我记得 NoA 是不是声明过不会支持 fcm
