### ISSUE TITLE
小米使用后智能省电会不见

### ISSUE THREAD

**Issue by sujiuer5201314** [kooritea/fcmfix#108]
![Screenshot_2023-06-08-15-03-48-369_com.miui.powerkeeper.png](https://github.com/kooritea/fcmfix/assets/119154401/c31a2ea8-4497-4cdd-8ac7-71e92cc4be3e)

**Comment by kooritea** [comment]
作用域不要选电量和性能

**Comment by kooritea** [comment]
先试试吧，这个比较玄学

**Comment by David-plz** [comment]
fcmfix导致夜间智能省电消失我也是检查好久才发现的，后来就暂时用着MIUIGMS了，不过原理跟fcmfix稍有差异。但还是希望如果后续能有更新的话修复这个问题，主要这问题说小也不小，一旦智能省电没了就找不回来了

**Comment by TigerBeanst** [comment]
> fcmfix导致夜间智能省电消失我也是检查好久才发现的，后来就暂时用着MIUIGMS了，不过原理跟fcmfix稍有差异。但还是希望如果后续能有更新的话修复这个问题，主要这问题说小也不小，一旦智能省电没了就找不回来了

不勾选「电量和性能」就行吧，我现在没选他，区别不大，本来选他也只是让电量与性能判定手机是国际版，不过在我这边本身没有效果（可能是因为我 MIX4 没有国际版hhhhhh）
而且后面主要还是靠强制唤醒来收的 FCM 消息，电量与性能的修改可有可无了

**Comment by David-plz** [comment]
> > fcmfix导致夜间智能省电消失我也是检查好久才发现的，后来就暂时用着MIUIGMS了，不过原理跟fcmfix稍有差异。但还是希望如果后续能有更新的话修复这个问题，主要这问题说小也不小，一旦智能省电没了就找不回来了
> 
> 不勾选「电量和性能」就行吧，我现在没选他，区别不大，本来选他也只是让电量与性能判定手机是国际版，不过在我这边本身没有效果（可能是因为我 MIX4 没有国际版hhhhhh） 而且后面主要还是靠强制唤醒来收的 FCM 消息，电量与性能的修改可有可无了

不清楚，后来我一直暂时用的MIUIGMS，这个是通过保后台实现接收FCM消息的。前几天刚把主力手机转到eu版上，也就用不到这插件了，后期如果再用国内版的时候我再看下
