### ISSUE TITLE
使用网络代理时代理连接突然断开

### ISSUE THREAD

**Issue by MuyueJusan** [kooritea/fcmfix#11]
在使用ssr或者clash for android网络代理时出现代理突然中断，暂时关闭fcmfix后情况停止

**Comment by MuyueJusan** [comment]
虽然这个问题没有解决，但我发现…我就是心跳包的问题，上谷歌找了个跳过系统直接发心跳包的软件，fcm就活了，不过那个软件有个缺点就是下梯子的时候会断，要等到下次发心跳包才能复活
不过我还是希望能够得到我问题的答复，我想知道是我手机问题还是有bug
补充下安卓11 miui12稳定版12.2.2

**Comment by kooritea** [comment]
代理中断是指系统上那个vpn断开吗

**Comment by MuyueJusan** [comment]
对，有时会突然断开，没有时间规矩，clash给过崩溃报告但我忘记截图了

**Comment by MuyueJusan** [comment]
确认了，是我自己的miui系统bug（大概？）

**Comment by kooritea** [comment]
因为没有动过系统vpn方面的代码所以应该不是fcmfix的问题…

**Comment by kooritea** [comment]
> 虽然这个问题没有解决，但我发现…我就是心跳包的问题，上谷歌找了个跳过系统直接发心跳包的软件，fcm就活了，不过那个软件有个缺点就是下梯子的时候会断，要等到下次发心跳包才能复活
> 不过我还是希望能够得到我问题的答复，我想知道是我手机问题还是有bug
> 补充下安卓11 miui12稳定版12.2.2

这个是miui优化造成的普遍问题，fcmfix也有解决这个问题不过要手动改配置文件

**Comment by MuyueJusan** [comment]
去了clash for android看了下，有其他人反应过这个问题，有人提到是miui云控的问题

**Comment by kooritea** [comment]
> 去了clash for android看了下，有其他人反应过这个问题，有人提到是miui云控的问题

这个就不清楚了，个人觉得这种没必要运控，真运控也不可能只断vpn
我用的是eu版没发现

**Comment by MuyueJusan** [comment]
我尝试更新系统了，或许我错怪miui了，目前没有突然中断，总之感谢听了我一个与项目基本无关的问题（题外话的题外话，miui12.5感觉有些相对之前版本有些卡）
