### ISSUE TITLE
软件被非millet墓碑（例如冻它，noac和灭霸）冻结后无法推送了

### ISSUE THREAD

**Issue by sujiuer5201314** [kooritea/fcmfix#110]
日志如下
![Screenshot_20230622-130352_Google Play 服务.png](https://github.com/kooritea/fcmfix/assets/119154401/c6f113ee-4dde-46fc-be67-fc34bcabadc3)

**Comment by cxzlw** [comment]
我其实想说这是墓碑的错，比如有墓碑强调不会适配 fcm。
fcmfix 所做的是拉起未在运行的应用，我的测试结果是冻它环境下 fcmfix 可以拉起未运行的应用，并发送通知。而已冻结的应用则无法发送通知。
部分墓碑给出的解决方案是设为自由后台等选项。

**Comment by SenLief** [comment]
应用都冻结了，还怎么拉起来发通知额，正常应该是杀死进程，而不是冻结。

**Comment by cxzlw** [comment]
> 应用都冻结了，还怎么拉起来发通知额，正常应该是杀死进程，而不是冻结。

正确的，可惜 millet 会冻结并无法拉起…

**Comment by SenLief** [comment]
> > 应用都冻结了，还怎么拉起来发通知额，正常应该是杀死进程，而不是冻结。
> 
> 正确的，可惜 millet 会冻结并无法拉起…

别用冻结这个功能，而是用杀死进程这个功能，或者休眠就可以了。我现在就是这样使用的。
