### ISSUE TITLE
ColorOS 12电池在没有VPN的情况下将gms服务不放在电池白名单引发心跳包为负数的问题

### ISSUE THREAD

**Issue by 17998384** [kooritea/fcmfix#113]
将电池冻结掉后，心跳恢复正常，想问下这个有什么办法么？

**Comment by kooritea** [comment]
心跳计数器被杀掉了吧，把gms放电池白名单？

**Comment by 17998384** [comment]
> 心跳计数器被杀掉了吧，把gms放电池白名单？

真相了，ColorOS12有一个特别蠢的机制，电池.apk会在连接到google的时候将gms放入白名单，无法连接google后将gms移除白名单，就导致了心跳不正常；目前我将电池中的 Oplus Battery Service给禁用后解决了，但是后遗症就是电池曲线图没了，不过不重要，感谢作者回复
