### ISSUE TITLE
微信不能推送，提示Send broadcast GCM_RECONNECT

### ISSUE THREAD

**Issue by xiaozhen12138** [kooritea/fcmfix#114]
改了hosts文件，FCM Diagnostics显示Connected，nekogram也能推送。但是微信就是不推送，微信国内版8.0.40

**Comment by xiaozhen12138** [comment]
那出现这个情况的原因一般是什么呢？

**Comment by kooritea** [comment]
微信服务器那边判断你不是海外用户就不给你发fcm，至于根据什么判断就不知道了

**Comment by xiaozhen12138** [comment]
行吧，那我还是再研究一下吧，谢谢大佬的解答

**Comment by hongfa1380** [comment]
我酷安已经发布教程了，国内如何微信注册fcm

**Comment by hongfa1380** [comment]
> > 我酷安已经发布教程了，国内如何微信注册fcm
> 
> 哪个贴子？

https://www.coolapk.com/feed/49965611?shareKey=NWZiMjIwNjlkOGY4NjU0YWU1Y2Y~&shareUid=856602&shareFrom=com.coolapk.market_13.3.4
