### ISSUE TITLE
在Android 14正式版不断重启手机

### ISSUE THREAD

**Issue by zyh941** [kooritea/fcmfix#116]
开发者你好，我刚把Pixel 5升级到正式版Android 14(UP1A.231005.007)，然后已经明确：单独装好LSPosed不开启任何LSP模块则手机正常运行，一开启fcmfix模块、重启后每次进入桌面或还没输入完锁屏密码就自动重启手机了，我只能用电脑命令行强制卸载所有magisk模块相当于把LSPosed干没了，我无法提供LSP日志，请研究后修复。
另外：请问有没有不卸载Magisk模块而单独禁用所有LSPosed模块的cmd命令呢，每次测试都要重启很多次

**Comment by kooritea** [comment]
先试试新建一个/sdcard/disable_fcmfix看能不能禁用，这个/sdcard应该是/storage里的一个文件夹挂载出来的，具体你要看你自己的机器。

另一个是在/data/app里把fcmfix文件夹删了就行了，就是不太好找

**Comment by zyh941** [comment]
好的，我还是坐等你的模块更新吧

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kml0798** [comment]
恨怎么不搜一搜，重启了一天了，刚怀疑fcmfix呢

**Comment by kooritea** [comment]
> 恨怎么不搜一搜，重启了一天了，刚怀疑fcmfix呢

大概率就是fcmfix问题（
fcmfix在系统进程上尝试获取应用列表，估计是出错了然后就启动失败重启了

**Comment by zyh941** [comment]
> 另外，进安全模式 magisk 会自动禁用所有模块

谢谢，刚试了20231030自动发的版本，还是没修好，但起码我会简单把手机救回来了

**Comment by zyh941** [comment]
> > 恨怎么不搜一搜，重启了一天了，刚怀疑fcmfix呢
> 
> 大概率就是fcmfix问题（ fcmfix在系统进程上尝试获取应用列表，估计是出错了然后就启动失败重启了

刚才试了20231030自动发的版本，还是一进桌面手机马上重启……

**Comment by kooritea** [comment]
这个问题还没修复…

**Comment by Rakau** [comment]
KSU没遇到这个问题

**Comment by zyh941** [comment]
装了2023.11.19号的版本，正常运行，关闭工单
