### ISSUE TITLE
Android14，No response to

### ISSUE THREAD

**Issue by mrlihx** [kooritea/fcmfix#117]
升级了安卓14，app完全关闭后收不到推送，app挂在后台可以推送成功。

![Screenshot_2023-10-13-00-05-20-515_com.google.android.gms-edit.jpg](https://github.com/kooritea/fcmfix/assets/68861286/dfb3992a-c951-4b16-81c1-9180f6c93970)

**Comment by kooritea** [comment]
看起来fcmfix没生效，应该是旧的hook点不支持安卓14了，而且其他也有报告可能拿不到应用列表，需要更新。

**Comment by mrlihx** [comment]
> 看起来fcmfix没生效，应该是旧的hook点不支持安卓14了，而且其他也有报告可能拿不到应用列表，需要更新。

坐等更新😜

**Comment by Rakau** [comment]
![Screenshot_2023-10-31-07-44-00-080_com google android gms-edit](https://github.com/kooritea/fcmfix/assets/33389179/4eac6fea-ee90-4a0b-a980-2a8563aa7b6c)
![Screenshot_2023-10-31-07-44-32-111_com google android gms](https://github.com/kooritea/fcmfix/assets/33389179/dd5dc1e2-c1dd-49d6-8aa0-3c9c889e1fd1)

**Comment by xzl0326** [comment]
我这边也是，HyperOS安卓14.完全没后台的软件，不开自启动权限就无法唤醒。

**Comment by wfniub** [comment]
得到解决了吗？

**Comment by cxzlw** [comment]
> 得到解决了吗？

 看[Auto Release 20231121-adf1947](https://github.com/kooritea/fcmfix/releases/tag/20231121-adf1947),对我有用

**Comment by kooritea** [comment]
已更新
