### ISSUE TITLE
Gmail收不到推送

### ISSUE THREAD

**Issue by lsjiaowo** [kooritea/fcmfix#12]
FCM能一直连接Connected，也显示Successful，但是Gmail却没有收到推送。LSP的日志里没有显示Allow LocalNotification。如图
https://sm.ms/image/jGagWMoF5AViqPb
https://sm.ms/image/P1R5Ty7hOzDKs8a

只能重启手机，刚重启后的几分钟之内Gmail能收到推送，但是过一段时间就又收不到推送了。。。
（Gmail已开启自启动，电池不优化。与此同时Twitter推送正常，可以一直收到推送）

**Comment by kooritea** [comment]
LSP有勾选安卓作用域吗

**Comment by lsjiaowo** [comment]
这个肯定勾选了Android系统作用域的

**Comment by kooritea** [comment]
你提供的截图看不到有fcmfix已经启动的痕迹。。
有在gms日志里看到过[fcmfix]开头的日志吗

**Comment by lsjiaowo** [comment]
是指FCM的日志吗，我第一次刚装这个模块的时候，能够在FCM里面看到[fcmfix]开头的记录，但是我又装了EdXposed和LSP，又用了clash修改固定IP，翻来覆去几次操作之后FCM里面就没看到[fcmfix]开头的记录。
我也很奇怪，但是推特能一直收到推送。只能在LSP的日志里看到[fcmfix]Send Force Start、Allow这类的记录。

**Comment by kooritea** [comment]
lsp的日志里有fcmfix的吗，截图我看看

**Comment by lsjiaowo** [comment]
lsp排版太长不好截图，我直接传日志文件给你哈，https://www.wenshushu.cn/f/5r0adtjv79p
里面也有Gmail推送记录，不过那只是重启后收到，过一段时间就又收不到推送了

**Comment by kooritea** [comment]
是不是没有在lsp里勾选gms

你的推特能收到通知可能是没有完全被杀掉，还在后台。
gmail一段时间之后不到可能是被杀掉了，fcmfix没有起作用

**Comment by kooritea** [comment]
你这个好像不是最新版，顺便更新一下吧…

**Comment by lsjiaowo** [comment]
lsp没勾选gms，原来是被隐藏了😅。现在重启再测试下能不能正常推送
lsp是最新版的v1.4.5-5767

![IMG_20210625_140951.jpg](https://user-images.githubusercontent.com/49240966/123378426-536c2c00-d5bf-11eb-90db-4fe176ec79fb.jpg)

**Comment by lsjiaowo** [comment]
另外有个问题哈，为什么只能在解锁后才收到推送。锁屏状态下，点亮屏幕看不到推送弹窗(已经设置锁屏可接收通知)，解锁后就弹出一堆推送，是不是锁屏状态下fcm或者模块不工作？🧐

**Comment by kooritea** [comment]
因为你收到的fcm不是高优先级的，我记得是只有高优先级的才会立即推送给app，普通优先级会适时推送防止耗电过多

**Comment by lsjiaowo** [comment]
怎样自定义优先级呢，有没有教程😅

**Comment by kooritea** [comment]
这个是推送方决定的，一般只有im会用高优先级，你可以试试telegram

**Comment by lsjiaowo** [comment]
好，谢谢指导哈😊
