### ISSUE TITLE
0.7.0版本对于新版gms的hook点失效

### ISSUE THREAD

**Issue by Andrea-lyz** [kooritea/fcmfix#120]
Google Play服务版本：23.43.12
系统：ColorOS13.1
安卓版本：13
以尝试清除Google Play服务并重启，无效

![Screenshot_2023-10-27-01-59-59-77_f7aa348215f5d566f9e4ca860f474209](https://github.com/kooritea/fcmfix/assets/52863141/278f448e-e117-4725-80ce-2a7c9cf672bd)
![Screenshot_2023-10-27-01-58-19-82_f7aa348215f5d566f9e4ca860f474209](https://github.com/kooritea/fcmfix/assets/52863141/2b99fec9-e2a2-44fe-a3bd-88136b465704)

**Comment by akaDRJ** [comment]
Google Play服务版本：23.43.12
系统：MIUI14
安卓版本：13
遇到同样问题

**Comment by 666boy** [comment]
安卓12的MIUI13也是這樣

**Comment by j2rong4cn** [comment]
> 安卓12的MIUI13也是這樣

> 一样的问题，Google play版本，MIUI和安卓版本都跟上边一样。提示未能找到hook什么

> Google Play服务版本：23.43.12 系统：MIUI14 安卓版本：13 遇到同样问题

已提交pr，等作者合并发布新版。这个是Github Actions自动编译的 [fcmfix](https://github.com/j2rong4cn/fcmfix/suites/17720875993/artifacts/1014570780)，签名不一样，如果没有核心破解需要卸载再安装

**Comment by Andrea-lyz** [comment]
> > 安卓12的MIUI13也是這樣
> 
> > 一样的问题，Google play版本，MIUI和安卓版本都跟上边一样。提示未能找到hook什么
> 
> > Google Play服务版本：23.43.12 系统：MIUI14 安卓版本：13 遇到同样问题
> 
> 已提交pr，等作者合并发布新版。这个是Github Actions自动编译的 [fcmfix](https://github.com/j2rong4cn/fcmfix/suites/17720875993/artifacts/1014570780)，签名不一样，如果没有核心破解需要卸载再安装
> 

感谢大佬，能再发一下吗似乎链接失效了404

**Comment by j2rong4cn** [comment]
> > > 安卓12的MIUI13也是這樣
> > 
> > 
> > > 一样的问题，Google play版本，MIUI和安卓版本都跟上边一样。提示未能找到hook什么
> > 
> > 
> > > Google Play服务版本：23.43.12 系统：MIUI14 安卓版本：13 遇到同样问题
> > 
> > 
> > 已提交pr，等作者合并发布新版。这个是Github Actions自动编译的 [fcmfix](https://github.com/j2rong4cn/fcmfix/suites/17720875993/artifacts/1014570780)，签名不一样，如果没有核心破解需要卸载再安装
> 
> 感谢大佬，能再发一下吗似乎链接失效了404

https://github.com/j2rong4cn/fcmfix/actions

**Comment by kooritea** [comment]
> @kooritea 你还是得正经release一下的，CI里的只保存3个月，而且必须要登录才会展示下载链接（不登录没有任何提示要登录）

原来还要登录…下午改成ci release吧
