### ISSUE TITLE
HyperOS＋Android14，无法唤醒已完全停止的应用

### ISSUE THREAD

**Issue by xzl0326** [kooritea/fcmfix#123]
HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新

**Comment by wfniub** [comment]
同样的问题！

**Comment by hongfa1380** [comment]
> HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新

原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电

**Comment by wfniub** [comment]
我知道需要给予自启的权限，目前的问题是Android14可以吗，hook正常吗？

**Comment by xzl0326** [comment]
> > HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新
> 
> 原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电

现在的问题是给自启后拉起的不是一个小缓存，很大，而且大概率吃软件自己的推送。

**Comment by xzl0326** [comment]
> > HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新
> 
> 原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电

并且应该是没有适配好hyperOS的电量与性能，hook会报错并导致系统界面重载

**Comment by cxzlw** [comment]
> > HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新
> 
> 原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电

这难道不就是这个项目的意义？

**Comment by TigerBeanst** [comment]
> > HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新
> 
> 原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电

fcmfix 的作用之一就是在不开启系统里应用自启动权限的情况下，强制拉起应用发通知。。。

**Comment by hongfa1380** [comment]
> > > HyperOS＋Android14。无法唤醒已完全停止的应用。必须给要通知的应用开启自启动权限才可以收到消息。希望更新
> > 
> > 
> > 原生系统也是这样，强制拉起给予自启权限无后台的app，没自启权限的app拉不起来的。它的特征是无任何后台的app也可以拉起，且后台只会出现一个小缓存就能通知了，省电
> 
> fcmfix 的作用之一就是在不开启系统里应用自启动权限的情况下，强制拉起应用发通知。。。

没有fcmfix的时候，原生系统强行停止的app，fcm也拉不起来。耗电还比较大

**Comment by WuYang09661** [comment]
我小米14最新版fcmfix也碰到了这个问题，日志显示拉起成功，但是实际上收不到通知，不过微软全系都没有这个问题，百分百拉起，但是discord和ins很抽风

**Comment by xzl0326** [comment]
最新版已经可以了

**Comment by WuYang09661** [comment]
![image](https://github.com/kooritea/fcmfix/assets/81788651/a6ddcb4c-f247-44a0-bb53-79409e203381)
还是无响应

**Comment by xzl0326** [comment]
> ![image](https://private-user-images.githubusercontent.com/81788651/285724184-a6ddcb4c-f247-44a0-bb53-79409e203381.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjY4OTgsIm5iZiI6MTcwMTA2NjU5OCwicGF0aCI6Ii84MTc4ODY1MS8yODU3MjQxODQtYTZkZGNiNGMtZjI0Ny00NGEwLWJiNTMtNzk0MDllMjAzMzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2Mjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMGFhNGVmN2ExZWI3OTYyNTdkZWZmY2VhYTdmNDNiMTM2NDcwZjkyZDAzNmJjOWQxOTk2N2QzODAxNzk2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wROma3MgdHINqxsxqj2EPGDjvZfAVJ97ee-dWikHPxk) 还是无响应 偶尔能有几次成功拉起，目前我是给了自启动，电池限制是智能限制，说是不影响消息接收，不过我开无限制事实上也收不到

那就不太清楚了，我现在dc，电报都是正常的，连微信就正常了

**Comment by WuYang09661** [comment]
是必须要给电池无限制才行吗？

**Comment by xzl0326** [comment]
> 是必须要给电池无限制才行吗？

不用，我安装最新版fcmfix就能正常拉起了

**Comment by wfniub** [comment]
> > 是必须要给电池无限制才行吗？
> 
> 不用，我安装最新版fcmfix就能正常拉起了

telegram，总是收不到消息，有时候又可以，你的行吗？

**Comment by xzl0326** [comment]
> > > 是必须要给电池无限制才行吗？
> > 
> > 
> > 不用，我安装最新版fcmfix就能正常拉起了
> 
> telegram，总是收不到消息，有时候又可以，你的行吗？

可以，就是可能会有延迟

**Comment by cxzlw** [comment]
> 是必须要给电池无限制才行吗？

好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？

**Comment by xzl0326** [comment]
> > 是必须要给电池无限制才行吗？
> 
> 好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？

不确定，我有墓碑。没问题

**Comment by cxzlw** [comment]
> > > 是必须要给电池无限制才行吗？
> > 
> > 
> > 好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？
> 
> 不确定，我有墓碑。没问题

你是什么墓碑

**Comment by xzl0326** [comment]
> > > > 是必须要给电池无限制才行吗？
> > > 
> > > 
> > > 好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？
> > 
> > 
> > 不确定，我有墓碑。没问题
> 
> 你是什么墓碑

smillet

**Comment by cxzlw** [comment]
> > > > > 是必须要给电池无限制才行吗？
> > > > 
> > > > 
> > > > 好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？
> > > 
> > > 
> > > 不确定，我有墓碑。没问题
> > 
> > 
> > 你是什么墓碑
> 
> smillet

我也是

**Comment by xzl0326** [comment]
> > > > > > 是必须要给电池无限制才行吗？
> > > > > 
> > > > > 
> > > > > 好诡异我这边能拉起未运行的软件，在后台的起不来。无非millet墓碑。感觉和millet有点关系？
> > > > 
> > > > 
> > > > 不确定，我有墓碑。没问题
> > > 
> > > 
> > > 你是什么墓碑
> > 
> > 
> > smillet
> 
> 我也是

给要推送的应用白名单试试吧
