### ISSUE TITLE
fcmfix勾选gms后，safetynet net检测失败

### ISSUE THREAD

**Issue by hongfa1380** [kooritea/fcmfix#124]
![Screenshot_20231107-192439](https://github.com/kooritea/fcmfix/assets/49623327/34b55569-0f8d-4129-bbf7-e38599deb6c1)
已经刷了play intergrity fix最新版，没勾选之前都能通过，pixel7pro官方系统安卓13最终版

**Comment by LaplaceTor** [comment]
老问题，GMS HOOK不行

**Comment by hongfa1380** [comment]
> 老问题，GMS HOOK不行

哦哦哦，明白了

**Comment by Rakau** [comment]
没遇到这个问题
