### ISSUE TITLE
Can't work on HyperOS（Android14）

### ISSUE THREAD

**Issue by VOfficial404** [kooritea/fcmfix#129]
小米14Pro，HyperOS 1.0.23.11.21.Dev Android14
fcm是连着的，但是支持fcm推送的APP仍然收不到通知🤔（应用均未开启自启动权限）
我已经刷入了[unlock cn gms模块](https://github.com/fei-ke/unlock-cn-gms)来
![Screenshot_2023-11-23-21-02-55-879_com google android gms](https://github.com/kooritea/fcmfix/assets/104217168/96aaed90-4ed4-4528-b37b-e7d9987c4d0f)
![Screenshot_2023-11-23-21-09-36-746_com google android gms](https://github.com/kooritea/fcmfix/assets/104217168/2d12df30-3a56-4669-9022-e05c66310d20)

但是在同样升级了HyperOS和Android14的小米13Pro上仍然可以正常使用
![IMG_20231123_211032_967](https://github.com/kooritea/fcmfix/assets/104217168/aea67a2f-40d0-4491-8de2-3fc1ee75f2a7)

**Comment by kooritea** [comment]
android14应该是支持了，但是HyperOS的自启动权限现在还绕过不了
