### ISSUE TITLE
有支持fcm的app不能被选中

### ISSUE THREAD

**Issue by ayanamist** [kooritea/fcmfix#13]
例如Google相册和textnow这两个应用，是能看到有fcm消息进来的，但在fcmfix里却没有出现在列表里
![IMG_20210721_234236](https://user-images.githubusercontent.com/406779/126518526-932a9306-caa5-4fa0-a63a-f73730cf3401.jpg)

**Comment by kooritea** [comment]
我去看了一下确实是之前有的谷歌相册现在没有了…
判定有点问题

**Comment by kooritea** [comment]
https://github.com/kooritea/fcmfix/releases/tag/v0.3.1

**Comment by ayanamist** [comment]
能看到了，thx👍🏻
