### ISSUE TITLE
适配安卓14了，目前是不是不开自启权限也行

### ISSUE THREAD

**Issue by wfniub** [kooritea/fcmfix#130]
终于适配安卓14和hyperos
现在是不开启自启也可以启动推送吗，但是有时候为什么收不到，如下截图
![Screenshot_2023-11-25-10-38-33-514_com google android gms](https://github.com/kooritea/fcmfix/assets/59757806/ccf1b523-7f92-488b-89f6-338bc4dead01)

**Comment by kooritea** [comment]
不开自启不行，你这个可以收到只是因为应用还在后台

**Comment by David-plz** [comment]
我安卓14也是图里这情况，tg回出现无响应，也给自启了。但来消息时tg iOS可以提示，安卓版不行

**Comment by wfniub** [comment]
![288da93fbaa5378677d8702aed18304](https://github.com/kooritea/fcmfix/assets/59757806/1083538e-c1dc-4f14-9d79-7a9ddff22f69)
大佬，这具体啥情况，diagnostics明明没断开，但是收不到消息呢！

**Comment by cxzlw** [comment]
> 不开自启不行，你这个可以收到只是因为应用还在后台

在后台就收不到不在就可以，有什么办法吗？无非millet类墓碑

**Comment by wfniub** [comment]
> 我安卓14也是图里这情况，tg回出现无响应，也给自启了。但来消息时tg iOS可以提示，安卓版不行

同样的问题，时间久了就收不到消息了tg

**Comment by wfniub** [comment]
> > 不开自启不行，你这个可以收到只是因为应用还在后台
> 
> 在后台就收不到不在就可以，有什么办法吗？无非millet类墓碑

同样的问题！

**Comment by cxzlw** [comment]
> > > 不开自启不行，你这个可以收到只是因为应用还在后台
> > 
> > 
> > 在后台就收不到不在就可以，有什么办法吗？无非millet类墓碑
> 
> 同样的问题！

是不是有scene

**Comment by shaul-xu** [comment]
我的是小米14 hyperos，应用不给自启权限，能收到通知。
但是移动网络在锁屏之后大概率会断开 fcm 连接（有时候十几分钟断开，有时候几个小时都没断开）。

**Comment by tzcskys** [comment]
> 我的是小米14 hyperos，应用不给自启权限，能收到通知。 但是移动网络在锁屏之后大概率会断开 fcm 连接（有时候十几分钟断开，有时候几个小时都没断开）。

请问下有发现什么手段可以保持在锁屏之后不自动断开FCM连接吗？

**Comment by Shanks333** [comment]
> > 我的是小米14 hyperos，应用不给自启权限，能收到通知。 但是移动网络在锁屏之后大概率会断开 fcm 连接（有时候十几分钟断开，有时候几个小时都没断开）。
> 
> 请问下有发现什么手段可以保持在锁屏之后不自动断开FCM连接吗？



> > 我的是小米14 hyperos，应用不给自启权限，能收到通知。 但是移动网络在锁屏之后大概率会断开 fcm 连接（有时候十几分钟断开，有时候几个小时都没断开）。
> 
> 请问下有发现什么手段可以保持在锁屏之后不自动断开FCM连接吗？

替换国际版电量与性能

**Comment by kooritea** [comment]
用最新的发布
