### ISSUE TITLE
哪位大佬看下这是什么情况，fcm是不断开了，但是总是收不到消息

### ISSUE THREAD

**Issue by wfniub** [kooritea/fcmfix#131]
哪位大佬看下这是什么情况，fcm是不断开了，但是总是收不到消息，下面是日志，快搞费了都！
![6f06f4beeb1f2a166f25cd1f01bf308](https://github.com/kooritea/fcmfix/assets/59757806/6b60719e-686b-4a09-9201-702c62a966c9)

**Comment by wfniub** [comment]
有时候能收到，有时候跟睡死了一样，也开了自启，真的快以某了！

**Comment by kooritea** [comment]
现在除了原生安卓14估计都是这样，启动被系统拦下来，hyperos找不到再哪里绕过自启

**Comment by wfniub** [comment]
> 现在除了原生安卓14估计都是这样，启动被系统拦下来，hyperos找不到再哪里绕过自启

难不成要退回13？

**Comment by David-plz** [comment]
我这实测一直亮屏fcm不会断，感觉反而是锁屏后只要过十几秒，再亮屏解锁后查看，fcm就是0秒开始

**Comment by wfniub** [comment]
> 现在除了原生安卓14估计都是这样，启动被系统拦下来，hyperos找不到再哪里绕过自启

啥时候能适配完善就好了，苦等！

**Comment by David-plz** [comment]
现在安卓14的国内版rom对fcm的限制估计都没解决呢，息屏后解锁亮屏的时候断，很难看到以前连好几个小时的样子了，感觉不刷eu版没人修复了

**Comment by cxzlw** [comment]
> 现在除了原生安卓14估计都是这样，启动被系统拦下来，hyperos找不到再哪里绕过自启

小米的millet墓碑？可能得jook一下，我找时间看看

**Comment by shaul-xu** [comment]
我是 hyperos，我一切正常，应用也不需要打开【自启动】
