### ISSUE TITLE
dc通知问题问下看看

### ISSUE THREAD

**Issue by xzl0326** [kooritea/fcmfix#132]
请问discord这个服务器通知只推送3条，私聊可以很多是dc本身的问题吗
![Screenshot_2023-11-28-10-56-31-241_com google android gms](https://github.com/kooritea/fcmfix/assets/52959229/1bf4b037-d130-4436-b0e8-4cf016979170)

**Comment by kooritea** [comment]
通知是应用自己的行为，大概和fcm无关
