### ISSUE TITLE
android 14上无法工作

### ISSUE THREAD

**Issue by SenLief** [kooritea/fcmfix#134]
主要体现就是强行停止的app会拉不起来，看日志Failed to broadcast
to stopped app org.telegram.messenger，应该是fcm有推送过来但是app不在后台，无法通知，这样来看应该是模块没有工作起来。

手机realme gt5pro
版本为安卓14

**Comment by SenLief** [comment]
之前没有重启，原来是重启后来hook的，现在可以通知了，不过感觉也不会非常的省电的那种。

目前fix的方式是接到fcm推送后拉起app，也就是启动app，这样app会冷启动在前台了，如果频繁的推送狐估计还耗电一些。

这个app只有在后台fcm才会推送是特性吗？我同时手机上安装了hmspush，发现它是可以在app不在后台推送的。

**Comment by TigerBeanst** [comment]
> 之前没有重启，原来是重启后来hook的，现在可以通知了，不过感觉也不会非常的省电的那种。
> 
> 目前fix的方式是接到fcm推送后拉起app，也就是启动app，这样app会冷启动在前台了，如果频繁的推送狐估计还耗电一些。
> 
> 这个app只有在后台fcm才会推送是特性吗？我同时手机上安装了hmspush，发现它是可以在app不在后台推送的。

频繁推送的话就看你系统鲨App鲨得狠不狠了（

hmspush，mipush主要都是对应的App在后台发送给厂商，厂商直接用系统组件给你发通知，所以没有唤起App；

fcm也有这种由gms发送的通知，但是大多数情况下对应的App的后台可能都是选择唤起自己App，让App发通知这个方式（

**Comment by SenLief** [comment]
恩，了解了。这种情况下微信确实不适合，这货属于常用，经常弹。如果杀的厉害恐怕要经常冷启动了，看来这种方式还是适合邮箱这种。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SenLief** [comment]
很灵性，又不工作了，正常工作会有一个强制拉起app的日志，现在没有那行了，也不知道是拉起不成功还是模块没有工作了。

**Comment by TigerBeanst** [comment]
> 很灵性，又不工作了，正常工作会有一个强制拉起app的日志，现在没有那行了，也不知道是拉起不成功还是模块没有工作了。

不过 App 的拉起，fcmfix 好像主要修复的是 MIUI/HyperOS 上的吧

**Comment by SenLief** [comment]
> > 很灵性，又不工作了，正常工作会有一个强制拉起app的日志，现在没有那行了，也不知道是拉起不成功还是模块没有工作了。
> 
> 不过 App 的拉起，fcmfix 好像主要修复的是 MIUI/HyperOS 上的吧

fcmfix应该是模拟了一个app的进程吧，让fcm觉得进程在后台从而推送过来，然后fcmfix再拉起app。

**Comment by kooritea** [comment]
> 很灵性，又不工作了，正常工作会有一个强制拉起app的日志，现在没有那行了，也不知道是拉起不成功还是模块没有工作了。

gms上显示的日志不是可靠的，真正作用的hook是在系统上的，按道理成功一次之后只要不重启都应该是可用的，最可靠的判断只能在设置强制停止然后看fcm来消息是在设置中看应用是否在运行，是否有通知也不可靠。

**Comment by SenLief** [comment]
目前自启动后可以成功拉起了

**Comment by TigerBeanst** [comment]
> 目前自启动后可以成功拉起了

HyperOS 可以试试这个版本
https://github.com/TigerBeanstBackup/fcmfix-fix/releases/tag/20231220-d5523f3

基于作者没合并的一个pr弄的（
没有核心破解的话需要卸载作者的版本先
