### ISSUE TITLE
在coloros13上无法拉起强制停止的应用。

### ISSUE THREAD

**Issue by csjoyxy** [kooritea/fcmfix#135]
开发者你好，对于您的开发先说声感谢。
我发现在ColorOS13上无法拉起应用。请问是什么原因？以下是设置以及日志。
![Screenshot_2023-12-19-17-17-05-60_f7aa348215f5d566f9e4ca860f474209](https://github.com/kooritea/fcmfix/assets/64026998/39e894b2-129f-4c81-885e-a821fbe63f70)
![Screenshot_2023-12-19-17-18-31-31_0ba066473b79d6e213a1f6f52505e2ee](https://github.com/kooritea/fcmfix/assets/64026998/71070503-f9ea-417e-a96a-bb5b3618ddd0)
![Screenshot_2023-12-19-17-18-43-05_e6871cd13ad370b30dca80a8c4050ac0](https://github.com/kooritea/fcmfix/assets/64026998/e1923ed3-70c4-44f0-a323-76cc4947a871)
![Screenshot_2023-12-19-17-19-12-59_084ab3bc34f7aa7ccff83653f52abafc](https://github.com/kooritea/fcmfix/assets/64026998/50e94011-bb9b-43bc-888c-6201be0f91a1)

**Comment by csjoyxy** [comment]
好像是需要给tg自启动权限才行。测试几次发现给了自启动权限后强制停止也可以唤醒。

**Comment by kooritea** [comment]
因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。
在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。

但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。

**Comment by csjoyxy** [comment]
> 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 以前由系统用户发出的启动广播是不会被拦截的，现在被拦截了之后就或者手动设置允许自启动，或者fcmfix工具从做自启动限制的绕过。
> 
> 但是现在只有miui有做正确的装备不需要给自启动权限，其他除了外部的一般都要。

明白了  这个工具还是很实用  感谢开发!

**Comment by csjoyxy** [comment]
> 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。

是的 只能取舍了

**Comment by Chuhe2399** [comment]
> 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。
> 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> 
> 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。

澎湃需要自启动吗？

**Comment by SenLief** [comment]
> > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> 
> 是的 只能取舍了

如果root了可以用luckytool破解自启动这个个数限制。

**Comment by Chuhe2399** [comment]
> > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > 
> > 是的 只能取舍了
> 
> 如果root了可以用luckytool破解自启动这个个数限制。

买ios

**Comment by csjoyxy** [comment]
> > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > 
> > > 
> > > 是的 只能取舍了
> > 
> > 
> > 如果root了可以用luckytool破解自启动这个个数限制。
> 
> 买ios

刚从IOS转过来,对于爱折腾的人来说 到了安卓就回不去了.

**Comment by SenLief** [comment]
> > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > 
> > > 
> > > 是的 只能取舍了
> > 
> > 
> > 如果root了可以用luckytool破解自启动这个个数限制。
> 
> 买ios

我就是ios转过来啊，ios续航和信号太差。

**Comment by csjoyxy** [comment]
> 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> 
> 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。



> > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > 
> > 
> > 是的 只能取舍了
> 
> 如果root了可以用luckytool破解自启动这个个数限制。

嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..

**Comment by Chuhe2399** [comment]
> > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > 
> > > > 
> > > > 是的 只能取舍了
> > > 
> > > 
> > > 如果root了可以用luckytool破解自启动这个个数限制。
> > 
> > 买ios
> 
> 刚从IOS转过来,对于爱折腾的人来说 到了安卓就回不去了.

我用安卓都想转iOS了，折腾太久用处不大的，日常稳定就不错。

**Comment by kooritea** [comment]
> > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > 
> > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> 
> 
> 
> > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > 
> > > 
> > > 是的 只能取舍了
> > 
> > 如果root了可以用luckytool破解自启动这个个数限制。
> 
> 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..

因为fcm设计的理想情况是应用静止在后台等fcm的消息，但现实是应用只要在后台就不太可能呆着不动，所以才有了这个项目，既不需要应用留在后台也能接收到fcm

**Comment by csjoyxy** [comment]
> > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > 
> > 
> > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > 
> > > > 
> > > > 是的 只能取舍了
> > > 
> > > 
> > > 如果root了可以用luckytool破解自启动这个个数限制。
> > 
> > 
> > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> 
> 因为fcm设计的理想情况是应用静止在后台等fcm的消息，但现实是应用只要在后台就不太可能呆着不动，所以才有了这个项目，既不需要应用留在后台也能接收到fcm

嗯嗯 这样看来在原生安卓上体验很好 但是在定制ROM比如ColorOS  如果需要给应用自启动权限，应用本身就可以随时自启动，那么就达不到省电，省运存的目的了。
😂有没有可能给的自启动权限，只是开机的时候它启动一次，然后配合安卓13自带的墓碑系统冻结在后台，（我查看过确实一分钟左右没有活动会被v2冻结）fcm收到消息后才从冻结状态唤醒？这样的话fcm就比较有意义了。
![Uploading Screenshot_2023-12-23-18-48-23-14_9e8df3d0c7c1f50248b6ee043a653d26.jpg…]()

**Comment by SenLief** [comment]
> > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> 
> > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > 
> > > 
> > > 是的 只能取舍了
> > 
> > 
> > 如果root了可以用luckytool破解自启动这个个数限制。
> 
> 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..

如果app符合规则，那实际上app是会进入缓存状态，只保留一个推送进程，等待fcm推送后拉起，但是国产app不遵守这个规则。现在我的情况就是主动杀死，用模块当息屏或者进入后台主动杀死进程，这样就可以利用fcm推送fcmfix 然后再拉起app了。

**Comment by csjoyxy** [comment]
![Screenshot_2023-12-23-18-48-23-14_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/kooritea/fcmfix/assets/64026998/41cced6a-c3c6-4a27-ae09-d6b82ccde4f9)


> > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > 
> > 
> > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > 
> > > > 
> > > > 是的 只能取舍了
> > > 
> > > 
> > > 如果root了可以用luckytool破解自启动这个个数限制。
> > 
> > 
> > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> 
> 如果app符合规则，那实际上app

> > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > 
> > 
> > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > 
> > > > 
> > > > 是的 只能取舍了
> > > 
> > > 
> > > 如果root了可以用luckytool破解自启动这个个数限制。
> > 
> > 
> > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> 
> 如果app符合规则，那实际上app是会进入缓存状态，只保留一个推送进程，等待fcm推送后拉起，但是国产app不遵守这个规则。现在我的情况就是主动杀死，用模块当息屏或者进入后台主动杀死进程，这样就可以利用fcm推送fcmfix 然后再拉起app了。

请问一下，这些应用你给了自启动权限吧？那模块杀死进程后，这些APP不会自动启动了吗？另外求模块🤣🤣🤣

**Comment by SenLief** [comment]
> ![Screenshot_2023-12-23-18-48-23-14_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/64026998/292622186-41cced6a-c3c6-4a27-ae09-d6b82ccde4f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDI3MzAsIm5iZiI6MTcwMzM0MjQzMCwicGF0aCI6Ii82NDAyNjk5OC8yOTI2MjIxODYtNDFjY2VkNmEtYzNjNi00YTI3LWFlMDktZDZiODJjY2RlNGY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE0NDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNWY0ZDkxZTYxYzFlNzhlNTUyMGRlZjMzNGQ3NjU1YzExMGQ2Yjk2YWYyNzEwMTcxMjA3ZWRmNmYxODM1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZP8DX6t2Nvo050uMdgLD2o4-QWozqWRExv4v_CF-J4)
> 
> > > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > > 
> > > 
> > > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > > 
> > > > > 
> > > > > 是的 只能取舍了
> > > > 
> > > > 
> > > > 如果root了可以用luckytool破解自启动这个个数限制。
> > > 
> > > 
> > > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> > 
> > 
> > 如果app符合规则，那实际上app
> 
> > > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > > 
> > > 
> > > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > > 
> > > > > 
> > > > > 是的 只能取舍了
> > > > 
> > > > 
> > > > 如果root了可以用luckytool破解自启动这个个数限制。
> > > 
> > > 
> > > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> > 
> > 
> > 如果app符合规则，那实际上app是会进入缓存状态，只保留一个推送进程，等待fcm推送后拉起，但是国产app不遵守这个规则。现在我的情况就是主动杀死，用模块当息屏或者进入后台主动杀死进程，这样就可以利用fcm推送fcmfix 然后再拉起app了。
> 
> 请问一下，这些应用你给了自启动权限吧？那模块杀死进程后，这些APP不会自动启动了吗？另外求模块🤣🤣🤣

自启动不会无缘由的自启动的，我目前没发现，你可以用黑域一类的，我用的是thanox

**Comment by SenLief** [comment]
> ![Screenshot_2023-12-23-18-48-23-14_9e8df3d0c7c1f50248b6ee043a653d26](https://private-user-images.githubusercontent.com/64026998/292622186-41cced6a-c3c6-4a27-ae09-d6b82ccde4f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDI3MzAsIm5iZiI6MTcwMzM0MjQzMCwicGF0aCI6Ii82NDAyNjk5OC8yOTI2MjIxODYtNDFjY2VkNmEtYzNjNi00YTI3LWFlMDktZDZiODJjY2RlNGY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE0NDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNWY0ZDkxZTYxYzFlNzhlNTUyMGRlZjMzNGQ3NjU1YzExMGQ2Yjk2YWYyNzEwMTcxMjA3ZWRmNmYxODM1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZP8DX6t2Nvo050uMdgLD2o4-QWozqWRExv4v_CF-J4)
> 
> > > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > > 
> > > 
> > > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > > 
> > > > > 
> > > > > 是的 只能取舍了
> > > > 
> > > > 
> > > > 如果root了可以用luckytool破解自启动这个个数限制。
> > > 
> > > 
> > > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> > 
> > 
> > 如果app符合规则，那实际上app
> 
> > > > 因为启动应用广播被厂商的定制ROM拦截了，所以fcmfix就拉不起了。 在以前由system用户发出的启动广播是不会被拦的，现在被拦了之后就要么手动设置允许自启动，要么fcmfix适配rom做自启动限制的绕过。
> > > > 但是现在只有miui是有做正确适配就是不需要给自启动权限，其他除原生之外的一般都要。
> > > 
> > > 
> > > > > > 哎oppo这边自启动非推荐的只给5个自启动，也是绝了。
> > > > > 
> > > > > 
> > > > > 是的 只能取舍了
> > > > 
> > > > 
> > > > 如果root了可以用luckytool破解自启动这个个数限制。
> > > 
> > > 
> > > 嗯嗯 已经用上了, 一直搞不清自启动权限是开机的时候自己启动 还是应用在后台可以一直自启动的话,如果是这样的话 那就不能做到让它乖乖休眠,一直活跃在后台.那FCM就没什么意义了吧.个人愚见..
> > 
> > 
> > 如果app符合规则，那实际上app是会进入缓存状态，只保留一个推送进程，等待fcm推送后拉起，但是国产app不遵守这个规则。现在我的情况就是主动杀死，用模块当息屏或者进入后台主动杀死进程，这样就可以利用fcm推送fcmfix 然后再拉起app了。
> 
> 请问一下，这些应用你给了自启动权限吧？那模块杀死进程后，这些APP不会自动启动了吗？另外求模块🤣🤣🤣

自启动不会无缘由的自启动的，我目前没发现，你可以用黑域一类的，我用的是thanox

**Comment by vHrqO** [comment]
> 😂有没有可能给的自启动权限，只是开机的时候它启动一次，然后配合安卓13自带的墓碑系统冻结在后台，（我查看过确实一分钟左右没有活动会被v2冻结）fcm收到消息后才从冻结状态唤醒？这样的话fcm就比较有意义了。

這個 https://github.com/Nep-Timeline/NoA-Epsilon , https://noactive.sakion.top/
> FCM解冻: 当应用接收 [FCM推送](https://firebase.google.com/docs/cloud-messaging) 时临时解冻应用，确保消息送达

**Comment by SenLief** [comment]
> > 😂有没有可能给的自启动权限，只是开机的时候它启动一次，然后配合安卓13自带的墓碑系统冻结在后台，（我查看过确实一分钟左右没有活动会被v2冻结）fcm收到消息后才从冻结状态唤醒？这样的话fcm就比较有意义了。
> 
> 這個 https://github.com/Nep-Timeline/NoA-Epsilon , https://noactive.sakion.top/
> 
> > FCM解冻: 当应用接收 [FCM推送](https://firebase.google.com/docs/cloud-messaging) 时临时解冻应用，确保消息送达

这个有些app不遵守规则的，他不会自己进入缓存。
