### ISSUE TITLE
反馈一个奇怪的bug

### ISSUE THREAD

**Issue by Bluenight-beta** [kooritea/fcmfix#138]
我使用Google Pixel Watch 的Google助手会导致手机的Google App发生错误以下是错误日志和bug百分百触发方法。
（不知道其他的Wear os的Google语音助手会不会有这个问题反正我遇到了）
（没有装这个模块之前不会有任何问题但装了之后就会有这个问题，问题是我不装收不到推送啊）
https://github.com/kooritea/fcmfix/assets/148428813/3ca71f05-3ed0-4e2d-bcc5-9a9d8c45898d
![screenshot-2024-02-22-17-49-10](https://github.com/kooritea/fcmfix/assets/148428813/73886e8c-e57c-410e-974d-787c8ce3c431)

**Comment by Bluenight-beta** [comment]
不知道为什么上传了一个空的日子文件我重新复制再补一下吧以下是日志。
Generated by AppErrorsTracking 1.3-53c6f8a(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Nothing
[Device Model]: A063
[Display]: U2.5-240119-1910
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_TW_#Hant
[Process ID]: 29603
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.google.android.googlequicksearchbox
[Version Name]: 15.7.45.28.arm64
[Version Code]: 301313673
[Target SDK]: 34
[Min SDK]: 28
[Error Type]: JVM
[Crash Time]: 2024-02-22T17:54:46.741
[Stack Trace]:
java.lang.RuntimeException: Unchecked exception running task: alxy[Request UsageReportingApiClientWrapper disconnects]
	at asck.setException(PG:6)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at ephl.run(PG:1)
	at gzvb.run(PG:23)
	at epgo.run(PG:2)
	at java.lang.Thread.run(Thread.java:1012)
	at ephq.run(PG:6)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.sendEmptyMessage(int)' on a null object reference
	at alxy.run(PG:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 5 more

**Comment by kooritea** [comment]
lsposed里面不要勾选gms试试，hook gms并无实际作用

**Comment by Bluenight-beta** [comment]
试过了还是会崩
![Screenshot_20240222-182928](https://github.com/kooritea/fcmfix/assets/148428813/fcffc7ea-5163-4954-b294-5cbaa0bf3ab1)
[com.google.android.googlequicksearchbox_2024-02-22T18_29_59.725.log](https://github.com/kooritea/fcmfix/files/14372648/com.google.android.googlequicksearchbox_2024-02-22T18_29_59.725.log)
[Uploading LSPosed_2024-02-22T18_32_37.949457.zip…]()

**Comment by Bluenight-beta** [comment]
查到了Google的[Wear os官方模拟器](https://developer.android.com/training/wearables/get-started/creating#prepare-watch) 模拟器里面带Google助手应该是可以用来调试。
