### ISSUE TITLE
时不时的会断练，要过好久才重连，这是咋回事呀

### ISSUE THREAD

**Issue by suaosong1** [kooritea/fcmfix#14]
有时候查看能连上，有时候看就连不上。。。是因为切换了网络的原因吗？

**Comment by kooritea** [comment]
附个fcm日志看看

**Comment by suaosong1** [comment]
> 附个fcm日志看看

![Screenshot_2021-08-01-08-01-49-306_com google android gms](https://user-images.githubusercontent.com/70273859/127755388-c5705494-fb30-4c36-93b0-d4e1760934d6.jpg)
![Screenshot_2021-08-01-08-01-49-306_com google android gms](https://user-images.githubusercontent.com/70273859/127755390-96f4de12-64ed-475f-8380-e094162ba725.jpg)
这是日志老哥，有时候显示没连接fcm，但是电报还可以正常推送。。

**Comment by suaosong1** [comment]
> 附个fcm日志看看

![Screenshot_2021-07-31-22-09-14-640_com google android gms](https://user-images.githubusercontent.com/70273859/127755398-b57d131e-0517-4a75-bb38-6e67680974fb.jpg)
上面发重复了。。

**Comment by suaosong1** [comment]
> 附个fcm日志看看

老哥，这个链接是时而能连上时而连不上，我刚才更新了一下谷歌服务，就连上了了，
![Screenshot_2021-08-01-08-41-56-471_bin mt plus](https://user-images.githubusercontent.com/70273859/127755581-7eb3defd-6d0d-449c-832e-5f42594faa1b.jpg)
这是连上的日志。。等下次连不上了了我再来发日志图。

**Comment by suaosong1** [comment]
> 附个fcm日志看看

![Screenshot_2021-08-01-08-45-13-960_bin mt plus](https://user-images.githubusercontent.com/70273859/127755615-bce9d13f-02f0-4104-ad47-443e59f07803.jpg)

**Comment by kooritea** [comment]
重连时间是根据无法连接次数增长的，如果断开太久下次重连的时间也是很久，切换网络或者重启谷歌服务才会马上重连

**Comment by suaosong1** [comment]
> 重连时间是可以确定无法连接次数的，如果再次连接太久再连的时间也是可能的，切换或者网络重启谷歌服务会马上重连

那什么情况下会断呢？我就是感觉有时候突然就断了，我把心跳时间改成0了  不知道会不会好一点。

**Comment by suaosong1** [comment]
> 重连时间是可以确定无法连接次数的，如果再次连接太久再连的时间也是可能的，切换网络重启谷歌服务或者马上重连

我把心跳时间改成0了会不会好一点，我再感受感受。。老哥，有问题我随时来这里向你反馈以及询问

**Comment by kooritea** [comment]
心跳只能防止fcm连接长时间没有消息被意外断开，连不上就没办法了

**Comment by suaosong1** [comment]
> 惊魂未定，连长没有消息被突然断开，连不上一桩了

又断开了，日志显示这样。。
![Screenshot_2021-08-01-15-26-52-103_bin mt plus](https://user-images.githubusercontent.com/70273859/127762968-4abaea62-6962-4aca-a585-52dbce7139a9.jpg)

**Comment by kooritea** [comment]
日志的图错了

**Comment by suaosong1** [comment]
> 日志的图错了

这个嘛
![Screenshot_2021-08-01-16-45-52-194_com google android gms](https://user-images.githubusercontent.com/70273859/127765051-60642e6a-54a8-47c0-b328-d5779c3030af.jpg)

**Comment by kooritea** [comment]
看不出什么，把fcmfix里tg的勾去了，等一下再截

**Comment by suaosong1** [comment]
勾走了，突然又连上了
![Screenshot_2021-08-01-19-45-28-551_com google android gms](https://user-images.githubusercontent.com/70273859/127769670-27397b63-3433-4974-ba13-348fb9ca4adb.jpg)


> 看不出什么，把fcmfix里tg的勾走，等一下再截图

**Comment by suaosong1** [comment]
> 看不出什么，把fcmfix里tg的勾走，等一下再截图

老哥，能留个联系方式吗？这样沟通太费劲了。。

**Comment by ayanamist** [comment]
我这也有这个问题，观察了几天，貌似锁屏后过了一会GMS就不会再读这个到mtalk的长链接了，要解锁后才会恢复（光亮屏好像还没用），然后看日志就是在解锁那个时间突然收到一个server hb，然后连接就立刻断了。用hosts大法把mtalk长链接劫持到自己国内的vps上，能观察到是GMS自己主动断开长链接的，不是远端断开。这期间的push都不灵。
而且解锁后有可能并不会重连，下次重连时间依旧是负数，感觉是锁屏后GMS被MIUI冻结了，不会维持这个长链接的读取，长链接断开后虽然有你的补丁，但你补丁发的intent也因为种种原因没生效，导致依旧是负数。
手机是小米10 MIUI 12.5.5稳定版。这问题困扰好久，不知道有没有什么思路。

**Comment by kooritea** [comment]
@ayanamist 这种看着就像是长时间没有数据互通然后链接被代理掐掉的，日志里有[fcmfix] Send broadcast GCM_RECONNECT 吗

**Comment by ayanamist** [comment]
没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。

**Comment by suaosong1** [comment]
> 我这也有这个问题，观察了几天，貌似锁屏后过了一会GMS就不会再读这个到mtalk的长链接了，要解锁后才会恢复（光亮屏好像还没用），然后看日志就是在解锁那个时间突然收到一个server hb，然后连接就立刻断了。用hosts大法把mtalk长链接劫持到自己国内的vps上（然后走自己的私有协议翻墙出去连接真正的mtalk服务），能观察到是GMS自己主动断开长链接的，不是远端断开。这期间的push都不灵。
> 而且解锁后有可能并不会重连，下次重连时间依旧是负数，感觉是锁屏后GMS被MIUI冻结了，不会维持这个长链接的读取，长链接断开后虽然有你的补丁，但你补丁发的intent也因为种种原因没生效，导致依旧是负数。
> 手机是小米10 MIUI 12.5.5稳定版。这问题困扰好久，不知道有没有什么思路。

你的稳定版还好，只是息屏受不到，我是开发版，fcm直接被砍断了。。miui我真服了

**Comment by ayanamist** [comment]
> > 我这也有这个问题，观察了几天，貌似锁屏后过了一会GMS就不会再读这个到mtalk的长链接了，要解锁后才会恢复（光亮屏好像还没用），然后看日志就是在解锁那个时间突然收到一个server hb，然后连接就立刻断了。用hosts大法把mtalk长链接劫持到自己国内的vps上（然后走自己的私有协议翻墙出去连接真正的mtalk服务），能观察到是GMS自己主动断开长链接的，不是远端断开。这期间的push都不灵。
> > 而且解锁后有可能并不会重连，下次重连时间依旧是负数，感觉是锁屏后GMS被MIUI冻结了，不会维持这个长链接的读取，长链接断开后虽然有你的补丁，但你补丁发的intent也因为种种原因没生效，导致依旧是负数。
> > 手机是小米10 MIUI 12.5.5稳定版。这问题困扰好久，不知道有没有什么思路。
> 
> 你的稳定版还好，只是息屏受不到，我是开发版，fcm直接被砍断了。。miui我真服了

你先确定下你的网络环境下是否能正常连接mtalk的那些域名，未必能连通的，这不是MIUI的问题。

**Comment by suaosong1** [comment]
![Screenshot_2021-08-02-09-21-45-409_com google android gms](https://user-images.githubusercontent.com/70273859/127792451-6fe76c53-73cf-4e00-830a-07eb60bfa04f.jpg)
![Screenshot_2021-08-02-09-21-25-449_com google android gms](https://user-images.githubusercontent.com/70273859/127792457-4e050a1d-bcf4-4e4b-a8db-78e500f4fc68.jpg)
你看我这个，很久没重连了。。

**Comment by suaosong1** [comment]
> > > 我这也有这个问题，观察了几天，貌似锁屏后过了一会GMS就不会再读这个到mtalk的长链接了，要解锁后才会恢复（光亮屏好像还没用），然后看日志就是在解锁那个时间突然收到一个server hb，然后连接就立刻断了。用hosts大法把mtalk长链接劫持到自己国内的vps上（然后走自己的私有协议翻墙出去连接真正的mtalk服务），能观察到是GMS自己主动断开长链接的，不是远端断开。这期间的push都不灵。
> > > 而且解锁后有可能并不会重连，下次重连时间依旧是负数，感觉是锁屏后GMS被MIUI冻结了，不会维持这个长链接的读取，长链接断开后虽然有你的补丁，但你补丁发的intent也因为种种原因没生效，导致依旧是负数。
> > > 手机是小米10 MIUI 12.5.5稳定版。这问题困扰好久，不知道有没有什么思路。
> > 
> > 
> > 你的稳定版还好，只是息屏受不到，我是开发版，fcm直接被砍断了。。miui我真服了
> 
> 你先确定下你的网络环境下是否能正常连接mtalk的那些域名，未必能连通的，这不是MIUI的问题。

老哥，我刚才试了下。还真的连不上Host: alt8-mtalk.google.com这个域名。。那怎么解决呀？

**Comment by kooritea** [comment]
> 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。

有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效

**Comment by suaosong1** [comment]
> > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> 
> 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效

老哥你看下我这个，又连不上了。。

> > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> 
> 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效

老哥你看下我这个，又连不上了。
![Screenshot_2021-08-02-10-03-56-234_com google android gms](https://user-images.githubusercontent.com/70273859/127795055-2eb11ae5-e2ba-4d4c-a347-be70bafe92b4.jpg)

**Comment by kooritea** [comment]
> > > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> > 
> > 
> > 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效
> 
> 老哥你看下我这个，又连不上了。。
> 
> > > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> > 
> > 
> > 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效
> 
> 老哥你看下我这个，又连不上了。
> ![Screenshot_2021-08-02-10-03-56-234_com google android gms](https://user-images.githubusercontent.com/70273859/127795055-2eb11ae5-e2ba-4d4c-a347-be70bafe92b4.jpg)

你的代理是不是用了分应用代理什么的

**Comment by ayanamist** [comment]
> > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> 
> 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效

有的，其他日志都在，什么LocalNotification那些，模块肯定生效了的

**Comment by kooritea** [comment]
> > > 没有被系统掐掉，我在VPS上能看到这个长链接在我解锁之前都还存在的。
> > > 没有你说的这个日志，应该说进入这个贤者状态后啥日志都没，你的日志也是靠一个intent来打印的，怀疑一起被吃掉了。
> > 
> > 
> > 有其他[fcmfix]开头的日志么，或者xp框架里有没有什么报错日志，会不会是模块没生效
> 
> 有的，其他日志都在，什么LocalNotification那些，模块肯定生效了的
LocalNotification 和日志都是固定的hook位置，但是自动重连的hook点是动态的，不一定能正确找到命中，还是要看xposed的日志看看有没有什么输出
