### ISSUE TITLE
Android 14 HyperOS 墓碑後無法成功推送

### ISSUE THREAD

**Issue by hexSophia** [kooritea/fcmfix#140]
手機是Xiaomi 14 Ultra (aurora)
系統是1.0.8.0.UNACNXM
 
應用在後台一段時間被墓碑後就無法成功拉起
應用沒開自啟動 給了無限制後台

使用PR內的版本可以減少狀況 不過會有通知延遲的情況

**Comment by kooritea** [comment]
已知问题，现在没有做绕过墓碑机制的hook。

那个pr把所有的应用都无差别放行了，这个肯定不能直接合到主线，但是我现在没有android14的设备所以也没法去调整

**Comment by hexSophia** [comment]
好的 感謝作者了 一直用的你的模塊

**Comment by Rakau** [comment]
> 好的 感謝作者了 一直用的你的模塊

https://github.com/Nep-Timeline/Freezer

**Comment by studentluo** [comment]
> 已知问题，现在没有做绕过墓碑机制的hook。
> 
> 那个pr把所有的应用都无差别放行了，这个肯定不能直接合到主线，但是我现在没有android14的设备所以也没法去调整

期待作者解决墓碑问题。我是K40，从MIUI 14升级的澎湃(依然是安卓13)。被墓碑的软件也无法成功推送，折腾两天了😂😂😂原来是已知问题，以前墓碑都是好的，有点难受。只能耐心等待了

**Comment by Nep-Timeline** [comment]
使用官方Millet 或者使用Thanox之類的應用在FCM推送時對目標進程解凍即可

**Comment by kooritea** [comment]
用最新的发布应该就可以了

**Comment by studentluo** [comment]
造孽啊，安卓13的hyper os被墓碑了，还是收不到信息。😄坑爹系统

**Comment by Nep-Timeline** [comment]
> 造孽啊，安卓13的hyper os被墓碑了，还是收不到信息。😄坑爹系统

A14也一样...

**Comment by jordanyoong1** [comment]
> > 造孽啊，安卓13的hyper os被墓碑了，还是收不到信息。😄坑爹系统
> 
> A14也一样...

一样
