### ISSUE TITLE
Auto Release 20240421-7e9d08e 于 Android 14 不可用？

### ISSUE THREAD

**Issue by senzyo** [kooritea/fcmfix#142]
最新版本 [Auto Release 20240421-7e9d08e](https://github.com/kooritea/fcmfix/releases/tag/20240421-7e9d08e) 无法唤起应用，表现为 `Failed to broadcast to stopped app <PACKAGE>`。
上个版本 [Auto Release 20240412-7b742f8](https://github.com/kooritea/fcmfix/releases/tag/20240412-7b742f8) 一切正常。

系统: LineageOS 21 (Android 14) 
LSPosed 作用域: 均只勾选了 `系统框架`

**Comment by kooritea** [comment]
看看xposed里面有没有保存信息？

**Comment by senzyo** [comment]
> 看看xposed里面有没有保存信息？

我不明白这句话的意思。这是开机后的 LSPosed 日志和 FCM EVENT 日志：
[LSPosed_2024-04-21T19_31_36.617149.zip](https://github.com/kooritea/fcmfix/files/15051690/LSPosed_2024-04-21T19_31_36.617149.zip)

<img src="https://github.com/kooritea/fcmfix/assets/147815563/8eaf36d1-6974-4061-a0ec-e31257b763b6" height="800" width="auto">

**Comment by kooritea** [comment]
写错字，我就是要这个（
晚点看看

**Comment by kooritea** [comment]
把fcmfix本体打开试试？可能是没读取到设置的应用列表

**Comment by senzyo** [comment]
> 把fcmfix本体打开试试？可能是没读取到设置的应用列表

fcmfix 本体是处于前台打开状态的，但仍然 `Failed to broadcast to stopped app <PACKAGE>`。
我还把另一个 LSPosed 模块 Thanox 停掉 (虽然本来就没什么影响) 又测试了几次，但没有改善。
另外，我要把上面这条 [消息](https://github.com/kooritea/fcmfix/issues/142#issuecomment-2068013540) 删掉哈，其中的 LSPosed 日志 zip 里有我的一点个人信息。

**Comment by kooritea** [comment]
原来是pr里把安卓14排除出去了…
等下试试新的ci构建

**Comment by senzyo** [comment]
正常了，感谢。
