### ISSUE TITLE
在fcmfix设定中勾选了全选包含FCM应用反而不能用了，是我理解错误吗？

### ISSUE THREAD

**Issue by huang5307** [kooritea/fcmfix#143]
我的小米12 Pro 是hyper os，所以我没有办法root，当然也没有安卓magisk，我安装fcmfix希望能达到我安装的line能推送消息的功能。我安装了最新版以后，不管是消息还是语音电话都能接收👍。但是很奇怪的是我在在fcmfix设定中勾选了全选包含FCM应用反而不能用了，我的理解是勾选了这些才代表被fcmfix接管吧？但实际的情况是，不勾选能及时接收，勾选之后不能接收或是非常延迟的接收，是我理解错误吗？

**Comment by TigerBeanst** [comment]
理论上来说，只要你没在 Xposed 中勾选它，他是压根不会起一丁点作用的……

**Comment by huang5307** [comment]
> 理论上来说，只要你没在 Xposed 中勾选它，他是压根不会起一丁点作用的……

但……，它真的能通知了哎！是不是因为fcmfix解决了mtalk被墙的问题？

**Comment by TigerBeanst** [comment]
> > 理论上来说，只要你没在 Xposed 中勾选它，他是压根不会起一丁点作用的……
> 
> 但……，它真的能通知了哎！是不是因为fcmfix解决了mtalk被墙的问题？

解决不了哦，fcmfix 本身并不能也不会解决连接不上的问题，它的作用只是确保 fcm 在能连接的基础上正常工作，防止因为系统本身原因，对应的 App 拉不起来

**Comment by huang5307** [comment]
> > > 理论上来说，只要你没在 Xposed 中勾选它，他是压根不会起一丁点作用的……
> > 
> > 
> > 但……，它真的能通知了哎！是不是因为fcmfix解决了mtalk被墙的问题？
> 
> 解决不了哦，fcmfix 本身并不能也不会解决连接不上的问题，它的作用只是确保 fcm 在能连接的基础上正常工作，防止因为系统本身原因，对应的 App 拉不起来

我不懂原理，但是我亲身做实验有效。刚刚又再次实验，如果把fcmfix的省电策略设成智能限制并不让它自启，这样line的通知就接收不到了，但是省电策略改成无限制，并且自动启动，这样line的消息跟语音都能收到了。

**Comment by huang5307** [comment]
另外也不能在fcmfix里面选中fcm应用全选，让它保持都是空的，这样就能通知了。
