### ISSUE TITLE
[BUG] 勾选应用后无法联网

### ISSUE THREAD

**Issue by yours57** [kooritea/fcmfix#145]
使用0426版的fcmfix，软件中勾选nekogram（三方tg），然后打开对应的vpn软件（尝试了cmfa,nb4a）。
在使用一段时间（时间不定）手机之后，nekogram无法联网。与此同时，其他软件可以正常联网。
手机重启可正常联网，但一段时间后就又会出现上面情况。
卸载该版本fcmfix后，恢复正常。
之前版本未出现该情况。

**Comment by TigerBeanst** [comment]
Nekogram 无法联网时，有没有试过强行停止它重新打开

**Comment by kooritea** [comment]
作用域勾了哪些

**Comment by yours57** [comment]
描述一个可能的复现步骤：
关闭vpn，fcm显示connected
然后打开vpn，在fcmfix中勾选过的应用则无法连接到网络（不是显示无网络连接，而是一直在转圈）

**Comment by yours57** [comment]
hosts如下设置即可，~对之前未如此设置，反而能正常使用感到疑惑~


108.177.125.188 [mtalk.google.com](http://mtalk.google.com/)
3.3.3.3 [alt1-mtalk.google.com](http://alt1-mtalk.google.com/)
3.3.3.3 [alt2-mtalk.google.com](http://alt2-mtalk.google.com/)
74.125.200.188 [alt3-mtalk.google.com](http://alt3-mtalk.google.com/)
74.125.200.188 [alt4-mtalk.google.com](http://alt4-mtalk.google.com/)
3.3.3.3 [alt5-mtalk.google.com](http://alt5-mtalk.google.com/)
3.3.3.3 [alt6-mtalk.google.com](http://alt6-mtalk.google.com/)
74.125.200.188 [alt7-mtalk.google.com](http://alt7-mtalk.google.com/)
3.3.3.3 [alt8-mtalk.google.com](http://alt8-mtalk.google.com/)
2404:6800:4008:c07::bc [mtalk.google.com](http://mtalk.google.com/)
2607:f8b0:4023:c0b::bc [alt1-mtalk.google.com](http://alt1-mtalk.google.com/)
2607:f8b0:4023:1::bc [alt5-mtalk.google.com](http://alt5-mtalk.google.com/)
2607:f8b0:4002:c03::bc [alt7-mtalk.google.com](http://alt7-mtalk.google.com/)

参考链接 [https://www.v2ex.com/t/966150#r_13515216](https://www.v2ex.com/t/966150#r_13515216)
