### ISSUE TITLE
HyperOS有概率在解锁后卡顿3-5秒

### ISSUE THREAD

**Issue by hfdem** [kooritea/fcmfix#146]
fcmfix 版本 20240426_13f13a7
lsposed 作用域为系统框架

手机从黑屏状态解锁后，有概率会卡顿3-5秒，这几秒可以上下滑动但全面屏手势无效，不能退出应用返回桌面
最近几周才出现了这个问题，经过排查发现禁用掉fcmfix就好了

**Comment by kooritea** [comment]
有可能是fcm来通知了触发fcmfix去读配置文件了
试试[0422](https://github.com/kooritea/fcmfix/releases/tag/20240422-bc5d0c3)

**Comment by hfdem** [comment]
> 有可能是 fcm 来通知了触发 fcmfix 去读配置文件了 试试[0422](https://github.com/kooritea/fcmfix/releases/tag/20240422-bc5d0c3)

我试试，一段时间后再来反馈

**Comment by hfdem** [comment]
> > 有可能是 fcm 来通知了触发 fcmfix 去读配置文件了 试试 [0422](https://github.com/kooritea/fcmfix/releases/tag/20240422-bc5d0c3)
> 
> 我试试，一段时间后再来反馈

这个版本没问题，作用域为系统框架和play服务，也可以正常使用

**Comment by zxyist** [comment]
不止解锁，开启关闭静音模式，充电的时候，都有概率卡住几秒再反应。

**Comment by hfdem** [comment]
> 有可能是 fcm 来通知了触发 fcmfix 去读配置文件了 试试[0422](https://github.com/kooritea/fcmfix/releases/tag/20240422-bc5d0c3)

这个版本也会卡，只勾选几个app也会卡。我现在的用法是作用域只勾选电量与性能，然后需要拉起的应用勾上自启动。

**Comment by zym013579** [comment]
> 有可能是fcm来通知了触发fcmfix去读配置文件了 试试[0422](https://github.com/kooritea/fcmfix/releases/tag/20240422-bc5d0c3)

@kooritea 您好，我也存在这个问题。我试了一下历史版本，0412是最后一个不存在这个问题的版本，再往后都有这个问题

**Comment by Orokapei** [comment]
同样的问题，没有总结出什么情况下会复现

**Comment by kooritea** [comment]
0412开始的话应该是自启动的hook有问题吧，看看卡顿时候输出的日志

**Comment by Orokapei** [comment]
> 0412开始的话应该是自启动的hook有问题吧，看看卡顿时候输出的日志

[verbose_2024-05-18T13:22:46.990334.log](https://github.com/kooritea/fcmfix/files/15362965/verbose_2024-05-18T13.22.46.990334.log)
[modules_2024-05-18T13:25:35.361404.log](https://github.com/kooritea/fcmfix/files/15362971/modules_2024-05-18T13.25.35.361404.log)
大概19：07左右出现了一次，刚好发现

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/15371765/app-release.zip)
改了一下日志输出和让日志输出到xposed了，有空用这个再抓一下日志吧

**Comment by zym013579** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/15371765/app-release.zip) 改了一下日志输出和让日志输出到xposed了，有空用这个再抓一下日志吧

@kooritea 大概18:43插充电器，卡了一会儿才跳出充电界面。另外大概18:55左右，解锁后全面屏手势失效。
[LSPosed_2024-05-20T18_56_23.269380.zip](https://github.com/kooritea/fcmfix/files/15376207/LSPosed_2024-05-20T18_56_23.269380.zip)

**Comment by kooritea** [comment]
> > [app-release.zip](https://github.com/kooritea/fcmfix/files/15371765/app-release.zip) 改了一下日志输出和让日志输出到xposed了，有空用这个再抓一下日志吧
> 
> @kooritea 大概18:43插充电器，卡了一会儿才跳出充电界面。另外大概18:55左右，解锁后全面屏手势失效。
> [LSPosed_2024-05-20T18_56_23.269380.zip](https://github.com/kooritea/fcmfix/files/15376207/LSPosed_2024-05-20T18_56_23.269380.zip)
> 

有没有一个时间点是有fcm通知的？

**Comment by zym013579** [comment]
> > > [app-release.zip](https://github.com/kooritea/fcmfix/files/15371765/app-release.zip) 改了一下日志输出和让日志输出到xposed了，有空用这个再抓一下日志吧
> > 
> > 
> > @kooritea 大概18:43插充电器，卡了一会儿才跳出充电界面。另外大概18:55左右，解锁后全面屏手势失效。
> > [LSPosed_2024-05-20T18_56_23.269380.zip](https://github.com/kooritea/fcmfix/files/15376207/LSPosed_2024-05-20T18_56_23.269380.zip)
> 
> 有没有一个时间点是有fcm通知的？

没有fcm通知，我感觉卡顿跟通知没什么关系，我以前一直以为是系统问题，直到看到了这个issue

**Comment by TigerBeanst** [comment]
> 是的，卡顿和通知没有关系，现在是fcmfix接收到任意一个广播都会应用自启动的hook，现在猜测是开屏锁屏的时候同时尝试启动多个应用cpu占满导致卡顿。
> 
> 需要日志看看接收fcm通知的时候是什么广播，把应用自启动的hook限定到fcm广播应该就好了

严格来说，手机没有卡顿（上下滑动，点App里的东西是很流畅的），主要在于没办法上滑回桌面啥的……

**Comment by Orokapei** [comment]
大概10：50左右出现，用的上面的apk
[modules_2024-05-22T00:19:05.571311.log](https://github.com/kooritea/fcmfix/files/15397459/modules_2024-05-22T00.19.05.571311.log)
[verbose_2024-05-22T00:18:55.308377.log](https://github.com/kooritea/fcmfix/files/15397460/verbose_2024-05-22T00.18.55.308377.log)

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/15397614/app-release.zip)

**Comment by hfdem** [comment]
[20240524_ff116bf](https://github.com/kooritea/fcmfix/releases/tag/40-20240524_ff116bf) 应该是修好了
