### ISSUE TITLE
lsp仓库提示更新问题

### ISSUE THREAD

**Issue by StrayJoker** [kooritea/fcmfix#148]
fcmfix在lsp仓库的最新版本是20240426_xxx
github上的新版都会在lsp中提示更新
大佬能不能刷高点版本号🤣

**Comment by kooritea** [comment]
就是想着ci发布测试下，这几天没人报严重问题就发在线仓库了

**Comment by StrayJoker** [comment]
不怎么了解lsp仓库检测更新机制
但我看这几版的版本号都是40
ci测试迭代更新的时候如果写高版本号，应该就不会提示更新了吧

**Comment by kooritea** [comment]
是我手动控制的，更新versionCode ci就会提交到lsposed仓库

**Comment by PDxtXHd** [comment]
@kooritea 大佬是不是最近又忘记提交更新了？lsposed仓库的版本比ci落后很多，目前ci也没有明显的问题，可以推到仓库了~
