### ISSUE TITLE
HyperOS下划出后台卡片不能杀死后台

### ISSUE THREAD

**Issue by GitHubd3b7c** [kooritea/fcmfix#149]
想问一下，划卡不清后台是有意设计成这样的吗。还是说出现了什么错误。
已经通过排除法确定了是fcmfix导致
作用域只勾选了系统框架

**Comment by TigerBeanst** [comment]
确实是 HyperOS 后出现的（

我这边估计是 cfa 测试版的问题，有时候Play商店会没网，得彻底鲨掉打开才有网，但又因为模块的原因，我现在得在灭霸里配置让它后台卡片消失的时候被杀（

**Comment by kooritea** [comment]
不是有意设计成这这样的，但是具体是哪一个钩子造成的，我也不清楚（
如果方便的话可以用这个apk抓一下日志给我
https://github.com/kooritea/fcmfix/issues/146#issuecomment-2119536549

**Comment by GitHubd3b7c** [comment]
安装该后重启，分别开启亚马逊、spotify、temu、shein后划掉后台的日志。
[LSPosed_2024-05-29T23_57_53.101411.zip](https://github.com/kooritea/fcmfix/files/15486314/LSPosed_2024-05-29T23_57_53.101411.zip)


> 不是有意设计成这这样的，但是具体是哪一个钩子造成的，我也不清楚（ 如果方便的话可以用这个apk抓一下日志给我 [#146 (comment)](https://github.com/kooritea/fcmfix/issues/146#issuecomment-2119536549)

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/15492879/app-release.zip)
试试这个

**Comment by GitHubd3b7c** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/15492879/app-release.zip) 试试这个

仍然无法划卡杀后台
[LSPosed_2024-05-30T12_39_26.621029.zip](https://github.com/kooritea/fcmfix/files/15493373/LSPosed_2024-05-30T12_39_26.621029.zip)

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/15494199/app-release.zip)
这个呢

**Comment by GitHubd3b7c** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/15494199/app-release.zip)
> 这个呢

解决了，感谢

**Comment by kooritea** [comment]
需要看看fcm来的时候还能不能自启，上面那个干掉了三个hook，有两个作用不知道，有一个就确定了是这个划卡片的白名单了

**Comment by GitHubd3b7c** [comment]
> 需要看看fcm来的时候还能不能自启，上面那个干掉了三个hook，有两个作用不知道，有一个就确定了是这个划卡片的白名单了

不给自启权限不能拉起应用了，会显示No respond

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/15499774/app-release.zip)
试试这个，不行的话发一下日志和framework.jar和services.jar

**Comment by GitHubd3b7c** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/15499774/app-release.zip)
> 试试这个，不行的话发一下日志和framework.jar和services.jar

神医，可以推送了，也可以清后台

**Comment by nnna21** [comment]
I installed hyper os with latest version in mi 9.when i unlock the phone display stuck for 1.5 mint to 2 mint and system work properly 
Can anyone know the solution
