### ISSUE TITLE
锁屏后FCM失效

### ISSUE THREAD

**Issue by ayanamist** [kooritea/fcmfix#15]
先说一下，不是fcmfix导致的问题，探讨下看看有没有思路。

from https://github.com/kooritea/fcmfix/issues/14#issuecomment-890550817

大概就是这样，如下面的截图，3点多长连接断开，next reconnect就是负数了，也没有任何日志，8点半我解锁了手机，也没有恢复过来，这是我遇到的其中一种情况（姑且称之为情况A）。另一种描述的情况B我今天抓了截图后再补充comment

![Screenshot_2021-08-02-08-35-15-510_com google android gms](https://user-images.githubusercontent.com/406779/127797598-ecb9a3c5-f641-4697-954c-4a391f0baaa2.jpg)

![Screenshot_2021-08-02-08-35-04-954_com google android gms](https://user-images.githubusercontent.com/406779/127797603-8300772e-ba0d-4ad7-b215-21dde7e09245.jpg)

**Comment by kooritea** [comment]
你这个是国内版吗，会不会是国内版的睡眠模式的问题
设置->电池->右上角->场景配置->睡眠模式

**Comment by ayanamist** [comment]
睡眠模式肯定关了的，而且白天也这样的，只是刚好有个图，就抛出来了

**Comment by kooritea** [comment]
emm，要不强制停止一下play服务，然后等play服务重启后再看一下fcm最上面的几条日志？

**Comment by ayanamist** [comment]
> emm，要不强制停止一下play服务，然后等play服务重启后再看一下fcm最上面的几条日志？

清空lsposed的日志，杀掉GMS，再启动，截图如下

![Screenshot_2021-08-02-11-36-20-759_com google android gms](https://user-images.githubusercontent.com/406779/127801319-852493dc-fd00-44f7-9608-9f87fd821ddf.jpg)

lsposed的日志看起来也正常

```
2021-08-02 03:36:08.008 I/com.google.android.gms.persistent(995-995): [fcmfix] start hook com.google.android.gms
2021-08-02 03:36:08.008 I/com.google.android.gms(985-985): [fcmfix] start hook com.google.android.gms
2021-08-02 03:36:10.010 I/com.google.android.gms.ui(1293-1293): [fcmfix] start hook com.google.android.gms
```

**Comment by ayanamist** [comment]
不过看起来确实又像没有生效，因为居然有 `Failed to broadcast to stopped app` 这个日志，按道理你这个module应该hook掉了这个才对，hook系统我也是勾选了的

![Screenshot_2021-08-02-11-32-45-350_com google android gms](https://user-images.githubusercontent.com/406779/127801569-ad9e60e3-998a-45e2-8513-a1cfba153275.jpg)

**Comment by kooritea** [comment]
> 不过看起来确实又像没有生效，因为居然有 `Failed to broadcast to stopped app` 这个日志，按道理你这个module应该hook掉了这个才对，hook系统我也是勾选了的
> 
> ![Screenshot_2021-08-02-11-32-45-350_com google android gms](https://user-images.githubusercontent.com/406779/127801569-ad9e60e3-998a-45e2-8513-a1cfba153275.jpg)

看起来没问题，只有在fcmfix勾选了的应用才不会出现`Failed to broadcast to stopped app`，对于没勾选的应用这个是正常的

**Comment by ayanamist** [comment]
> > 不过看起来确实又像没有生效，因为居然有 `Failed to broadcast to stopped app` 这个日志，按道理你这个module应该hook掉了这个才对，hook系统我也是勾选了的
> > ![Screenshot_2021-08-02-11-32-45-350_com google android gms](https://user-images.githubusercontent.com/406779/127801569-ad9e60e3-998a-45e2-8513-a1cfba153275.jpg)
> 
> 看起来没问题，只有在fcmfix勾选了的应用才不会出现`Failed to broadcast to stopped app`，对于没勾选的应用这个是正常的，或者是你没有给勾选的应用`自启动->被系统唤醒`的权限

可是我勾选了Chrome呀……

**Comment by kooritea** [comment]
emm 这就难办了，已经想不到其他可能了

**Comment by ayanamist** [comment]
> emm 这就难办了，已经想不到其他可能了

这个问题解决了，我取消后重新勾选一下就好了。

https://github.com/kooritea/fcmfix/blob/379814c79051c89a9141c96932ef5d234a86fcfd/app/src/main/java/com/kooritea/fcmfix/xposed/ReconnectManagerFix.java#L147 这个地方，Timer实例会启动一个线程，但好像不会自己释放，会导致线程越来越多的，最好调用一下cancel方法释放一下

**Comment by lsjiaowo** [comment]
问下哈，是fixfcm不勾选目标应用，然后再次勾选，重启手机就可以解决了吗？
