### ISSUE TITLE
fcmfix在MIUI14(Android13)上使用，为什么阻止应用停止时自动清除通知的功能失去作用？

### ISSUE THREAD

**Issue by Kuailedeqingnian** [kooritea/fcmfix#151]
fcmfix在MIUI14(Android13)上使用时，阻止应用停止时自动清除通知的功能失去了作用，也就是在应用程序关闭后，通知栏里面的消息也被自动清除了。希望下一个版本可以修复这个bug。

![Screenshot_2024-06-09-00-00-58-194_com.kooritea.fcmfix.jpg](https://github.com/kooritea/fcmfix/assets/172131911/1ee69f40-2d27-416c-84c7-c1ae6c67e087)

**Comment by kooritea** [comment]
用的最新版的吗？之前应该已经修过这个问题了，不行的话发个日志和services.jar看看

**Comment by kooritea** [comment]
日志在lsposed下方右手边第二个，右上角可以保存。
services.jar在/system/framework目录，顺便把framework.jar也发了吧

**Comment by Kuailedeqingnian** [comment]
> 日志在lsposed下方右手边第二个，右上角可以保存。
> services.jar在/system/framework目录，顺便把framework.jar也发了吧

好的，我先把fcmfix更新到最新版，因为使用最新版才能发现问题😂

**Comment by Kuailedeqingnian** [comment]
> 日志在lsposed下方右手边第二个，右上角可以保存。
> services.jar在/system/framework目录，顺便把framework.jar也发了![LSPosed_2024-06-12T22_21_20.867388.zip](https://github.com/user-attachments/files/15806608/LSPosed_2024-06-12T22_21_20.867388.zip)

**Comment by Kuailedeqingnian** [comment]
> > 日志在lsposed下方右手边第二个，右上角可以保存。
> > services.jar在/system/framework目录，顺便把framework.jar也发了![LSPosed_2024-06-12T22_21_20.867388.zip](https://github.com/user-attachments/files/15806608/LSPosed_2024-06-12T22_21_20.867388.zip)
> 

![services.zip](https://github.com/user-attachments/files/15806660/services.zip)

**Comment by Kuailedeqingnian** [comment]
> 日志在lsposed下方右手边第二个，右上角可以保存。
> services.jar在/system/framework目录，顺便把framework.jar也发了吧

你看一下，我发送了日志和Service.jar，都是zip压缩包😂

**Comment by Kuailedeqingnian** [comment]
> 日志在lsposed下方右手边第二个，右上角可以保存。
> services.jar在/system/framework目录，顺便把framework.jar也发了吧

![framework.zip](https://github.com/user-attachments/files/15806857/framework.zip)

**Comment by Kuailedeqingnian** [comment]
> 日志在lsposed下方右手边第二个，右上角可以保存。
> services.jar在/system/framework目录，顺便把framework.jar也发了吧

您好！我发送了三个zip压缩包，你查看一下😂😊

**Comment by kooritea** [comment]
https://github.com/kooritea/fcmfix/releases/tag/42-20240613_71ee631
试试这个

**Comment by Kuailedeqingnian** [comment]
> https://github.com/kooritea/fcmfix/releases/tag/42-20240613_71ee631
> 试试这个

好的，谢谢！

**Comment by Kuailedeqingnian** [comment]
> https://github.com/kooritea/fcmfix/releases/tag/42-20240613_71ee631
> 试试这个

我测试了，这个版本的阻止应用停止自动清除通知的功能在MIUI14（Android13）上重新生效了😂😘
