### ISSUE TITLE
gms需要勾选吗？

### ISSUE THREAD

**Issue by Lovefish** [kooritea/fcmfix#156]
我看到别人说要在插件页面勾选gms，但是插件并没有把gms作为推荐勾选的应用。
而且我只勾选了电量与性能，还有系统框架这两个，就能够正常推送了

**Comment by kooritea** [comment]
不用，勾gms没什么实际作用

**Comment by Lovefish** [comment]
> 不用，勾gms没什么实际作用，gms推荐应用是我后来去掉的

好的谢谢
