### ISSUE TITLE
我发现最近如果不点开fcm诊断，fcm就没有连接。

### ISSUE THREAD

**Issue by Lovefish** [kooritea/fcmfix#164]
点开的瞬间才连接上的。。。

**Comment by Lovefish** [comment]
就很奇怪，不点的话，重启手机之后很长一段时间他都没有主动去连接，就是要点开fcm诊断，等一段时间它才会去连接

**Comment by Lovefish** [comment]
@kooritea 我尝试着切换不同的网络设置，都会出现这个问题。开机或重启手机只要不点f cm诊断，它就不会连接。只要点开诊断等个几秒钟就自动连上

**Comment by kooritea** [comment]
可能是gms服务被省电/墓碑了吧，只能自己找对应的系统对应的解决方法了

**Comment by Lovefish** [comment]
> 可能是gms服务被省电/墓碑了吧，只能自己找对应的系统对应的解决方法了

但就很奇怪啊，最近也没有去专门设置什么。
印象中就清空了一次play store数据

**Comment by Lovefish** [comment]
> 可能是gms服务被省电/墓碑了吧，只能自己找对应的系统对应的解决方法了

![Screenshot_2024-10-12-23-02-09-014_com android settings](https://github.com/user-attachments/assets/e88b2cf3-7d60-4720-8c35-eedc8e15a94a)

我就看了一下，这默认就是没有优化的啊

**Comment by Lovefish** [comment]
清空电量与性能的数据之后修复

**Comment by Lovefish** [comment]
> 可能是gms服务被省电/墓碑了吧，只能自己找对应的系统对应的解决方法了

抱歉，找到原因了，不久之前disable了一个gms的组件。。。
现在正常了
