### ISSUE TITLE
WiFi下即使fcm已连接也收不到推送

### ISSUE THREAD

**Issue by lsjiaowo** [kooritea/fcmfix#17]
作者好！又来打扰了，反馈一下：
1. WiFi连接时，前20分钟还能收到推送，但超过20分钟后，即使Connected，也收不到推送。但是用流量连接就可以一直收到推送。很奇怪
2. 最近也经常断连，锁屏状态下基本都断连了（已关闭睡眠模式。设置->电池->右上角->场景配置->睡眠模式）
3. 用Clash的Host绑定IP也没办法一直连接。之前是可以保持几乎24小时连接的（看到前面几个issue也反馈这点）

附上日志

![Screenshot_2021-08-04-11-09-23-882_com.google.android.gms.jpg](https://user-images.githubusercontent.com/49240966/128280781-22c3b9e5-572d-457c-a351-9a4796743c5a.jpg)
![IMG_20210804_111237.jpg](https://user-images.githubusercontent.com/49240966/128280822-bf410300-5ccd-485f-81bc-2225a3ec2254.jpg)
![IMG_20210804_111257.jpg](https://user-images.githubusercontent.com/49240966/128280834-e6784475-b04d-49f5-a285-2d93646eaefc.jpg)

**Comment by kooritea** [comment]
锁屏收不到很可能miui的问题，我这里是eu版+本地化的权限管理器没问题，可能国内版的还有其他什么机制

**Comment by lsjiaowo** [comment]
不知道MIUI又改了什么，之前12.5.3版还是可以保持十几个小时的连接的，现在升到最新12.5.5就不行了

**Comment by lsjiaowo** [comment]
WiFi连接超过20分钟就收不到推送了，不锁屏也这样，MIUI真的醉了

**Comment by kooritea** [comment]
设置一下心跳时间试试？

**Comment by lsjiaowo** [comment]
已经设置了。无论是设置为0，还是设置成117000，都测试了，即使Connected，也没有推送，好奇怪

**Comment by kooritea** [comment]
设置成117000有没有看到发送心跳的日志

**Comment by lsjiaowo** [comment]
额，发送心跳的日志是指哪个，我不太懂。。
附上截图
![Screenshot_2021-08-06-11-45-09-759_com.google.android.gms.jpg](https://user-images.githubusercontent.com/49240966/128453033-6d9ae63a-4b8a-46bc-a8fc-bed38dd3f0ce.jpg)

**Comment by kooritea** [comment]
![Screenshot_20210806121110.png](https://user-images.githubusercontent.com/28976621/128454820-1c5f2f3d-d50c-4d1c-bd5e-993b7b8603a9.png)
这个倒计时结束之后fcm日志的界面应该会出现新的日志

**Comment by lsjiaowo** [comment]
![Screenshot_2021-08-06-12-14-36-129_com.google.android.gms.jpg](https://user-images.githubusercontent.com/49240966/128455139-3ba69662-27d6-4dba-bae2-e6a4737b47f2.jpg)

出现负数了😂

**Comment by kooritea** [comment]
看来国内miui还是不行

**Comment by lsjiaowo** [comment]
555.....无解了吗Orz

**Comment by lsjiaowo** [comment]
大佬，看到酷安上有位酷友在你的fcmfix基础上更新了。增加了对com.miui.powerkeeper（电量和性能）的启用控制。可以围观一下，目前我正在用，看看什么效果 :)
传送门：https://blog.minamigo.moe/archives/747

**Comment by kooritea** [comment]
因为看起来没有公布源码所以反编译稍微看了一下…
增加了修改任务管理器的行为允许应用驻留后台和在国内版自动允许通过fcm自启动以及删除了powerkeeper的两个方法。

驻留后台这里是不需要的，因为这个模块本身就是为了让没有驻留后台的应用也能接收fcm，至于powerkeeper的地方这边没法测试能不能解决国内版锁屏收不到fcm的问题，因为我手上没国内版rom的机器…

**Comment by Andywei110** [comment]
我也是遇到同样的问题！

**Comment by Andywei110** [comment]
fcm连着，有时候就是不通知，锁屏也是不通知！

**Comment by 17998384** [comment]
我也是同样的情况，fcm连着就是不通知，系统ColorOS12

**Comment by jayjayzhang** [comment]
怎么解决的，锁屏后收不到推送，但是fcmtoolbox 锁屏是可以正常收到
