### ISSUE TITLE
锁屏后必定会断开连接

### ISSUE THREAD

**Issue by oswaldxdd** [kooritea/fcmfix#18]
不知为什么肯定会断

**Comment by oswaldxdd** [comment]
![Uploading Screenshot_2021-08-11-08-50-45-776_com.google.android.gms.jpg…]()

**Comment by oswaldxdd** [comment]
![06AEC0B1E7269D341AF617E4DE6D2BDF](https://user-images.githubusercontent.com/19682134/128954402-7b791953-e449-40dd-9f68-f5e45f781399.jpg)

**Comment by kooritea** [comment]
https://github.com/ayanamist/miui-powerkeeper-hack

国内版可能还需要这个

**Comment by Rakau** [comment]
![IMG_20210924_083338](https://user-images.githubusercontent.com/33389179/134601144-44a70ebb-e51b-472b-a0ae-5b21c4a525c7.jpg)
没你们说的问题
