### ISSUE TITLE
google相册无法推送

### ISSUE THREAD

**Issue by gu970214** [kooritea/fcmfix#19]
![Screenshot_2021-08-12-14-56-42-909_com google android gms](https://user-images.githubusercontent.com/40325591/129200548-7967a86f-346d-49e2-ae17-39ea8f7b276b.jpg)
提示No response to broadcast
在fcmfix中已经勾选谷歌相册
fcmfix版本0.3.3
非常感谢开发者

**Comment by kooritea** [comment]
有没有给自启动权限

**Comment by gu970214** [comment]
给了的，电源管理也是无限制

**Comment by gu970214** [comment]
> 有没有给自启动权限

给了的，电源管理也是无限制

**Comment by ruanidiot** [comment]
@gu970214 請問後來有找到解決的方法嗎？
