### ISSUE TITLE
修改后google play屡次停止服务

### ISSUE THREAD

**Issue by Feiyuyu0503** [kooritea/fcmfix#2]
Redmi K30S MIUI12.5 21.2.3 Android11
edxposed v0.5.2.1 (YAHFA)
多次检查配置文件，感觉修改没啥问题，改完重启，google play屡次停止服务，FCM Diagnostics变为No service
应该是和那个closed issue差不多的问题。。如果大佬没时间处理的话就close吧，打扰啦😅

**Comment by kooritea** [comment]
我还没升安卓11，抱歉

**Comment by kooritea** [comment]
我这边已经升级到安卓11，这个gms按那个方法修改是没有问题可以正常工作的
应该是我markdown里描述不清楚你改错了。。。

你可以把你改的配置文件和你那个版本的gms.apk发给我看看是哪里描述出了差错

**Comment by Feiyuyu0503** [comment]
感谢！刚尝试了一下新的release，配置了一下，google play正常服务，但没记错的话我之前的配置文件应该也按照这样改的。
我现在的环境是 K30S MIUI12.5 21.4.14 Android11
LSPosed v1.3.5 模块作用域勾选了com.google.android.gms和目标app

以下是我更改完后，未重启前的配置文件
`<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="heartbeatInterval" value="117000" />
    <string name="timer_intent_property">d</string>
    <string name="timer_next_time_property">f</string>
    <boolean name="enable" value="true" />
    <string name="timer_settimeout_method">c</string>
    <string name="timer_class">achz</string>
    <string name="gms_version">21.15.15 (150400-371058782)</string>
    <boolean name="isInit" value="true" />
</map>`
然后重启完成，google play正常，这次没停止服务，打开FCM diagnostics中是这样显示的
05-07 15:38:18.634 net=0: Connected 
05-07 15:38:20.788 net=0:[fcmfix] User Device Unlock Broadcast 
05-07 15:38:20.788 net=0:[fcmfix] ReconnectManagerFix 配置已关闭 
05-07 15:38:20.810 net=0:[fcmfix] ReconnectManagerFixStartHook 完成 
05-07 15:38:31.583 net=0: Close err:30 time:12 
05-07 15:38:33.019 net=0: Connected 
05-07 15:38:37.347 net=0: Close err:20 time:4 
05-07 15:38:56.218 net=0: Connected 05-07 15:38:56.259 net=0: Received com.google.android.googlequicksearchbox 0:1620373118934992%8b460216f9fd7ecd 05-07 15:38:57.929 net=0: Successful broadcast to com.google.android.googlequicksearchbox (id=0:1620373118934992%8b460216f9fd7ecd time=1658ms priority=NORMAL)

然后再去看配置文件发现 enable修改为false了。
然后去LSPosed中模块管理，虽然作用域勾选了com.google.android.gms和目标app，但是fcmfix自己的模块设置页面只有一个com.android.vending（谷歌play商店）可以勾选。
目前我还不知道有没有效果，不过还是很感谢！

**Comment by kooritea** [comment]
fcm唤醒应用的功能需要在lsposed勾选安卓系统，不需要勾选目标app
fcmfix里只有一个应用可能是你没有给它读取应用列表权限
enable被修改为false是因为获取到的gms版本和配置文件里不一样，你手动再改为true应该就不会再被改为flase了

**Comment by Feiyuyu0503** [comment]
> 感谢！刚尝试了一下新的release，配置了一下，google play正常服务，但没记错的话我之前的配置文件应该也按照这样改的。
> 我现在的环境是 K30S MIUI12.5 21.4.14 Android11
> LSPosed v1.3.5 模块作用域勾选了com.google.android.gms和目标app
> 
> 以下是我更改完后，未重启前的配置文件
> 
> ```
> <?xml version='1.0' encoding='utf-8' standalone='yes' ?>
> <map>
>     <long name="heartbeatInterval" value="117000" />
>     <string name="timer_intent_property">d</string>
>     <string name="timer_next_time_property">f</string>
>     <boolean name="enable" value="true" />
>     <string name="timer_settimeout_method">c</string>
>     <string name="timer_class">achz</string>
>     <string name="gms_version">21.15.15 (150400-371058782)</string>
>     <boolean name="isInit" value="true" />
> </map>
> ```
> 
> 然后重启完成，google play正常，这次没停止服务，打开FCM diagnostics中是这样显示的
> 05-07 15:38:18.634 net=0: Connected
> 05-07 15:38:20.788 net=0:[fcmfix] User Device Unlock Broadcast
> 05-07 15:38:20.788 net=0:[fcmfix] ReconnectManagerFix 配置已关闭
> 05-07 15:38:20.810 net=0:[fcmfix] ReconnectManagerFixStartHook 完成
> 05-07 15:38:31.583 net=0: Close err:30 time:12
> 05-07 15:38:33.019 net=0: Connected
> 05-07 15:38:37.347 net=0: Close err:20 time:4
> 05-07 15:38:56.218 net=0: Connected 05-07 15:38:56.259 net=0: Received com.google.android.googlequicksearchbox 0:1620373118934992%8b460216f9fd7ecd 05-07 15:38:57.929 net=0: Successful broadcast to com.google.android.googlequicksearchbox (id=0:1620373118934992%8b460216f9fd7ecd time=1658ms priority=NORMAL)
> 
> 然后再去看配置文件发现 enable修改为false了。
> 然后去LSPosed中模块管理，虽然作用域勾选了com.google.android.gms和目标app，但是fcmfix自己的模块设置页面只有一个com.android.vending（谷歌play商店）可以勾选。
> 目前我还不知道有没有效果，不过还是很感谢！

看起来还是存在一点问题，我在打开play 商店更新应用时，观察过FCM diagnostics，出现过fcmfix allow com.google.android.gms的内容。但是刚刚又发现，重连服务还是出现了负数问题。
文件大于10M传不上来，发个我用的gms的apk链接吧 [my.sharepoint.cn](https://seunic-my.sharepoint.cn/:u:/g/personal/213170721_seu_edu_cn/EcDWJvkqAo1Jiv-S-jzQ9p0BLtAYtXT0s6AwYs-AjAYhag?e=VbUG8q)
麻烦您看一下。

**Comment by Feiyuyu0503** [comment]
> fcm唤醒应用的功能需要在lsposed勾选安卓系统，不需要勾选目标app
> fcmfix里只有一个应用可能是你没有给它读取应用列表权限
> enable被修改为false是因为获取到的gms版本和配置文件里不一样，你手动再改为true应该就不会再被改为false了

谢谢回复！
我尝试过勾选安卓系统，当时觉得勾不勾没什么变化，就又取消勾选了，于是过了一段时间后才发现的重连负数问题，暂时不知道如果勾选了安卓系统会不会有负数问题。
另外读取应用列表的权限我后来重新去给了，然后也清除了fixfcm的应用数据，打开依然只有com.google.android.gms一个应用。
我不太懂您说的手动改为true的意思，是说每次重启后都再去手动改为true就可以了吗？我现在依然是每次重启后变为false。

**Comment by kooritea** [comment]
日志中有出现这个吗
> [fcmfix] ReconnectManagerFix 配置已关闭

这个表示配置文件里的enable没打开

**Comment by Feiyuyu0503** [comment]
> 日志中有出现这个吗
> 
> > [fcmfix] ReconnectManagerFix 配置已关闭
> 
> 这个表示配置文件里的enable没打开

我在重启前都是修改enable为true，然后重启之后，日志中出现了 [fcmfix] ReconnectManagerFix 配置已关闭，配置文件也确实enable为false。

**Comment by kooritea** [comment]
> > fcm唤醒应用的功能需要在lsposed勾选安卓系统，不需要勾选目标app
> > fcmfix里只有一个应用可能是你没有给它读取应用列表权限
> > enable被修改为false是因为获取到的gms版本和配置文件里不一样，你手动再改为true应该就不会再被改为false了
> 
> 谢谢回复！
> 我尝试过勾选安卓系统，当时觉得勾不勾没什么变化，就又取消勾选了，于是过了一段时间后才发现的重连负数问题，暂时不知道如果勾选了安卓系统会不会有负数问题。
> 另外读取应用列表的权限我后来重新去给了，然后也清除了fixfcm的应用数据，打开依然只有com.google.android.gms一个应用。
> 我不太懂您说的手动改为true的意思，是说每次重启后都再去手动改为true就可以了吗？我现在依然是每次重启后变为false。

正常来说只会在获取到gms版本和配置文件里写的不一样enable才会自动变为false。
只有配置文件正确打开并读取才能修复重连时间为负数的问题。

你用的是国内版的miui或者什么权限管理软件吗，在应用权限里应该有一个「读取应用列表」的权限，需要打开

勾选安卓系统的是为了让fcm唤醒force stop的应用然后发送通知

**Comment by Feiyuyu0503** [comment]
> > > fcm唤醒应用的功能需要在lsposed勾选安卓系统，不需要勾选目标app
> > > fcmfix里只有一个应用可能是你没有给它读取应用列表权限
> > > enable被修改为false是因为获取到的gms版本和配置文件里不一样，你手动再改为true应该就不会再被改为false了
> > 
> > 
> > 谢谢回复！
> > 我尝试过勾选安卓系统，当时觉得勾不勾没什么变化，就又取消勾选了，于是过了一段时间后才发现的重连负数问题，暂时不知道如果勾选了安卓系统会不会有负数问题。
> > 另外读取应用列表的权限我后来重新去给了，然后也清除了fixfcm的应用数据，打开依然只有com.google.android.gms一个应用。
> > 我不太懂您说的手动改为true的意思，是说每次重启后都再去手动改为true就可以了吗？我现在依然是每次重启后变为false。
> 
> 正常来说只会在获取到gms版本和配置文件里写的不一样enable才会自动变为false。
> 只有配置文件正确打开并读取才能修复重连时间为负数的问题。
> 
> 你用的是国内版的miui或者什么权限管理软件吗，在应用权限里应该有一个「读取应用列表」的权限，需要打开
> 
> 勾选安卓系统的是为了让fcm唤醒force stop的应用然后发送通知
我现在都是在Lsposed勾选了安卓系统的情况下。
我另外安装有Vanced microG，它的包名是com.mgoogle.android.gms，不知是否和它有关。
我安装有Thanox Pro，它可以权限管理，但是我没有启用，我现在的权限管理使用的就是miui自己的。
我在看play服务的包名的时候，看到应用版本号为21.15.15 (150400-371058782)，也是与配置文件一致的。

**Comment by kooritea** [comment]
emmm 
vanced不影响
thanox没用过不清楚读不了应用列表是不是他的问题

重启之后自动变为false的问题可能是获取不到gms的版本，要明天打个多一点日志的包排查

**Comment by Feiyuyu0503** [comment]
> emmm
> vanced不影响
> thanox没用过不清楚读不了应用列表是不是他的问题
> 
> 重启之后自动变为false的问题可能是获取不到gms的版本，要明天打个多一点日志的包排查

非常感谢！
感觉和thanox没关系，因为我根本没启用它的这个功能。

**Comment by Feiyuyu0503** [comment]
更新！我现在重启之后可以读取并启用配置了 日志如下
```
05-07 19:15:20.593 net=0: Connected 
05-07 19:15:37.275 net=0:[fcmfix] User Device Unlock Broadcast 
05-07 19:15:37.275 net=0:[fcmfix] ReconnectManagerFix 读取配置已成功,timer_class: achz 
05-07 19:15:37.275 net=0:[fcmfix] ReconnectManagerFixStartHook 完成 
05-07 19:15:52.450 net=0: Close err:30 time:31 
05-07 19:15:57.980 net=0:[fcmfix] Send broadcast GCM_RECONNECT 
05-07 19:15:58.994 net=0: Failed connection err:16 
05-07 19:16:28.021 net=0:[fcmfix] Send broadcast GCM_RECONNECT 
05-07 19:16:59.373 net=0: Failed connection err:24 
05-07 19:17:10.485 net=0: Connected
```
过程令我有些匪夷所思。

~~其实我是本来就不担心FCM不会再主动重连的，因为我在play商店找到了一个应用“推送通知助手”，它会在每个时间间隔后广播GCM心跳以保持连接，所以我之前就是不存在再也不会主动重连的问题的。但是后来启用fcmfix模块后，我就把这个应用关闭了，此为前提。
我关闭thanox模块后，重启，看fcm日志依然有 [fcmfix] ReconnectManagerFix 配置已关闭。
然后为了方便编辑配置文件，我换了一个叫做FX的文件管理器，因为它可以把特定文件夹固定到FX首页，于是我用这个管理器的编辑器保存好enable为true后，重启，发现fcmfix的配置居然读取成功了。
于是我又开启thanox模块，再重启，fcmfix的配置依然读取成功。
总之，这个过程涉及到的app应该包括有:两个文件管理器"FX"和"MT"，thanox，推送通知助手。~~

在有了上述删除线中的内容后，我又尝试了几次，基本可以排除thanox和推送通知助手的关系，我现在都是以它们两个开启的情况下讨论，~~在重启前，配置文件的enable都是true(这点存疑了，不过不太重要)~~。
1.使用mt编辑配置文件的timer_intent_property为别的错误的值，保存，无论用mt或是fx再打开查看，都确实是保存过的错误的值，然后再重启手机，再查看配置文件，发现居然是之前正确的值，同时fcm日志中看到配置文件启用了。
2.使用fx编辑配置文件的timer_intent_property为别的错误的值，保存，查看也是错的值，重启手机，再查看配置，错误的值保留了，enable改为了false（~~不知是自动改为false，还是重启前配置文件就是false，因为我后来明确enable为true时，改timer_intent_property为错误的值，再重启，fcm日志显示配置文件正常启用，enable也是true而没有自动改为false~~），fcm日志中也反映出了 [fcmfix] ReconnectManagerFix 配置已关闭。用fx修改为正确的配置，重启手机，fcm日志中显示配置文件正常启用了。

因此总结来说就是我使用mt管理器修改enable为true时，虽然我再三查看都是正常保存了，但重启后就是显示enable为false（包括其他配置项的更改重启后也都恢复成了修改前的），而使用fx文件管理器编辑，则正常。
我最开始使用的未充钱版且进行了存储重定向的mt管理器，不对mt进行存储重定向后，问题依旧。
有一点细节是，其他配置项如timer_intent_property那些填字母的，**首次配置**它们时，都是我通过mt编辑保存的，配置完后，保存（而这些配置项在我重启了那么多次的自始至终都是存在的），然后我立马想起了enable项还没改为true，于是才**二次编辑**（使用mt）该配置文件中的enable为true，然后就出现了上面几个回复中重启自动修改enable为false的问题。
但我奇怪的是既然其他配置项在首次填写时都是用的mt，且在后来重启多次的情况下，这些配置项也确确实实地保留着而不是空着，而后我使用mt编辑其他任意属性，重启后都恢复为修改前的内容，那么是否意味着必须在首次配置时全部正确填写（包括enable改为true）？但是否决这个想法的证据也有，就是我用fx编辑配置文件（显然不是首次配置）再重启后配置都是保留为修改后的。

***
由于实在太奇怪了，我还是卸载了fcmfix，删掉了fcm_config.xml，重来一次。首次编辑使用mt一次性配置完所有项目，重启，失败。
但这次我终于发现，使用mt管理器编辑的话，保存后出现了fcm_config.xml.bak这个文件，而重启手机后fcm_config.xml的内容被覆盖为fcm_config.xml.bak的内容且fcm_config.xml.bak消失。而使用fx管理器编辑，则不会出现.bak文件，所以是成功的。另外使用mt管理器编辑，把生成的.bak删除，再重启，就也是成功的情况了。

算是破案了，不太懂这里面的技术，所以很抱歉只能把尝试过程描述出来。
感谢作者！总之配置文件是成功启用了，但是fcmfix里可勾选的应用依然还是只有com.android.vending（谷歌play商店)，我现在确实存在即使在fcm日志里看到successful broadcast也无通知的问题(app已开自启甚至已有缓存的情况)，包括看到某社区也有反映此问题，我看您此次更新似乎解决了这个问题，感激！

**Comment by kooritea** [comment]
fcmfix勾选应用的配置保存在/data/data/com.kooritea.fcmfix/shared_prefs/config.xml

你可以先勾选那个play商店，然后编辑那个配置文件仿照里面的格式添加想要唤醒推送的包名就好了

**Comment by kooritea** [comment]
找到不能读取应用列表的原因了
因为改成了api30读取列表要声明权限
更新到0.1.2就好了

**Comment by Feiyuyu0503** [comment]
> 找到不能读取应用列表的原因了
> 因为改成了api30读取列表要声明权限
> 更新到0.1.2就好了

感谢！新版已经可以读取应用列表了。
昨天0.1.1版手动添加allowlist后就确实成功唤醒app了，但是现在有个非常严重的问题，我也是体验了一段时间后，重启非常多次才敢猜测的结论，无论是0.1.1还是0.1.2，当我勾选系统框架(也就是安卓系统)后，会频率非常高的系统界面无响应，只能长按关机键重启手机，甚至可以说正常使用五分钟内必卡死界面。。但是不勾选系统框架的话，就没这问题了，可是也唤醒不了应用了。。。

**Comment by kooritea** [comment]
emmm
我手机也会开机一两分钟之后出现卡住的情况，只是我一般是30秒左右就恢复了而且之后都不会再有这种情况，还以为是xp的问题。
我先试试看是不是这个模块的问题

**Comment by kooritea** [comment]
关了模块之后好像真的不会卡住了😥
我去排查一下是什么问题

**Comment by Feiyuyu0503** [comment]
为了方便触发模块效果，我是在模块里勾选了telegram，对几个群组开启了通知，然后就明显感到，在勾选了系统框架的情况下，tg通知越频繁，越容易导致系统界面卡住，当然tg不频繁通知的话，也很容易导致系统界面卡住。而不勾选系统框架的话，让tg保留在后台，即使它频繁通知，也没有卡住界面的情况出现。

**Comment by kooritea** [comment]
应该是因为每次有通知都去读取配置造成了阻塞，需要优化一下实现方式

**Comment by kooritea** [comment]
0.2.0这个我手机上不会再卡住不动了，你看看你还会不会卡住(捂脸)

**Comment by Feiyuyu0503** [comment]
> 0.2.0这个我手机上不会再卡住不动了，你看看你还会不会卡住(捂脸)

感谢作者！没再卡住了！fcm活了！
