### ISSUE TITLE
MIUI 12.5 21.8.23 已经修复了这个问题

### ISSUE THREAD

**Issue by drakeet** [kooritea/fcmfix#22]
如题，可以更新到这个系统版本试试，需要申请加入开发内测版。

**Comment by drakeet** [comment]
或许这个模块并不是专门针对 MIUI 的...

**Comment by kooritea** [comment]
这个其实不是问题，不太可能被miui修复，
名字起得不是很好所以有歧义了哈哈。

fcmfix是扩展fcm的功能的，本身fcm的设计是需要应用在后台驻留才能响应并且发送通知，这个模块的目的是让没有留在后台的应用也能顺利收到fcm
