### ISSUE TITLE
0.4的问题

### ISSUE THREAD

**Issue by Rakau** [kooritea/fcmfix#23]
现在自启不开可以推送了，但是需要到APP里打开开关才能推送，能否默认开启所有APP，或者给一个搜索功能？一个一个开很难找

**Comment by kooritea** [comment]
默认全部开启不是一个好的选择，像知乎这种会用fcm推送广告的。
事实上现在检测到支持fcm的应用都是默认排在列表上面的，如果前面找不到的话估计都是不支持fcm了。
搜索的话我不是很懂安卓开发所以比较难做哈哈

**Comment by Rakau** [comment]
好的谢谢

kooritea ***@***.***> 于 2021年8月30日周一 14:43写道：
