### ISSUE TITLE
通过修改hosts让国内裸连，WIFI正常，切数据就会断开一直连不上

### ISSUE THREAD

**Issue by wfniub** [kooritea/fcmfix#25]
大佬，因为怕dns解析出来的mtalk无法连接，所以手动修改了hosts，全部弄了有用的节点，也全部测试都是通的，可是wifi可以连接，切换数据就挂了，感觉跟长时间不自动连接一样，下面是日志，麻烦大佬看看是哪里的问题
![image](https://user-images.githubusercontent.com/59757806/132812823-dad2c160-9adf-46fb-8670-d9619d780ac9.png)
![a6978f0273d06fcce2ddd77701fbab5](https://user-images.githubusercontent.com/59757806/132812858-fb3e9b9f-3597-4532-81d5-ba1d8f746c7d.jpg)
![2b15152a2ad84edf18d10b196a81d7b](https://user-images.githubusercontent.com/59757806/132812877-914792c1-8383-4bd6-9624-7498affb065a.jpg)

**Comment by Andywei110** [comment]
另外我把网断开再开启，他也不会重新连接，一直保持这个状态，时间还一直在增加
![349f0546ddfd281d5c66ee9b6a9b658](https://user-images.githubusercontent.com/59757806/132813810-1c91b121-b254-4b96-802c-a68a4f4bfcd0.jpg)

**Comment by kooritea** [comment]
同样的机器不同网络的表现不同那多半是网络的问题，不同运营商连通性有差异也很正常。

通过改host来连接fcm其实没什么意义，只有一些国内本身能用且接入了fcm的应用才有用，这样的应用少之又少

**Comment by Andywei110** [comment]
> 同样的机器不同网络的表现不同那多半是网络的问题，不同运营商连通性有差异也很正常。
> 
> 通过改host来连接fcm其实没什么意义，只有一些国内本身能用且接入了fcm的应用才有用，这样的应用少之又少

不是呢大佬，你能看下日志分析吗，我感觉好像他一直不连接一样，而不是连不上，时间一直继续，我断开网络，他都依旧不会从0开始继续连接！裸连是为了只收消息提醒呢，例如tg！

**Comment by kooritea** [comment]
日志里Send broadcast GCM_RECONNECT的时候就是在重连了，只不过没连上

**Comment by Andywei110** [comment]
> 日志里Send broadcast GCM_RECONNECT的时候就是在重连了，只不过没连上

老哥，息屏fcm并没有断开，正常连接，但是息屏不消息提醒是怎么回事！

**Comment by kooritea** [comment]
什么应用，有没有挂代理，有挂代理但是收不到的话去用readme里那个国内版专用的

**Comment by Andywei110** [comment]
> 什么应用，有没有挂代理，有挂代理但是收不到的话去用readme里那个国内版专用的

挂了代理，而且查看代理没有断开，屏幕一按亮立马就来消息，tg电报，个别时候又正常！

**Comment by kooritea** [comment]
那大概是miui的省电策略问题吧，只能用那个国内版试试了

**Comment by Andywei110** [comment]
> 那大概是miui的省电策略问题吧，只能用那个国内版试试了

用他那个也不行，郁闷，不知为啥有时候又正常，
![1B218671](https://user-images.githubusercontent.com/59757806/133085957-3dc41bf6-8eb1-4e34-8fe2-2d8b4bc15c88.png)

**Comment by Rakau** [comment]
![IMG_20210924_083338](https://user-images.githubusercontent.com/33389179/134601144-44a70ebb-e51b-472b-a0ae-5b21c4a525c7.jpg)
没你们说的问题

**Comment by Andywei110** [comment]
你是啥手机啥系统呀老哥！

**Comment by Rakau** [comment]
MIUI12.5

wfniux ***@***.***> 于 2021年9月24日周五 09:53写道：

**Comment by Andywei110** [comment]
开发板还是稳定版，国内的版本吧！

**Comment by Rakau** [comment]
开发版21.5.28 国内版

wfniux ***@***.***> 于 2021年9月24日周五 09:55写道：

**Comment by Andywei110** [comment]
需要做什么特殊的设置吗老哥，例如云控设置俄罗斯？或者其他有什么需要注意的吗老哥？

**Comment by Rakau** [comment]
什么都没操作，就用了模块

wfniux ***@***.***> 于 2021年9月24日周五 09:59写道：

**Comment by Andywei110** [comment]
这真是见鬼了，我这边怎么搞都不行，连得上息屏就不提醒，难道是我稳定版的原因？我要像老哥学习，搞个开发版试试，搞这个搞的脑壳疼！

**Comment by Rakau** [comment]
也许是你的网络环境有问题

wfniux ***@***.***> 于 2021年9月24日周五 10:04写道：

**Comment by necowong** [comment]
考虑安卓13的 doze mode 导致的熄屏 fcm 不提醒问题
