### ISSUE TITLE
小米手机miui国内版总是有问题

### ISSUE THREAD

**Issue by wfniub** [kooritea/fcmfix#26]
小米手机miui国内版总是有这样那样的问题呢，有时候锁屏不收通知，有时候fcm断开一直连不上，也做了代理，大佬能修复这个问题吗，烧高香呀！

**Comment by kooritea** [comment]
https://blog.minamigo.moe/archives/747
用这个试试吧

**Comment by Rakau** [comment]
自身代理问题
