### ISSUE TITLE
心跳间隔变短

### ISSUE THREAD

**Issue by Krito-LiXIng** [kooritea/fcmfix#27]
我把心跳间隔由117s变短为15s，会发生什么不好的事吗？

**Comment by kooritea** [comment]
耗电，问题不大

**Comment by Krito-LiXIng** [comment]
> 耗电，问题不大

![Screenshot_2021-10-02-01-29-44-820_com google android gms](https://user-images.githubusercontent.com/63215647/135662720-3b847be9-afb9-479c-bbb4-2c2bf11e7260.jpg)
大佬这是什么原因？

**Comment by Krito-LiXIng** [comment]
> > 耗电，问题不大
> 
> ![Screenshot_2021-10-02-01-29-44-820_com google android gms](https://user-images.githubusercontent.com/63215647/135662720-3b847be9-afb9-479c-bbb4-2c2bf11e7260.jpg) 大佬这是什么原因？

为啥fcmfix退出？

**Comment by kooritea** [comment]
配置文件的enable项没有改成true

**Comment by Krito-LiXIng** [comment]
> 配置文件的启用项没有改成真，或者自动寻找钩子点失败了

大佬说下怎么改成真，我去试试

**Comment by kooritea** [comment]
如果你没有改过的话那就是自动找hook点失败了…
删除/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml。然后重启，再把这个fcm日志截图我看看

**Comment by Krito-LiXIng** [comment]
好的，感谢，我去试试

**Comment by Krito-LiXIng** [comment]
> 如果你没有改过的话那就是自动找钩点失败了…… 删除/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml。然后重启，再把这个fcm日志截图我看看

好的。感谢，我去试试

**Comment by Krito-LiXIng** [comment]
> 如果你没有改过的话那就是自动找钩点失败了…… 删除/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml。然后重启，再把这个fcm日志截图我看看

![Screenshot_2021-10-02-01-52-46-056_com google android gms](https://user-images.githubusercontent.com/63215647/135665503-a77890ae-2e07-488d-8c08-fe30e7aa15e3.jpg)
![Screenshot_2021-10-02-01-52-48-008_com google android gms](https://user-images.githubusercontent.com/63215647/135665515-18854a7a-84aa-47f0-a1ca-99b7de185294.jpg)
还是这样。

**Comment by kooritea** [comment]
看来是找不到，能把你的gms包发一下吗，在/data/app/随机字符串/com.google.android.gms-随机字符串/base.apk

**Comment by kooritea** [comment]
和图片一样的…选文件就行

**Comment by Krito-LiXIng** [comment]
> 和图片一样的…选文件就行

![image](https://user-images.githubusercontent.com/63215647/135669147-e1e749f6-c6c9-42f7-ab5a-426c00009a3e.png)
大佬，这个啥，github确实不支持APK文件，我没办法，只能上传到onedrive上了，麻烦大佬下载下。https://1drv.ms/u/s!AtkUEnRDTC3HhVnwtZYnz9k2kMz2?e=K5r0GR

**Comment by kooritea** [comment]
压缩成zip就好了…
已经下了，有空看一下

**Comment by Krito-LiXIng** [comment]
> 压缩成zip就好了…… 已经开始了，有空看一下

好的，是我傻逼了，那就麻烦大佬费时间看了。拜托了

**Comment by Krito-LiXIng** [comment]
> 压缩成zip就好了…… 已经开始了，有空看一下

好吧，是我傻逼了，那就麻烦大佬费时间了。拜托了

**Comment by kooritea** [comment]
0.4.2已修复

**Comment by Krito-LiXIng** [comment]
> 0.4.2已修复

我现在是小米的安卓12。兼容吗？4.1好像不兼容

**Comment by kooritea** [comment]
安卓12不兼容…

**Comment by Krito-LiXIng** [comment]
> 安卓12不兼容…

行吧，我去试试，我刚才装完后不知道是不是因为自启动推特的原因，能收到推特的消息了，但是又出现的新的问题，一直onupdateconfigallowlist size:数字

**Comment by kooritea** [comment]
出现这个日志只是说明你在fcmfix里面勾选或取消勾选了应用而已。
12的情况不是很清楚，不知道谷歌或者miui有没有什么新变化，比如miui不再强杀后台或者谷歌允许fcm唤醒，这样是都能正常收到通知的

**Comment by Krito-LiXIng** [comment]
> 出现这个日志只是说明你在fcmfix里面勾选或取消勾选了应用而已。
> 12的情况不是很清楚，不知道谷歌或者miui有没有什么新变化，比如miui不再强杀后台或者谷歌允许fcm唤醒，这样是都能正常收到通知的

额，行吧。我确定的是miui仍然是强杀后台，这个没变的，用4.1就会被强杀，无法唤醒
