### ISSUE TITLE
显示当前配置文件enable标识为false，FCMFIX退出

### ISSUE THREAD

**Issue by 923133980** [kooritea/fcmfix#28]
想问一下这个有啥问题吗![Screenshot_2021-10-03-17-11-47-074_com.google.android.gms.jpg](https://user-images.githubusercontent.com/44976581/135747414-ddf9acbe-20c7-4866-86ed-52016d037bf0.jpg)

**Comment by kooritea** [comment]
新版本gms自动找hook点失效了，现在自动重连修复和固定心跳间隔的功能不可用

**Comment by 923133980** [comment]
emm想问一下有什么解决办法嘛

**Comment by kooritea** [comment]
等更新

**Comment by 923133980** [comment]
好的辛苦大佬了

**Comment by kooritea** [comment]
0.4.3已更新
