### ISSUE TITLE
无法按照方法自己找hook

### ISSUE THREAD

**Issue by likeman66** [kooritea/fcmfix#32]
gms 版本 21.39.17 (120400-405802548)

按照方法自己找hook，没有叫intent的东西，然后好像所有参数都不太一样。。。
![IMG_20211029_181420](https://user-images.githubusercontent.com/59259075/139417942-1b897fb5-5408-4f21-8648-391391047788.jpg)

**Comment by likeman66** [comment]
> readme里那个现在新版gms不适用了，忘记删掉了。 这个问题只影响固定心跳和修复重连失败的问题。
> 
> 最新的代码虽然适配了新的gms但是只能自己找hook点，所以我还没编译发布，如果你能自己编译的话可以尝试用自己编译的版本然后用下面的配置…
> 
> fcmfix v0.4.2
> 
> ```
> <?xml version='1.0' encoding='utf-8' standalone='yes' ?>
> <map>
>     <long name="heartbeatInterval" value="0" />
>     <boolean name="enable" value="true" />
>     <long name="reconnInterval" value="0" />
>     <string name="timer_alarm_type_property">a.t</string>
>     <string name="timer_settimeout_method">g</string>
>     <long name="gms_version_code" value="213917046" />
>     <string name="timer_class">wrs</string>
>     <string name="gms_version">21.39.17 (150400-405802548)</string>
>     <boolean name="isInit" value="true" />
>     <string name="config_version">v2</string>
> </map>
> ```

![Screenshot_20211030-192730](https://user-images.githubusercontent.com/59259075/139531124-d579e175-a124-43ed-9398-6c9f942531aa.jpg)
大佬,请问这个是什么情况呀，突然一直拉不起来了，我试过降级gms，还是failed to boardcast，之前没问题

**Comment by kooritea** [comment]
给自启动权限试试

**Comment by likeman66** [comment]
> 给自启动权限试试

牛逼大佬！有没有捐赠渠道，白嫖挺不好意思的

**Comment by kooritea** [comment]
不知道你用的是哪个版本的fcmfix，按道理用0.4.1是不需要给自启动权限的（如果在系统给了自启动的话微信会常驻后台）。

**Comment by likeman66** [comment]
> 不知道你用的是哪个版本的fcmfix，按道理用0.4.1是不需要给自启动权限的（如果在系统给了自启动的话微信会常驻后台）。

我是想让微信进缓存，所以thanox里面强行禁止了自启权限，系统自启权限我一直没关。然后我发现thanox里面开了自启一样可以进缓存。主要是我微信换成了外国号码，自动走fcm，但是微信进缓存我怕睡死，就配合fcmfix防止睡死的时候收不到消息

**Comment by StarWishsama** [comment]
可以提供找 hook 点的方法吗？新版本 21.42.18 (190400-410302452) 无效

**Comment by kooritea** [comment]
@StarWishsama 

新版的gms要用最新的代码构建的app才行。
不找hook点只会影响修复重连时间会变成负数和固定心跳间隔的功能，这两个在eu版上不怎么需要，新的找hook点还比较麻烦，所以我都懒得找了。。。

[app-release.zip](https://github.com/kooritea/fcmfix/files/7606763/app-release.zip)

安装之后先强制结束gms让fcmfix生成新的配置文件，配置文件里面应该有个config_version: v2的标识，没有就删掉配置文件重启gms
```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="heartbeatInterval" value="0" />
    <boolean name="enable" value="true" />
    <long name="reconnInterval" value="0" />
    <string name="timer_alarm_type_property">a.t</string>
    <string name="timer_settimeout_method">g</string>
    <long name="gms_version_code" value="214218046" />
    <string name="timer_class">wrs</string>
    <string name="gms_version">21.42.18 (150400-410302452)</string>
    <boolean name="isInit" value="true" />
    <string name="config_version">v2</string>
</map>
```


用jadx-gui 反编译apk
然后搜索代码 `Previous alarms will stay active`
会搜到一个类里的一个方法，这个类名填进`timer_class`项，方法名填进`timer_settimeout_method`
比如这里的就是timer_class=wou, timer_settimeout_method=g
![image](https://user-images.githubusercontent.com/28976621/143536112-5d52cf11-04ec-4b53-93f3-99b9d7f8e728.png)

然后看这个类的构造方法
![image](https://user-images.githubusercontent.com/28976621/143536205-7d6dd34b-b69b-4603-897b-f5f1fbd69e82.png)
找到这个像这个anjz类的(名字会变，位置和构造参数应该不太会变)，这个类实例被赋值到上面wou类的`a`属性上，`a`先记下来，然后找anjz类实例化的第三个参数被赋值到了什么属性上
![image](https://user-images.githubusercontent.com/28976621/143536651-41be2b29-ea35-459c-a89d-7eaa8b88610a.png)
这里可以看到第三个参数被赋值到了anjz的`t`属性上，那么最后timer_alarm_type_property配置项的值就是wou类的`a`属性+anjz的`t`属性 = a.t，所以把`a.t`填到timer_alarm_type_property里。

最后把enable设置为true重启gms就好了

**Comment by StarWishsama** [comment]
> @StarWishsama 
> 
> 新版的gms要用最新的代码构建的app才行。
> 不找hook点只会影响修复重连时间会变成负数和固定心跳间隔的功能，这两个在eu版上不怎么需要，新的找hook点还比较麻烦，所以我都懒得找了。。。
> 
> [app-release.zip](https://github.com/kooritea/fcmfix/files/7606763/app-release.zip)
> 
> 安装之后先强制结束gms让fcmfix生成新的配置文件，配置文件里面应该有个config_version: v2的标识，没有就删掉配置文件重启gms
> ```xml
> <?xml version='1.0' encoding='utf-8' standalone='yes' ?>
> <map>
>     <long name="heartbeatInterval" value="0" />
>     <boolean name="enable" value="true" />
>     <long name="reconnInterval" value="0" />
>     <string name="timer_alarm_type_property">a.t</string>
>     <string name="timer_settimeout_method">g</string>
>     <long name="gms_version_code" value="214218046" />
>     <string name="timer_class">wrs</string>
>     <string name="gms_version">21.42.18 (150400-410302452)</string>
>     <boolean name="isInit" value="true" />
>     <string name="config_version">v2</string>
> </map>
> ```
> 
> 
> 用jadx-gui 反编译apk
> 然后搜索代码 `Previous alarms will stay active`
> 会搜到一个类里的一个方法，这个类名填进`timer_class`项，方法名填进`timer_settimeout_method`
> 比如这里的就是timer_class=wou, timer_settimeout_method=g
> ![image](https://user-images.githubusercontent.com/28976621/143536112-5d52cf11-04ec-4b53-93f3-99b9d7f8e728.png)
> 
> 然后看这个类的构造方法
> ![image](https://user-images.githubusercontent.com/28976621/143536205-7d6dd34b-b69b-4603-897b-f5f1fbd69e82.png)
> 找到这个像这个anjz类的(名字会变，位置和构造参数应该不太会变)，这个类实例被赋值到上面wou类的`a`属性上，`a`先记下来，然后找anjz类实例化的第三个参数被赋值到了什么属性上
> ![image](https://user-images.githubusercontent.com/28976621/143536651-41be2b29-ea35-459c-a89d-7eaa8b88610a.png)
> 这里可以看到第三个参数被赋值到了anjz的`t`属性上，那么最后timer_alarm_type_property配置项的值就是wou类的`a`属性+anjz的`t`属性 = a.t，所以把`a.t`填到timer_alarm_type_property里。
> 
> 最后把enable设置为true重启gms就好了
> 

感谢

**Comment by liyiecho** [comment]
@kooritea 大佬，Google Play 服务 [21.42.18 (190400-410302452)]，用了你上面提供的0.4.2，且根据你上面教程修改了配置文件，但无论app是否开启自启动，都是Failed to broadcast to stopped app

![Screenshot_2021-12-02-13-33-19-128_com google and](https://user-images.githubusercontent.com/5213722/144364284-4ee376fe-db77-4a79-9c6d-1b25fcdd6fe2.png)

**Comment by kooritea** [comment]
@liyiecho 重新在fcmfix勾选试试

**Comment by liyiecho** [comment]
@kooritea 重新勾选后还是一样，除非要走fcm的app在后台才能收到通知

**Comment by kooritea** [comment]
@liyiecho 用什么xposed框架，有没有勾选系统作用域

**Comment by liyiecho** [comment]
@kooritea 用的LSP，默认两个推荐都勾上的

**Comment by kooritea** [comment]
@liyiecho emmm想不到其他可能了
看看lsposed里的日志有没有报错啥的？

**Comment by liyiecho** [comment]
@kooritea LSP版本1.6.3日志显示这个
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.kooritea.fcmfix.xposed.BroadcastFix$1.beforeHookedMethod(BroadcastFix.java:51)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.broadcastIntentLocked(Unknown Source:134)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13080)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:13924)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2412)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2558)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)
```

**Comment by kooritea** [comment]
@liyiecho 你的是安卓什么版本

**Comment by liyiecho** [comment]
@kooritea miui12.5 安卓12 21.11.30内测版

**Comment by kooritea** [comment]
@liyiecho 安卓12还不支持…（主要是我还没升

**Comment by liyiecho** [comment]
@kooritea 好的，那我还是等大佬适配了再用这模块，谢谢解答

**Comment by kooritea** [comment]
v0.4.2已经发布，可以不用手动找hook位置了
