### ISSUE TITLE
无法对没有后台的应用推送fcm

### ISSUE THREAD

**Issue by zicoad** [kooritea/fcmfix#34]
无法对没有后台的应用推送fcm
就像tg停止自启动后，fcm日志里就显示failed to broadcast

**Comment by kooritea** [comment]
有没有日志

**Comment by zicoad** [comment]
![Screenshot_2021-12-19-11-56-56-363_com google android gms](https://user-images.githubusercontent.com/65034285/146663358-a4241057-c2ca-468b-9aee-4bae226b9883.jpg)
还有就是最新版说要更改文件我换了好多个文件管理器，手机重启过后又变回去了isinit

**Comment by kooritea** [comment]
安卓版本多少

**Comment by zicoad** [comment]
安卓12 红米k40最新开发版 
![正在上传 t2{cc17abc} (d69fdde0-ff0e-444c-b240-43c2ba9fda48 id=0x7f0a039e tag=BaseCommentFragment)…]()

**Comment by kooritea** [comment]
安卓12还不支持…

**Comment by zicoad** [comment]
啊这，好吧

**Comment by kooritea** [comment]
安卓12可以试试现在最新发布的0.4.3

**Comment by zicoad** [comment]
好的，我现在试试

**Comment by zicoad** [comment]
不行哦，现在fcmfix都运行不了![Screenshot_2021-12-20-10-44-17-547_com.google.android.gms.jpg](https://user-images.githubusercontent.com/65034285/146704441-81879598-e1fe-45b8-bc75-eb30a8ed75b8.jpg)

**Comment by liyiecho** [comment]
0.4.3大概率无法连通fcm，来回切换网络，小概率能连通fcm，但是无法唤醒相应的app
![1639981951886](https://user-images.githubusercontent.com/5213722/146722397-df6dcc8e-8e77-410d-a95f-5f963a9e1e16.png)
![1639981951879](https://user-images.githubusercontent.com/5213722/146722448-ca9fe5ae-3f1b-43f3-8f7f-edd3f9c1f70c.png)

**Comment by kooritea** [comment]
> 不行哦，现在fcmfix都运行不了![Screenshot_2021-12-20-10-44-17-547_com.google.android.gms.jpg](https://user-images.githubusercontent.com/65034285/146704441-81879598-e1fe-45b8-bc75-eb30a8ed75b8.jpg)

把配置文件删除然后重启试试
/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml

**Comment by kooritea** [comment]
> 0.4.3大概率无法连通fcm，来回切换网络，小概率能连通fcm，但是无法唤醒相应的app
> ![1639981951886](https://user-images.githubusercontent.com/5213722/146722397-df6dcc8e-8e77-410d-a95f-5f963a9e1e16.png)
> ![1639981951879](https://user-images.githubusercontent.com/5213722/146722448-ca9fe5ae-3f1b-43f3-8f7f-edd3f9c1f70c.png)
> 
> 

小概率能连上那应该不是fcmfix的问题…

无法唤醒可能是你的miui版本上自动允许自启动的功能失效了，给自启动权限试试

**Comment by zicoad** [comment]
> > 0.4.3大概率无法连通fcm，来回切换网络，小概率能连通fcm，但是无法唤醒相应的app
> > ![1639981951886](https://user-images.githubusercontent.com/5213722/146722397-df6dcc8e-8e77-410d-a95f-5f963a9e1e16.png)
> > ![1639981951879](https://user-images.githubusercontent.com/5213722/146722448-ca9fe5ae-3f1b-43f3-8f7f-edd3f9c1f70c.png)
> > 
> > 
> 
> 小概率能连上那应该不是fcmfix的问题…
> 
> 无法唤醒可能是你的miui版本上自动允许自启动的功能失效了，给自启动中的允许系统唤醒权限试试

最新版不是可以无视自启动吗

**Comment by kooritea** [comment]
@zicoad miui版本问题吧，如果你的版本号比我的高那失效也正常

**Comment by zicoad** [comment]
> @zicoad miui版本问题吧，如果你的版本号比我的高那失效也正常

请问您现在的版本是多少

**Comment by kooritea** [comment]
@zicoad 21.8.18

**Comment by zicoad** [comment]
> @zicoad 21.8.18

好吧，我的是21.12.8

**Comment by kooritea** [comment]
@zicoad 你可以发/system/framework里的framework.jar和services.jar给我看看是不是兼容问题

**Comment by liyiecho** [comment]
@kooritea 给了相应app自启动权限后能唤醒了。不用fcmfix的时候，切换网络100%能连上的。0.4.3切换网络就有概率连不上fcm，且心跳重连好几次也没连不上
![1639983960030](https://user-images.githubusercontent.com/5213722/146726381-4d6df485-dfc2-4675-8f7f-451a83e4fa5c.png)

**Comment by kooritea** [comment]
emm，那看看xposed框架的日志看看有没有报错？

**Comment by liyiecho** [comment]
无法连接fcm，大概率是今天我这网络的问题，用了对应的hosts就没问题了。问一下这fcmfix allow list is not ready是不是也需要给fcmfix app自启动权限？
![1640002769701](https://user-images.githubusercontent.com/5213722/146766493-64fb33bd-0885-4404-84c2-30ae8813f292.png)

**Comment by kooritea** [comment]
不用，这个日志一般只会出现在开机后第一次解锁屏幕之前，可以不用管

**Comment by liyiecho** [comment]
好的，谢谢了

**Comment by wzyoct** [comment]
同样也是fcmfix allow list is not ready，系统是coloros12 android12

**Comment by zicoad** [comment]
> > 不行哦，现在fcmfix都运行不了![Screenshot_2021-12-20-10-44-17-547_com.google.android.gms.jpg](https://user-images.githubusercontent.com/65034285/146704441-81879598-e1fe-45b8-bc75-eb30a8ed75b8.jpg)
> 
> 把配置文件删除然后重启试试
> /data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml

![Screenshot_2021-12-20-23-51-04-709_com.google.android.gms.jpg](https://user-images.githubusercontent.com/65034285/146795126-cac7e214-99db-4460-a5d7-8b6444be6267.jpg)
这个是咋回事

**Comment by kooritea** [comment]
@zicoad 新版本的miui不兼容了，给允许系统唤醒权限用着先吧…

**Comment by kooritea** [comment]
@wzyoct 这个无所谓的

**Comment by zicoad** [comment]
> @zicoad 新版本的miui不兼容了，给允许系统唤醒权限用着先吧…

好的，等着您的适配好消息，辛苦了

**Comment by Rakau** [comment]
> 

把电量与性能干掉试试？或者伪装成国际版的

**Comment by zicoad** [comment]
> > 
> 
> 把电量与性能干掉试试？或者伪装成国际版的

咋伪装，模块吗

**Comment by Rakau** [comment]
> > > 
> > 
> > 
> > 把电量与性能干掉试试？或者伪装成国际版的
> 
> 咋伪装，模块吗

https://github.com/ayanamist/miui-powerkeeper-hack
https://blog.minamigo.moe/archives/747
https://blog.minamigo.moe/archives/811

**Comment by yongman** [comment]
> 同样也是fcmfix allow list is not ready，系统是coloros12 android12

我是一加9Pro，coloros12 android12，twrp好像还没有适配，请教一下root的方法？

**Comment by Rakau** [comment]
给boot分区打面具补丁刷进去就好了

yongman ***@***.***> 于 2022年5月27日周五 14:56写道：

**Comment by yongman** [comment]
> 给boot分区打面具补丁刷进去就好了

这种方式，数据是否会被清空？

**Comment by Rakau** [comment]
不会

yongman ***@***.***> 于 2022年5月27日周五 15:07写道：
