### ISSUE TITLE
coloros12，fcm断开后无法自启

### ISSUE THREAD

**Issue by wzyoct** [kooritea/fcmfix#35]
请问一下，关于coloros12 fcm
fcm断开后完全不会自动重连😢需要重启play服务或者切换网络状态才可以，我感觉可能是因为play服务受限制了，有没有办法能去设置系统app的电池优化相关的选项呀，或者干脆一步到位有没有办法解决fcm断开后不重连的问题呀

另外还有一台miui设备，fcm重连就蛮积极的

**Comment by kooritea** [comment]
看看fcm的日志

**Comment by wzyoct** [comment]
> 看看fcm的日志

![Screenshot_2021-12-21-09-35-00-15_f7aa348215f5d566f9e4ca860f474209.jpg](https://user-images.githubusercontent.com/84799213/146855777-2054a22a-a60e-419a-a1b4-c00b45b1be81.jpg)
![Screenshot_2021-12-21-09-34-58-08_f7aa348215f5d566f9e4ca860f474209.jpg](https://user-images.githubusercontent.com/84799213/146855783-2a1474f6-7656-4ae1-93c9-4f99b89b92b2.jpg)
我故意断开fcm，然后现在六分钟里面也没有重连，昨天是断开了两个多小时fcm
一次也没重连，很是尴尬

**Comment by kooritea** [comment]
fcmfix升到最新的0.4.3，然后把这个文件删了，然后重启，再看看fcm日志
/data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml

**Comment by wzyoct** [comment]
> fcmfix升到最新的0.4.3，然后把这个文件删了，然后重启，再看看fcm日志
> /data/data/com.google.android.gms/shared_prefs/fcmfix_config.xml


更新后现在变得重连非常积极！谢谢大佬！我完全没注意到刷机的fcmfix没升级到最新版！不好意思！
大佬注意休息呀！昨天凌晨还看到你在回复！
