### ISSUE TITLE
关于MIUI13的一些体验和问题

### ISSUE THREAD

**Issue by Rakau** [kooritea/fcmfix#38]
我的环境是基于MIUI13的安卓12

1：~~已经可以通过给目标应用的系统唤醒权限即可正常推送，并不需要模块介入~~
2：锁屏断网1：如果锁屏后一段时间，FCM连接会自动断开，充电状态下不会。可以确定是电量与性能搞的鬼
3：锁屏不推送：通过某些模块干掉电量与性能后，FCM锁屏后不断连了，但锁屏会经常遇到有通知不推送的情况，表现为解锁后立马来通知，FCM日志里已经显示前段时间推送了并成功了，FCM连接时间也是正常的，并没有断连。这个问题不知道该怎么处理

**Comment by kooritea** [comment]
第三个如果日志上显示的优先级不是高(priority=NORMAL)的话那就是正常，只有高优先级的fcm通知才会立即唤醒设备进行通知

**Comment by Rakau** [comment]
> 第三个如果日志上显示的优先级不是高(priority=NORMAL)的话那就是正常，只有高优先级的fcm通知才会立即唤醒设备进行通知

感谢回复，优先级是由目标决定还是FCM决定的？

**Comment by kooritea** [comment]
推送方决定的，比如微信的fcm通知就是微信决定的
