### ISSUE TITLE
ZUI上开机首次接收FCM推送卡死问题

### ISSUE THREAD

**Issue by xsm1997** [kooritea/fcmfix#39]
我这里ZUI 13平板遇到了一个开机首次接收FCM推送，会卡死将近20秒的问题。

进一步测试得出，只要开机之后手动打开一次fcmfix app，就不会卡死。反之，即使是开机1分钟之后，尝试进行推送，不打开fcmfix app，也会卡死。

查看logcat，有一条引起注意：

E: Timeout waiting for provider com.kooritea.fcmfix/10253 for provider com.kooritea.fcmfix.provider providerRunning=false caller=system/1000

是不是由于开机没有自动启动引起的问题？

这个智障的ZUI 13系统，如果不声明自启动权限，根本无法手动允许自启动。如果是这个问题的话，能否请您加上显式自启动权限，并编译出来，给我测试一下呢？

logcat文件：
[logcat_02-16-2022_03-46-55.txt](https://github.com/kooritea/fcmfix/files/8074223/logcat_02-16-2022_03-46-55.txt)

感谢。

**Comment by xsm1997** [comment]
自己修改了一下，貌似加上一个自启动权限（android.permission.RECEIVE_BOOT_COMPLETED），再随便写一个BroadcastReceiver（里面啥也不干都行，我是只输出了一行log，不添加Receiver不行），就可以解决问题。此外还需要给自启动权限（给fcmfix，在ZUI安全中心里面）和关联启动权限（fcmfix和目标应用都需要，且只有成功推送一次才有选项，在ZUI安全中心里面）。然后安装app并且激活xposed模块之后一定要手动打开一下，先在系统里打开自启动权限，再打开应用，会收不到开机自启动广播。辣鸡系统。

以上权限和BroadcastReceiver能否添加进主线？期待回复。

**Comment by kooritea** [comment]
明白了，系统启动时确实会尝试启动fcmfix来拉取配置，没想到会有系统的自启动权限连系统进程拉起应用都限制。

不是miui12的系统确实要给目标应用自启动(一般是允许系统唤醒就可以，但是考虑到你这个系统连系统进程都受权限管理那把关联启动也要一起给也不奇怪)，因为我没有相应的机器去适配。。。

[app-release.zip](https://github.com/kooritea/fcmfix/files/8085076/app-release.zip)
这是加了开机广播权限和和receiver的，你依然要安装之后打开一次然后给自启和关联启动，如果没问题我就提交代码了

**Comment by xsm1997** [comment]
测试了下，问题已解决，谢谢！
