### ISSUE TITLE
gmail不能正常推送

### ISSUE THREAD

**Issue by Felix-Jung** [kooritea/fcmfix#4]
![微信图片_20210514210707](https://user-images.githubusercontent.com/65906015/118275058-80c1b680-b4f8-11eb-8aaf-97ae501067fe.jpg)

**Comment by kooritea** [comment]
看日志模块已经在正常运作
实际上应用收到fcm之后不一定会发送通知，日志里收到fcm的时间你的邮箱确认有新邮件吗

**Comment by Felix-Jung** [comment]
> 看日志模块已经在正常运作
> 实际应用收到的fcm之后不一定会发送通知，日志里收到的fcm的时间你的邮箱确认有新邮件吗

嗯嗯，因为我是用另一个号发邮件测试的

**Comment by kooritea** [comment]
emm我试了一下可以正常发出通知，看日志gmail已经成功被fcm唤醒，会不会是你设置->账号里的收件箱通知 没有打开

**Comment by Felix-Jung** [comment]
> emm我试了一下可以正常发出通知，看日志gmail已经成功被fcm唤醒，会不会是你设置->账号里的收件箱通知 没有打开

开了的，我重新安装一下试试，谢谢啦
