### ISSUE TITLE
省电模式下没有通知

### ISSUE THREAD

**Issue by nictse2013** [kooritea/fcmfix#40]
426可以显示拉起wx，但是没有通知
关闭省电，可以接受新的并弹出通知

**Comment by kooritea** [comment]
微信现在好像把fcm设置为了normal优先级。
这个优先级的高低在不同省电策略下有不同表现，所以normal级是不会立即唤醒处于省电模式的设备进行通知的

**Comment by nictse2013** [comment]
是NORMAL
但是省电过程中的推送，关闭后也不会再推了？除非自己打开看？

**Comment by kooritea** [comment]
这个机制我也不是很清楚
