### ISSUE TITLE
换一种思路

### ISSUE THREAD

**Issue by Adlyq** [kooritea/fcmfix#41]
请问有没有可能，我是说可能
Hook FCM 的广播方法，然后自己实现通知，就不用启动被通知的app，这样微信这毒瘤也能完美解决

**Comment by kooritea** [comment]
fcm的数据不一定是通知内容本身，即可能是加密过的消息，也可能是一条消息id，最终需要应用本身来处理后才能发出通知

**Comment by Adlyq** [comment]
谢谢
