### ISSUE TITLE
可能hook到系统UI，通过provider通信获取app白名单不是个好方法

### ISSUE THREAD

**Issue by xsm1997** [kooritea/fcmfix#42]
我这里换回MIUI 13设备测试（小米10S，22.3.3内测版），还是会有之前开机后整个System UI卡住的情况发生。

通过adb logcat发现，这种情况是自启动太多，接收到FCM通知的时候，还没轮到fcmfix自启动。这时System UI通过Provider的方式获取应用信息，就会直接卡住，一直卡到fcmfix完成自启动。

大概在开机解锁进入桌面半分钟之后，我的设备才会启动fcmfix。标志是adb logcat fcmfix:I *:S输出fcmfix  : waiting load config，同时系统也恢复响应。

系统里也没有自定义自启动顺序的选项，MIUI13如果想正常接收FCM推送，还是得给各个app设置自启动。所以是否可以不用provider的方式获取配置的app白名单信息？

**Comment by kooritea** [comment]
miui13还需要给自启动权限是因为我没有miui13设备，所以还没适配。

开机会卡住这个问题之前我手机上会有，后面0.4.x之后改了之后就没有了，这个在研究吧。
通过provider读配置主要是高版本安卓的限制，否则gcm那边拿不到配置

**Comment by kooritea** [comment]
卡住大概就是因为安卓系统进程尝试拉起fcmfix读配置，但是因为启动优先级之类的原因卡在那里等了

**Comment by kooritea** [comment]
开了一个新的线程去读配置，不知道能不能解决
[app-release.zip](https://github.com/kooritea/fcmfix/files/8203331/app-release.zip)

我这边miui12没有这个问题验证不了。。。

**Comment by xsm1997** [comment]
这个新版本很神奇，直接就能读到配置&发送fcm通知。通知显示10几秒之后，logcat才显示fcm自启的那条。。。

算是问题已解决？

**Comment by kooritea** [comment]
fcmfix 自启那条日志是被开机广播唤醒才触发的，读配置的时候不会，读配置依然是通过provider，只不过这个不用主线程去读就不会卡住了。

没问题我提交代码了

**Comment by xsm1997** [comment]
没问题，提交吧，谢谢。
