### ISSUE TITLE
换了航班后失效了

### ISSUE THREAD

**Issue by N2022062** [kooritea/fcmfix#44]
![Screenshot_20220309-191822_Pixel 启动器](https://user-images.githubusercontent.com/6193203/157634411-93e6414a-43b9-4ffd-85bb-61937ccc83cd.png)
怎么试都不行

之前可以 求点拨

**Comment by kooritea** [comment]
给fcmfix 自启动权限试试

**Comment by kooritea** [comment]
这个应该是没有读到配置，看一下xposed 框架里有没有错误日志吧。

https://github.com/kooritea/fcmfix/issues/42#issuecomment-1061454275

也可以试试这个版本

**Comment by nictse2013** [comment]
装了帖子里的后可以了 426里显示hook上了 wx也有推送了
但是fix显示0.44和release的不一样？

**Comment by kooritea** [comment]
发那个的时候还处于测试阶段，现在已经发布了
https://github.com/kooritea/fcmfix/releases/tag/v0.4.5
