### ISSUE TITLE
开启安全DNS是不是会影响FCM裸联

### ISSUE THREAD

**Issue by suaosong** [kooritea/fcmfix#45]
我在lsp中开启了安全DNS 但是发现好像不挂魔法裸连不上.然后我把安全DNS关掉 发现裸连好像能连上了 请问这个和fcm连接有关系吗
![Uploading Screenshot_2022-03-18-08-24-38-178-edit_org.lsposed.manager.jpg…]()

**Comment by kooritea** [comment]
有关，能不能裸连取决于dns解析出来的ip能不能直连，打开和关闭安全dns是查询不同的dns服务器。

https://blog.minamigo.moe/archives/201
可以尝试这个

**Comment by anysoft** [comment]
lsp中应该只对lsp起作用，而不是对整个系统。
整个系统设置里边有安全DNS，也就是DoH 有些系统叫私人DNS。我尝试自建DNS解析，可以一定程度上解决dns问题，效果不太好，对未root的手机是个勉强方案
