### ISSUE TITLE
不挂梯子连不上

### ISSUE THREAD

**Issue by suaosong** [kooritea/fcmfix#47]
目前只有挂梯子能连，wifi，4g都连不上，我已经刷了host模块，也还是只有挂梯子能连上。。
![Screenshot_2022-03-22-18-55-57-845_com google android gms](https://user-images.githubusercontent.com/36725964/159466745-38a1b187-5be2-4942-b03e-76a22464c89a.jpg)
![Screenshot_2022-03-22-18-57-07-490_io github vvb2060 magisk](https://user-images.githubusercontent.com/36725964/159466757-64e43443-bf68-4a89-999a-0aac84e1c739.jpg)

**Comment by kooritea** [comment]
写了host也不是一定连得上，能不能直连和运营商、地区都有关，建议逐个测试删除连不上的ip。
这与fcmfix无关。

**Comment by suaosong** [comment]
> 写出来也不是一定要连得上，能不能直接连和运营商、地区都有关，建议逐个测试删除连不上的ip。 这和fcmfix好了。

老哥我问一下，我在host里输入了这个地址，但是他实际连的时候可能不是这个地址，这两者之间到底是啥关系 求详解

**Comment by suaosong** [comment]
> 写出来也一定要连得上，能不能直接连和运营商、地区都有关，建议逐个测试删除连不上的。 这和fcmfixip就好。

![Uploading Screenshot_2022-03-24-17-14-08-289_bin.mt.plus.jpg…]()
![Screenshot_2022-03-24-17-14-25-436_com google android gms](https://user-images.githubusercontent.com/36725964/159883233-f5015764-6b63-44f1-837c-7c916c675424.jpg)
这两者之间是啥关系呀

**Comment by suaosong** [comment]
> 你的第一张图没传成功

![Screenshot_2022-03-24-17-14-08-289_bin mt plus](https://user-images.githubusercontent.com/36725964/159915108-fc4eb0c5-48fb-489e-bfab-a33a6929d8c5.jpg)
![Screenshot_2022-03-24-17-14-25-436_com google android gms](https://user-images.githubusercontent.com/36725964/159915120-a1083b78-d417-4b2a-a98a-aca77843006e.jpg)
我就是想知道这俩地址是什么关系 为什么我已经在host里面输入这个地址 但是他实际连不只连这一个地址勒？我在host里输入了一个能连的地址，但切换wifi流量它有时候还是重连失败，尽管fcmfix在很努力频繁的唤醒，可就是一直重连失败

**Comment by kooritea** [comment]
fcm不止会连接mtalk.google.com，连接失败时会连alt1-mtalk.google.com再失败就alt2-mtalk.google.com，再失败就alt3…
你可以把alt1到alt5都写进去host 文件

**Comment by suaosong** [comment]
> fcm不止会连接mtalk.google.com，连接失败时会连alt1-mtalk.google.com再失败就alt2-mtalk.google.com，再失败就alt3… 你可以把alt1到alt5都写进去host 文件

![Screenshot_2022-03-24-20-34-09-183_bin mt plus](https://user-images.githubusercontent.com/36725964/159917193-a8701302-1e92-4da0-826d-0a5b67f78dce.jpg)
同一个地址这样写吗？

**Comment by kooritea** [comment]
可以
