### ISSUE TITLE
心跳间隔设置不生效

### ISSUE THREAD

**Issue by csy19960309** [kooritea/fcmfix#49]
![Screenshot_20220324-155631](https://user-images.githubusercontent.com/12546423/159878682-1028a266-8ec6-476f-b868-1b237ee5a124.png)
![Screenshot_20220324-155647](https://user-images.githubusercontent.com/12546423/159878691-a4c6072f-1570-4c55-8948-13f0ad977daa.png)
设置后手机已重启，且配置文件未被重置。
另外，请问这个值的单位是分钟还是秒钟？

**Comment by kooritea** [comment]
这个是毫秒，设置为5s应该写成5000L，最小为1000L，小于1000不生效
设这么短会很耗电

**Comment by csy19960309** [comment]
> 这个是毫秒，设置为5s应该写成5000L，最小为1000L，小于1000不生效 设这么短会很耗电

好的，刚提起这个Issue就看你更新么README. 我设置这么短只是为了测试，想搞清楚是什么单位。
我先改成1000L测试一下。

**Comment by csy19960309** [comment]
使用了你推荐的文件管理器，并且修改后没发现bak文件，重启后配置文件仍然被重置。log如图。
![Screenshot_20220324-181111](https://user-images.githubusercontent.com/12546423/159893764-b87ba17e-90aa-456d-9eff-2bdc77b8e7a0.png)

**Comment by kooritea** [comment]
每次重启都有fcmfix init 这条log吗

**Comment by csy19960309** [comment]
> 每次重启都有fcmfix init 这条log吗

对的

**Comment by kooritea** [comment]
是改完才有这条还是什么都不动重启就有这条。
如果是改了才有那应该是你改的格式有问题，发出来给我看看

**Comment by csy19960309** [comment]
![Screenshot_20220325-101125](https://user-images.githubusercontent.com/12546423/160041427-9e78b6a2-84e8-4503-a205-5548a16ba48b.png)
配置如图。还是会出现fcmfix_config init的打印。刚开机时没网，我要设置下才有网，会导致这个问题么？

**Comment by kooritea** [comment]
没网不影响
你用的是哪一个xposed 框架什么版本

**Comment by csy19960309** [comment]
> 没网不影响 你用的是哪一个xposed 框架什么版本

Lsposed 1.7.2(6478) Zygisk.
Magisk 是alpha 24301.

**Comment by kooritea** [comment]
把配置文件删掉，重启两次不要改配置文件，看看是不是两次都会有fcmfix init这条log。
先确定是不是读不到配置文件的问题吧。

重启可以不用重启手机，直接结束gms运行就行

**Comment by csy19960309** [comment]
> 

删掉配置文件，重启时会fcmfix_config init. 配置文件也会重置。

**Comment by csy19960309** [comment]
> 把配置文件删掉，重启两次不要改配置文件，看看是不是两次都会有fcmfix init这条log。 先确定是不是读不到配置文件的问题吧。
> 
> 重启可以不用重启手机，直接结束gms运行就行

删掉配置文件，重启时会fcmfix_config init. 配置文件也会重置。

**Comment by kooritea** [comment]
试了一下设置心跳间隔确实有问题，有空再修

**Comment by kooritea** [comment]
原来是配置文件不用写L，直接写300000就好了，我都忘记了

**Comment by csy19960309** [comment]
> 原来是配置文件不用写L，直接写300000就好了，我都忘记了

好的谢谢，我有空了再试试。
