### ISSUE TITLE
配置文件改好了 一重启又变回去了

### ISSUE THREAD

**Issue by q601207194** [kooritea/fcmfix#5]
按步骤操作改好了配置文件，然后重启后有什么也没了，这是动态分区的锅吗
手机是k30pro

**Comment by kooritea** [comment]
是不是用mt管理器改的，这个编辑器好像有点问题，好像要删除bak后缀的同名文件才有效

**Comment by q601207194** [comment]
是的，要换一个软件吗

**Comment by kooritea** [comment]
好像删掉备份文件就生效了，或者设置里面关掉生成备份文件的设置

如果要换的话可以试试这个
https://play.google.com/store/apps/details?id=in.mfile

**Comment by q601207194** [comment]
可以了  就是mt管理器的问题

**Comment by kooritea** [comment]
模块有正常生效吗，没问题的话我关了

**Comment by q601207194** [comment]
![Screenshot_2021-05-25-16-54-22-165_com google android gms](https://user-images.githubusercontent.com/70868125/119469413-e8d68f00-bd79-11eb-9cfb-5107db53bd94.jpg)
应该是可以的

**Comment by kooritea** [comment]
配置文件的enable没改成true。。配置的是没生效的(防止重连失败和固定心跳)
如果只需要fcm唤醒应用的话其实不用改配置文件

**Comment by q601207194** [comment]
大佬我问下是不是  把value  false 改成true  我貌似傻逼的把name 改成了true
![Uploading Screenshot_2021-05-25-17-03-44-103_in.mfile.jpg…]()

**Comment by q601207194** [comment]
我傻逼了  改错了    感谢大佬
