### ISSUE TITLE
日志提示"allow list is not ready"

### ISSUE THREAD

**Issue by qifeng2233** [kooritea/fcmfix#50]
![Screenshot_2022-03-26-13-48-17-658_com google android gms](https://user-images.githubusercontent.com/76868731/160226704-bd73934a-192a-4cca-b765-72fa689301ca.jpg)

**Comment by kooritea** [comment]
给fcmfix 自启动权限试试

**Comment by qifeng2233** [comment]
> 

解决了，感谢

**Comment by qifeng2233** [comment]
> 给fcmfix 自启动权限试试

大佬，reconnInterval和heartbeatInterval设置后重启都会被覆盖为0怎么解决，我设置的300000L

**Comment by kooritea** [comment]
这个功能有问题，下个版本修

**Comment by kooritea** [comment]
设置300000就不会重启被覆盖了
