### ISSUE TITLE
safetynet验证问题

### ISSUE THREAD

**Issue by StephenSSR** [kooritea/fcmfix#53]
设备为一加 coloros12.1 magisk24.3 lsp1.80，经测试只要勾选com.google.android.gms就无法通过safetynet验证，测试软件为YASNAC

**Comment by kooritea** [comment]
我用YASNAC试了一下可以通过，可能是没有magisk hide的问题吧

**Comment by Chu2koi** [comment]
一样的问题，safetynet过不了，安卓12，pixel4xl和pixel6都不行

**Comment by Rakau** [comment]
不能HOOK谷歌，会失去safetynet

**Comment by jordanyoong1** [comment]
同样问题，使用Realme UI 3.0 (换皮COS12) 安卓12。 有使用Shamiko
