### ISSUE TITLE
Android12类原生无法拉取已停止应用

### ISSUE THREAD

**Issue by wzyoct** [kooritea/fcmfix#54]
lsposed18.0，zygisk激活
fcmfix 0.4.6
作用于仅勾选了 Android系统
尝试停止后台后接受fcm消息，但是日志里始终显示无法拉取
![Screenshot_20220406-155214_Google Play 服务](https://user-images.githubusercontent.com/84799213/161924525-65f906f8-4cf1-47a9-8b49-e4006eb80cf5.png)
有后台就能收到，无后台就无法拉取

**Comment by kooritea** [comment]
该不会是没有在fcmfix里勾选目标应用吧？
截图看一下开机时的日志

**Comment by wzyoct** [comment]
![Screenshot_20220408-022203_Shell](https://user-images.githubusercontent.com/84799213/162271007-add547e2-4ba3-478c-9985-1201931d7900.png)
![Screenshot_20220408-022212_fcmfix](https://user-images.githubusercontent.com/84799213/162271015-b753d049-db38-4f0c-8aad-44bc683009b9.png)
![Screenshot_20220408-022222_Google Play 服务](https://user-images.githubusercontent.com/84799213/162271022-d9f5160b-f1bc-48b8-8566-7f85360b4393.png)
第一张图片是作用域，第二张是fcmfix里勾选的应用（我确实勾选了，第三张是fcm刚开机时候的日志，非常奇怪，安卓11的类原生用起来就没有任何的问题，
ps:大佬有没有tg群之类的联系方式呀

**Comment by kooritea** [comment]
lsp作用域中先勾上google play 服务。
然后重启，再看看日志

**Comment by wzyoct** [comment]
![Screenshot_20220408-094327_Google Play 服务](https://user-images.githubusercontent.com/84799213/162346737-26a4a96d-d7a3-4f26-bccf-84f1dda6887c.png)
![Screenshot_20220408-094451_Shell](https://user-images.githubusercontent.com/84799213/162346772-1a0336f2-751b-4ca6-a8ac-caf9f5e04eda.png)
好的,这是日志的截图

**Comment by wzyoct** [comment]
作用域把play服务和Android系统都勾选上还是一样的无法唤醒未运行app（就只是在系统设置里面强制停止了

**Comment by kooritea** [comment]
好像是没拿到配置，在fcmfix勾选或者取消勾选一下随便一个应用，看看能不能在日志里看到update allow list字样的日志

**Comment by wzyoct** [comment]
![Screenshot_20220408-165401_Google Play 服务](https://user-images.githubusercontent.com/84799213/162401637-ce71659e-07a5-4c08-996b-bafb3b117a63.png)
按照你说的去做了，勾选了也取消了，都尝试了，日志没有变化

**Comment by wzyoct** [comment]
按照你说的做完了就立刻去打开日志，然后没有相关的字样，这是没拿到配置是嘛？

**Comment by kooritea** [comment]
emmm，lsposed里的日志看看有没有fcmfix 抛出的异常？
这边也不知道是啥问题

**Comment by wzyoct** [comment]
我可以把日志发给你吗？😭我看日志看不懂

**Comment by kooritea** [comment]
可以，因为不知道有没有隐私信息，你可以发到我邮箱[github@kooritea.moe](mailto:github@kooritea.moe)

其实也不一定能解决，因为我没安卓12的设备哈(

**Comment by wzyoct** [comment]
作者你好，我的设备是一加8T，一开始用类原生
havoc安卓11,fcmfix一切正常，后来升级到了安卓12(类原生)，发现fcmfix不可用，所以来反馈的，现在我回到了官方ROM，安卓11(oxygen11),fcmfix仍然不可用（猜想会不会是因为我是用备份数据的app直接恢复了这个app，不过我也卸载重装了，仍然不行


kooritea ***@***.***> 于 2022年4月8日周五 下午5:30写道：

**Comment by wzyoct** [comment]
破案了破案了，需要给fcmfix自启权限,我以为和别的xp模块一样不需要，可以用啦！

**Comment by kooritea** [comment]
我在miui上是不需要自启动权限的…应该是不同的rom对这个限制不同

**Comment by kooritea** [comment]
需要自启是因为配置是存fcmfix上的，所以要启动读取配置，现在主流的xp模块配置都是存在寄宿的应用上，就不用。
