### ISSUE TITLE
死活连不上了，这种情况是咋回事？

### ISSUE THREAD

**Issue by suaosong** [kooritea/fcmfix#55]
![Screenshot_2022-04-17-10-21-35-150_com google android gms](https://user-images.githubusercontent.com/36725964/163697497-1ca2091e-6ab7-4993-898d-fae1cc00a635.png)
以前重启一下谷歌服务能连上，这回怎么重启也不连了。。网络啥的都正常

**Comment by kooritea** [comment]
这个这边也判断不了
