### ISSUE TITLE
新用户求助，无法使fcmfix生效的问题

### ISSUE THREAD

**Issue by zyh941** [kooritea/fcmfix#56]
开发者您好，我是fcmfix的新用户，我是这么安装尝试使用的：先装了fcmfix app，然后刷入LSPosed模块，进去点启用fcmfix和里面的system framework，在app里也勾选了我想要的几个应用。并且重启了手机。以一个邮件app为例(com.easilydo.mail)，我强制停止了，然后测试接收邮件提醒，但是完全不能生效，fcm日志里还是像以前没用模块时一样fail to broadcast to stopped app。请帮看看是什么原因，附件里是lsp中导出的日志
手机型号：Pixel 4，Android 12L，网络：漫游网络，不存在连不上的问题
[LSPosed_2022-04-18T15_35_39.133.zip](https://github.com/kooritea/fcmfix/files/8504317/LSPosed_2022-04-18T15_35_39.133.zip)
![截图](https://user-images.githubusercontent.com/95530307/163774188-8477b039-379b-4c9e-abe7-5317ece07748.png)

g

**Comment by kooritea** [comment]
12L还没适配
看看lsposed 日志里有没有异常

**Comment by zyh941** [comment]
> 12L还没适配 看看lsposed 日志里有没有异常

LSP日志里应该是有异常，我不太会看，不过我已经将它上传到本issue里了。我只想要那个唤醒功能，现在我这边的安装操作是正确的么

**Comment by kooritea** [comment]
我还以为那个连接是图片。。
看了一下确实是12l没适配的问题，把/system/framework/services.jar 和/system/framework/framework.jar这两个文件发给我

**Comment by zyh941** [comment]
> 我还以为那个连接是图片。。 看了一下确实是12l没适配的问题，把/system/framework/services.jar 和/system/framework/framework.jar这两个文件发给我

请查收附件。单位上网，github间歇性被墙真的无语……
[framework+services.zip](https://github.com/kooritea/fcmfix/files/8504501/framework%2Bservices.zip)

**Comment by kooritea** [comment]
[0.4.8-preview.zip](https://github.com/kooritea/fcmfix/files/8504701/0.4.8-preview.zip)
试试这个

**Comment by zyh941** [comment]
> [0.4.8-preview.zip](https://github.com/kooritea/fcmfix/files/8504701/0.4.8-preview.zip) 试试这个

成功了，上面提到的邮件APP成功地在被强制停止后还能由fcm拉起来推送通知。谢谢你的积极改进！
