### ISSUE TITLE
hook电量和性能后电池优化列表被锁定

### ISSUE THREAD

**Issue by David-plz** [kooritea/fcmfix#59]
大佬我一直用着0.4.8版，有个小问题就是048 hook电量和性能后我把微信QQ进行电池优化后，开启吃米插件的禁止还原电池列表，重启手机后微信QQ还是恢复成未优化状态。这个能改善吗？系统MIUI12.5安卓11

**Comment by kooritea** [comment]
是fcmfix hook了电池与性能之后才会出现电池列表重启还原吗

**Comment by David-plz** [comment]
> 是fcmfix hook了电池与性能之后才会出现电池列表重启还原吗

是，MIUI默认的电池未优化列表不是有微信QQ小米应用商店支付宝什么的么而且默认是修改后重启还原，0.48. hook电量和性能后除了微信QQ和少部分保留在未优化列表里其余都被优化了，同时新的未优化列表还是修改后重启就还原，此时我还没装吃米呢。今天装上吃米后选择了禁止还原电池列表，修改微信QQ状态后重启还是还原成新未优化状态

**Comment by David-plz** [comment]
换句话说大佬的0.4.8的hook后比吃米的优先级都大，电池未优化列表被清理掉一部分后直接锁定了

**Comment by kooritea** [comment]
这个不好解决，现在这边只是做了一个伪装成国际版的操作，很难知道是什么问题

**Comment by David-plz** [comment]
> 这个不好解决，现在这边只是做了一个伪装成国际版的操作，很难知道是什么问题

好的无所谓，无伤大雅不影响使用的
