### ISSUE TITLE
安装在Xposed里面使用吗

### ISSUE THREAD

**Issue by lsjiaowo** [kooritea/fcmfix#6]
是在Xposed里安装fcmfix吗？不太清楚怎样使用

**Comment by kooritea** [comment]
xposed是一个安装在系统里的框架，不存在什么装在xposed里面
你该不会用的是virtual xposed 吧

**Comment by lsjiaowo** [comment]
我装的就是virtual xposed 。。。。要在哪里下载xposed（我傻傻分不清。。。）

**Comment by kooritea** [comment]
fcmfix不支持virtual xposed(也无法支持)
安装xposed的话这个就说来话长了

你要先取得手机的root，然后安装magisk，或者刷解锁bl刷twrp，然后在twrp里刷magisk
安装好magisk之后在magisk仓库里安装edxposed或者lsposed，就能使用fcmfix了

**Comment by lsjiaowo** [comment]
原来如此！这么漫长的操作步骤，没经验真怕把手机刷成砖了，折腾不动了Orz。总之还是感谢作者回复！
