### ISSUE TITLE
bug：重启会失效，需要重新手动勾选app

### ISSUE THREAD

**Issue by 3166265725** [kooritea/fcmfix#60]
![Screenshot_20220527-210053_Google Play 服务](https://user-images.githubusercontent.com/61723005/170704360-b143c8d4-4262-46d5-adde-5d4b810b26f3.png)
一加9r，nameless，Android12.1，fcmfix0.4.8
重启会出现[fcmfix]Allow list is not ready，然后就Failed to broadcast to stopped app，打开fcmfix重新勾选一下应用才可以

**Comment by kooritea** [comment]
一加有没有自启动之类的权限，给fcmfix本体自启动看看

**Comment by 3166265725** [comment]
> 一加有没有自启动之类的权限，给fcmfix本体自启动看看

好的，解决了
