### ISSUE TITLE
希望能适配oppo系锁屏fcm掉线

### ISSUE THREAD

**Issue by AragakiSaro** [kooritea/fcmfix#64]
在使用oppo手机color12时发现锁屏几分钟fcm会掉线，像miui那样把 系统软件“电池”冻结掉就能正常，顺便试了下color国际版系统没这个情况

**Comment by kooritea** [comment]
miui是用
```
ro.product.mod_device
IS_INTERNATIONAL_BUILD
IS_GLOBAL_BUILD
```
这几个来判断是不是国际版的，得有人先研究一下oppo是怎么样判断国际版的

**Comment by AragakiSaro** [comment]
请问这几行是在哪个文件里找到的？我在color里找找看

**Comment by kooritea** [comment]
在/system 找到电量与性能的软件包，再反编译看代码

**Comment by anysoft** [comment]
> 
并不一定是这个包，你可以先冻结禁用这个包，
看是否锁屏十分钟左右掉线，如果不掉线就确认是这个包

**Comment by AragakiSaro** [comment]
冻结后就正常了，我现在是用color13内测的 电池.apk 替换原来的版本，fcm也正常但是因为大版本不匹配所以 电池页面有bug，凑活用了

**Comment by anysoft** [comment]
> 冻结后就正常了，我现在是用color13内测的 电池.apk 替换原来的版本，fcm也正常但是因为大版本不匹配所以 电池页面有bug，凑活用了

没找到其他关键位置。
``` java
package com.oplus.a.i;

import android.content.Context;
import android.content.SharedPreferences;
import com.oplus.a.f.a;
import java.util.ArrayList;

/* compiled from: SmartModeSharepref */
public class b {

    /* renamed from: a  reason: collision with root package name */
    private static final ArrayList<String> f1989a = new ArrayList<String>() {
        {
            add("com.google.android.gms");
            add("com.google.android.configupdater");
            add("com.android.vending");
        }
    };
```

你可以尝试反编译后删除 `add("com.google.android.gms");` 这行，再替换。
如果可以的话让作者加入hook就行。

**Comment by AragakiSaro** [comment]
此问题随着color13的更新被自动修复...

**Comment by zx3777** [comment]
> 此问题随着color13的更新被自动修复...

升级13后锁屏一点都不掉了吗？

**Comment by AragakiSaro** [comment]
不掉了，但是会心跳负数或者连着也收不到消息...直到下一次心跳

**Comment by zx3777** [comment]
> 

我是c11，试过各种方法，冻结电池也掉线，最稳的就是充电的时候，一次都不掉。我试过伪装充电状态，也不行。

**Comment by AragakiSaro** [comment]
你可以先查看gms是否在电池优化白名单，然后把gms心跳间隔调低点试试
&nbsp;


1280082251
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 中午1:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [kooritea/fcmfix] 希望能适配oppo系锁屏fcm掉线 (Issue #64)





   
我是c11，试过各种方法，冻结电池也掉线，最稳的就是充电的时候，一次都不掉。我试过伪装充电状态，也不行。

**Comment by AragakiSaro** [comment]
> > 
> 
> 我是c11，试过各种方法，冻结电池也掉线，最稳的就是充电的时候，一次都不掉。我试过伪装充电状态，也不行。

我今天拿另一台外版手机对比发现，延时跟系统无关出自网络，两台手机fcm收不到时一块收不到，应该是上头采取什么措施了，我的延迟是最近一周出现的

**Comment by zx3777** [comment]
> > > 
> > 
> > 
> > 我是c11，试过各种方法，冻结电池也掉线，最稳的就是充电的时候，一次都不掉。我试过伪装充电状态，也不行。
> 
> 我今天拿另一台外版手机对比发现，延时跟系统无关出自网络，两台手机fcm收不到时一块收不到，偶尔秒收到两台都是秒收，应该是上头采取什么措施了，我的延迟是最近一周出现的
> 
> 而且奇怪的是挂梯子再连fcm，延迟还是那样，不懂抽风的是谷歌还是国内网络
> 
> 编辑下，好吧我破案了，有问题的是telegram的fcm通道，其他app正常

我好像找到解决办法了，裸连肯定是不行的。代理软件我用surfboard，vmess方式，最重要的是要给代理软件完全后台权限，这样连接时间能达到15-20分钟断一次，然后秒连，能用了。现在我这个手机还有一个毛病就是锁屏断wifi，这个影响不大，数据也能秒连fcm，但是很烦。

**Comment by zx3777** [comment]
> > > 
> > 
> > 
> > 我是c11，试过各种方法，冻结电池也掉线，最稳的就是充电的时候，一次都不掉。我试过伪装充电状态，也不行。
> 
> 我今天拿另一台外版手机对比发现，延时跟系统无关出自网络，两台手机fcm收不到时一块收不到，偶尔秒收到两台都是秒收，应该是上头采取什么措施了，我的延迟是最近一周出现的
> 
> 而且奇怪的是挂梯子再连fcm，延迟还是那样，不懂抽风的是谷歌还是国内网络
> 
> 编辑下，好吧我破案了，有问题的是telegram的fcm通道，其他app正常

还有要用规则模式，不要用分应用代理。

**Comment by 17998384** [comment]
> 

不是这段代码，我在c13的电池上也看到有这段
