### ISSUE TITLE
Android 12L 202207月更新后失效

### ISSUE THREAD

**Issue by zyh941** [kooritea/fcmfix#66]
开发者您好，我几个月前就一直正常使用fcmfix，但是发觉202207月更新后，fcmfix失效了，我重装了几次模块，都不能正常拉起被强制停止的app。fcm日志里是没用模块时一样fail to broadcast to stopped app。请帮看看是什么原因，附件里是之前说过的/system/framework/services.jar 和/system/framework/framework.jar
手机型号：Pixel 5，Android 12L 202207月更新，网络：漫游网络，不存在连不上的问题
[service+framework.zip](https://github.com/kooritea/fcmfix/files/9116867/service%2Bframework.zip)

**Comment by kooritea** [comment]
把fcmfix挂在后台看看能不能正常使用

**Comment by zyh941** [comment]
没有效果

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
发件人: kooritea ***@***.***>
发送时间: Friday, July 15, 2022 9:17:34 AM
收件人: kooritea/fcmfix ***@***.***>
抄送: zyh941 ***@***.***>; Author ***@***.***>
主题: Re: [kooritea/fcmfix] Android 12L 202207月更新后失效 (Issue #66)


把fcmfix挂在后台看看能不能正常使用

―

**Comment by kooritea** [comment]
找到问题了，broadcastIntentLocked的入参变了。
刚开机之后日志里面有提示 未适配的安卓版本吗

**Comment by zyh941** [comment]
这是从LSPosed导出来的日志记录，我不会看……麻烦看下
[LSPosed_2022-07-15T10_06_54.320.zip](https://github.com/kooritea/fcmfix/files/9117106/LSPosed_2022-07-15T10_06_54.320.zip)

**Comment by kooritea** [comment]
[fcmfix-0.4.9-preview.zip](https://github.com/kooritea/fcmfix/files/9129941/fcmfix-0.4.9-preview.zip)

试一下这个，没问题了我再提交代码。
因为我电脑重装了没有保留之前的签名密钥，所以这个不能覆盖安装，要先把原来的卸载。

**Comment by zyh941** [comment]
测试了WeChat，强停之后，正常拉起并推送了。
  

  

  
  
  
  
>
