### ISSUE TITLE
安卓9无法使用

### ISSUE THREAD

**Issue by Maplerm** [kooritea/fcmfix#67]
什么时候向下兼容安卓9？

**Comment by kooritea** [comment]
[fcmfix-0.4.9-preview.zip](https://github.com/kooritea/fcmfix/files/9129955/fcmfix-0.4.9-preview.zip)

这个写了安卓9的对应的方法，但是不保证能用，因为我没有设备测试

**Comment by 466aijq** [comment]
好的
