### ISSUE TITLE
心跳间隔如何具体配置

### ISSUE THREAD

**Issue by G75201314** [kooritea/fcmfix#68]
应该修改fcmfix_config.xml里的哪些数值呢？

**Comment by kooritea** [comment]
heartbeatInterval项的value，1000=1秒

**Comment by G75201314** [comment]
> 

明白啦，那reconnInterval这个项的value是啥？需要修改吗？

**Comment by kooritea** [comment]
这个是重新连接的间隔，这个功能没有测试过，用不到就不用改了

**Comment by G75201314** [comment]
> 这个是重新连接的间隔，这个功能没有测试过，用不到就不用改了



> 

好的，知道啦！谢谢开发大大解答🥰！
