### ISSUE TITLE
日志显示Successful broadcast tocom.tencent.mm但是没有消息推送

### ISSUE THREAD

**Issue by so1ar** [kooritea/fcmfix#70]
微信后台也被拉起了，但是没有收到消息
![S20805-07080999](https://user-images.githubusercontent.com/54471528/182970864-a4d0a2ae-85ed-4085-8dd6-f582f1c370d9.png)

**Comment by kooritea** [comment]
微信消息优先级的问题，fcmfix已经正常工作
