### ISSUE TITLE
关于锁屏断连，尝试参考一下 MIUI 性能救星 的 hook？

### ISSUE THREAD

**Issue by TigerBeanst** [kooritea/fcmfix#72]
我这边只用 fcmfix 的话，MIUI 13 Android 12 还是会在锁屏的时候断开连接而且不会重连，但我发现用了 MIUI 性能救星对 `电量与性能` 和 `Joyose`（屏蔽全部规则） 进行应用后，似乎 MIUI 不会再打断 fcm 的连接……？

https://github.com/test01wrk/MIUIPerfSaver

还没有充分的测试，明天早上起床看看还连着不（

**Comment by TigerBeanst** [comment]
好，它果然还是寄了（

**Comment by Walkar66** [comment]
> 好，它果然还是寄了（

感觉仍然收不到推送

**Comment by TigerBeanst** [comment]
> > 好，它果然还是寄了（
> 
> 感觉仍然收不到推送

可以尝试用最新代码编译一个，作者合并了一个修复但还没推新包，目前看来我这边会正常唤起了。
我自己打包了一个，但是建议只有在安装核心破解的情况下安装，不然由于签名不同会需要卸载重装
https://tmp.link/f/62fafc95b3f6c

**Comment by kooritea** [comment]
下午我发一下版吧

**Comment by TigerBeanst** [comment]
> 下午我发一下版吧

但是似乎在防止负数的问题上还是有问题诶……
![Screenshot_2022-08-16-11-39-51-218_com google android gms](https://user-images.githubusercontent.com/3889846/184793128-cfe5ccff-2cbf-4b6d-9b29-01da151a5a1b.jpg)

**Comment by kooritea** [comment]
看看日志那边有没有重连的日志？

**Comment by TigerBeanst** [comment]
> 看看日志那边有没有重连的日志？
似乎没有了
![Screenshot_2022-08-16-11-48-35-504_com google android gms_Mosaic_11_48_42](https://user-images.githubusercontent.com/3889846/184794011-4820f4ba-87b1-4e16-b5a0-9b8cc211ff7a.jpg)

**Comment by kooritea** [comment]
那得看一下xposed的日志了

**Comment by TigerBeanst** [comment]
> 那得看一下xposed的日志了

LSPosed 中粗略看是没有报错……

[LSPosed_2022-08-16T12_20_31.547.zip](https://github.com/kooritea/fcmfix/files/9347869/LSPosed_2022-08-16T12_20_31.547.zip)
