### ISSUE TITLE
Android 13正式版内失效

### ISSUE THREAD

**Issue by zyh941** [kooritea/fcmfix#73]
开发者您好，我上个月提交了2022年7月的Android 12L更新导致模块失灵的问题，并得到了您的积极解决。不过现在我升级到了新鲜的Android 13正式版，fcmfix又失效了，我重装了几次模块，都不能正常拉起被强制停止的app。fcm日志里是没用模块时一样failed to broadcast to stopped app。请帮看看是什么原因，附件里是之前说过的/system/framework/framework.jar 和/system/framework/services.jar和LSPosed导出的日志
手机型号：Pixel 5，Android 13正式版 ，网络：漫游网络，不存在连不上的问题
[Android 13 stable.zip](https://github.com/kooritea/fcmfix/files/9366878/Android.13.stable.zip)

**Comment by kooritea** [comment]
已更新
