### ISSUE TITLE
fcm无效

### ISSUE THREAD

**Issue by Stfrostec** [kooritea/fcmfix#75]
提示allow list is not ready
然后还是无法对已停止应用唤醒

**Comment by kooritea** [comment]
给fcmfix自启动权限看看

**Comment by Stfrostec** [comment]
![Screenshot_2022-08-21-18-17-54-29_f7aa348215f5d566f9e4ca860f474209](https://user-images.githubusercontent.com/65583472/185786439-d8b9dc50-4527-4247-b7db-a788832bc6b0.jpg)
已给，已重启，仍然会有提示

**Comment by Stfrostec** [comment]
已解决
但我还是想问下
gms能获取推送内容吗
比方说qq就可以用hms推送实现（我看着后台是无qq进程）
这样不用后台挂着微信占内存

**Comment by kooritea** [comment]
有的能有的不能，通不通过gms传送消息内容是由应用自己决定的

**Comment by Stfrostec** [comment]
感谢大佬
