### ISSUE TITLE
推送应用在一段时间内未启动时，fcmfix 虽然强制广播了，但推送应用报 404 错误

### ISSUE THREAD

**Issue by TigerBeanst** [kooritea/fcmfix#77]
### 设备
Xiaomi MIX 4 开发版内测 22.8.25，Android 12

### 相关应用版本：
- Spark：2.11.10
- Google Play 服务：22.32.12
### fcmfix
1. 0.4.10 或 （0.4.11+ PR #76 ）
2. 已勾选所有推荐作用域，应用中已勾选 Spark邮箱
3. fcm 此时连接正常保持

### Spark 邮箱的设置
1. 没有关闭通知权限，已检查
2. 自启动 权限全开
4. 手动启动它来拉取邮件的话，可以正常拉取

### 情况
（未安装 Thanox，应该不是 #51 的情况）
大概是图里这样，出现了 `xxx returned error code=404 to broadcast`

用 Spark邮箱(com.readdle.spark) 做例子，图二中可以看到 23 点没有自启动记录（当然也有可能是 #76 的原因，截图时已经是带了这个 pr 的版本了）。我在 23:27 尝试用另一个邮箱向此 App 中已设置的邮箱发送了测试邮件，根据 FCM 信息，23:28 左右已经能接收到了，但最终没有成功拉起 Spark邮箱 发出推送

![Screenshot_2022_08_25_23_31_03_526_com_google_android_gms_Mosaic](https://user-images.githubusercontent.com/3889846/186707665-ec824aef-c0bd-427f-9e9a-2f27658e7782.jpg)

![Screenshot_2022-08-25-23-34-17-611_com miui securitycenter](https://user-images.githubusercontent.com/3889846/186708340-5113f975-c759-49e5-b310-494aa552c7d7.jpg)

### LSPosed 日志
https://tmp.link/f/63079a0591590

**Comment by kooritea** [comment]
行为记录里没有自启动记录是预期行为。
能不能用其他app测试一下还会不会有404呢，不确定这是不是miui13对自启动有其他限制

**Comment by kooritea** [comment]
发一下你的/system/framework/services.jar给我

**Comment by TigerBeanst** [comment]
> 发一下你的/system/framework/services.jar给我

https://tmp.link/f/6309259fda1f6

**Comment by kooritea** [comment]
/system/framework/framework.jar也发给我吧

**Comment by Rakau** [comment]
一样的情况，部分应用没有推送。而且有时候系统会弹出气泡提示系统异常，请重启手机

**Comment by TigerBeanst** [comment]
> /system/framework/framework.jar也发给我吧

https://tmp.link/f/6309d668c23a5

**Comment by TigerBeanst** [comment]
> 一样的情况，部分应用没有推送。而且有时候系统会弹出气泡提示系统异常，请重启手机

这个我倒是没有诶

**Comment by Rakau** [comment]
> > 一样的情况，部分应用没有推送。而且有时候系统会弹出气泡提示系统异常，请重启手机
> 
> 这个我倒是没有诶

我再观望一下，不过微信进FCM很好（然并

**Comment by kooritea** [comment]
[app-release.zip](https://github.com/kooritea/fcmfix/files/9440923/app-release.zip)
多调用了一个方法，不知道有没有效果(

**Comment by TigerBeanst** [comment]
> [app-release.zip](https://github.com/kooritea/fcmfix/files/9440923/app-release.zip) 多调用了一个方法，不知道有没有效果(

甚至开始负数了（

**Comment by kooritea** [comment]
负数那个是另一部分的东西，先不管了

**Comment by TigerBeanst** [comment]
> 负数那个是另一部分的东西，先不管了

不行，依旧404……

![Screenshot_2022-08-29-18-22-11-718_com google android gms_Mosaic_18_22_18](https://user-images.githubusercontent.com/3889846/187180520-b963b859-c895-4c3f-9e77-b52692010071.jpg)

**Comment by kooritea** [comment]
那这个得等其他大佬来解决了。。 主要是我这也没法复现

**Comment by anysoft** [comment]
> > 负数那个是另一部分的东西，先不管了
> 
> 不行，依旧404……
> 
> ![Screenshot_2022-08-29-18-22-11-718_com google android gms_Mosaic_18_22_18](https://user-images.githubusercontent.com/3889846/187180520-b963b859-c895-4c3f-9e77-b52692010071.jpg)

https://github.com/anysoft/fcmfix/releases
参考我写的，我之前也是404，清数据后正常了。

**Comment by Rakau** [comment]
> > > 负数那个是另一部分的东西，先不管了
> > 
> > 
> > 不行，依旧404……
> > ![Screenshot_2022-08-29-18-22-11-718_com google android gms_Mosaic_18_22_18](https://user-images.githubusercontent.com/3889846/187180520-b963b859-c895-4c3f-9e77-b52692010071.jpg)
> 
> https://github.com/anysoft/fcmfix/releases 参考我写的，我之前也是404，清数据后正常了。

清哪个数据

**Comment by anysoft** [comment]
> > > > 负数那个是另一部分的东西，先不管了
> > > 
> > > 
> > > 不行，依旧404……
> > > ![Screenshot_2022-08-29-18-22-11-718_com google android gms_Mosaic_18_22_18](https://user-images.githubusercontent.com/3889846/187180520-b963b859-c895-4c3f-9e77-b52692010071.jpg)
> > 
> > https://github.com/anysoft/fcmfix/releases 参考我写的，我之前也是404，清数据后正常了。
> 
> 清哪个数据

1. 清除spark(接收推送的应用) 和com.android.gms (google play services)数据
2. 翻墙登录google账号
3. 登录spark应用


2,3都要保持网络畅通，确保能成功注册fcm

我当时就是这样成功的，然后接收推送的应用不要用其他限制软件去压制(比如thanox乖巧，ops的服务和activity不要禁用)

**Comment by TigerBeanst** [comment]
> 
> 1. 清除spark(接收推送的应用) 和com.android.gms (google play services)数据
> 2. 翻墙登录google账号
> 3. 登录spark应用
> 
> 2,3都要保持网络畅通，确保能成功注册fcm
> 
> 我当时就是这样成功的，然后接收推送的应用不要用其他限制软件去压制(比如thanox乖巧，ops的服务和activity不要禁用)

但按理说应用已经注册上了的（毕竟同一个应用也曾经推送成功过。。。）

**Comment by anysoft** [comment]
> > 1. 清除spark(接收推送的应用) 和com.android.gms (google play services)数据
> > 2. 翻墙登录google账号
> > 3. 登录spark应用
> > 
> > 2,3都要保持网络畅通，确保能成功注册fcm
> > 我当时就是这样成功的，然后接收推送的应用不要用其他限制软件去压制(比如thanox乖巧，ops的服务和activity不要禁用)
> 
> 但按理说应用已经注册上了的（毕竟同一个应用也曾经推送成功过。。。）

不要按理，我当时app开着能收到消息，关闭后唤醒就是404.
按流程操作一遍呗，又不亏

**Comment by TigerBeanst** [comment]
> > 但按理说应用已经注册上了的（毕竟同一个应用也曾经推送成功过。。。）
> 
> 不要按理，我当时app开着能收到消息(也是走的fcm收到的)，关闭后唤醒就是404. 按流程操作一遍呗，又不亏

行，我清除了数据，测试一段时间看看（

**Comment by TigerBeanst** [comment]
> 不要按理，我当时app开着能收到消息(也是走的fcm收到的)，关闭后唤醒就是404. 按流程操作一遍呗，又不亏

太迷了，Play服务清除数据+对应应用卸载重装，在登录完毕后划掉对应应用后台，尝试对其发送消息，依旧出现404的问题……
