### ISSUE TITLE
这是咋回事

### ISSUE THREAD

**Issue by Alanniea** [kooritea/fcmfix#78]
![2022-08-26-10-50-02](https://user-images.githubusercontent.com/93852428/186935538-da52c699-28b0-4f74-8504-f1475aa3b879.png)

**Comment by Alanniea** [comment]
![2022-08-26-10-49-30](https://user-images.githubusercontent.com/93852428/186945414-e0dc0cfe-1aac-4603-bf7c-ca6ce2742bb3.png)
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![Uploading 2022-08-26-10-48-54.png…]()

**Comment by Alanniea** [comment]
![2022-08-26-10-48-54](https://user-images.githubusercontent.com/93852428/187002374-2f746229-2a1e-4e95-b1d9-1e83dbc30421.png)

**Comment by anysoft** [comment]
你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。
hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志

**Comment by Alanniea** [comment]
> 你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。 hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志

重启Google play service还是这样，怎么hook到 Google play service

**Comment by kooritea** [comment]
看看重启后的日志

**Comment by anysoft** [comment]
> > 你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。 hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志
> 
> 重启Google play service还是这样，怎么hook到 Google play service

你用的什么xposed框架？？

@kooritea 建议把lsposed的默认xposed_scope添加进去，这样使用lsp的用户可以自动勾选☑️默认hook的APP

**Comment by kooritea** [comment]
> > > 你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。 hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志
> > 
> > 重启Google play service还是这样，怎么hook到 Google play service
> 
> 你用的什么xposed框架？？
> 
> @kooritea 建议把lsposed的默认xposed_scope添加进去，这样使用lsp的用户可以自动勾选☑️默认hook的APP

加了的，截图那个推荐应用就是

**Comment by Alanniea** [comment]
![2022-08-31-10-12-24](https://user-images.githubusercontent.com/93852428/187700941-7e5cfd21-0233-4cec-8ad7-6ab761bfe544.png)
这怎么解决

**Comment by anysoft** [comment]
> ![2022-08-31-10-12-24](https://user-images.githubusercontent.com/93852428/187700941-7e5cfd21-0233-4cec-8ad7-6ab761bfe544.png)
> 这怎么解决

看使用说明
需要lsposed中fcm作用域选中推送的APP，然后再在fcmfix界面勾选要推送的APP。

你现在是无法启动推送应用，所以无法接收消息。你如果应用是开启的那么直接能收到消息。

应该是你用其他软件限制了启动和后台。

**Comment by anysoft** [comment]
> > > > 你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。 hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志
> > > 
> > > 重启Google play service还是这样，怎么hook到 Google play service
> > 
> > 你用的什么xposed框架？？
> > 
> > @kooritea 建议把lsposed的默认xposed_scope添加进去，这样使用lsp的用户可以自动勾选☑️默认hook的APP
> 
> 加了的，截图那个推荐应用就是

fcm还是要唤醒应用才能显示通知，fcm最终应该是把消息丢给framework了(这个可以搜下fcm的流程)，我觉得可以hook后，转成模拟调用对应手机厂商的推送部分，这样就可以无需启动直接推送了。当然这样的话得对接不同系统rom了，越来越麻烦。

**Comment by Alanniea** [comment]
> > > > > 你这个看好像fcmfix没有hook到 Google play service，另外报错是因为无法唤醒APP导致通知无法显示的。 hook成功 fcm日志里边会有fcmfix字样，你可以强杀 Google play service 后在 进fcm diag看日志
> > > > 
> > > > 
> > > > 重启Google play service还是这样，怎么hook到 Google play service
> > > 
> > > 
> > > 你用的什么xposed框架？？
> > > @kooritea 建议把lsposed的默认xposed_scope添加进去，这样使用lsp的用户可以自动勾选☑️默认hook的APP
> > 
> > 
> > 加了的，截图那个推荐应用就是
> 
> fcm还是要唤醒应用才能显示通知，fcm最终应该是把消息丢给framework了(这个可以搜下fcm的流程)，我觉得可以hook后，转成模拟调用对应手机厂商的推送部分，这样就可以无需启动直接推送了。当然这样的话得对接不同系统rom了，越来越麻烦。

推送应用

**Comment by anysoft** [comment]
> 推送应用必须在后台运行吗，停止运行不可以收到通知吗

fcm的机制，或者说Android原生通知本身就是必须应用运行才能有通知显示，所以必须后台运行或者有通知时候能唤醒应用。否则只能用其他应用代理消息，比如thanox的微信代收代理通知。@kooritea 可以参考这个微信代收，fcmfix直接代收fcm通知，不转给应用，也不模拟转给手机厂商的消息管理。

国内厂商的通知推送不需要后台因为消息并没有发送给应用，而是自己的通知管理的系统APP代收的，只是显示图标和消息出发跳到了真实APP。

**Comment by anysoft** [comment]
> > 推送应用必须在后台运行吗，停止运行不可以收到通知吗
> 
> fcm的机制，或者说Android原生通知本身就是必须应用运行才能有通知显示，所以必须后台运行或者有通知时候能唤醒应用。否则只能用其他应用代理消息，比如thanox的微信代收代理通知。@kooritea 可以参考这个微信代收，fcmfix直接代收fcm通知，不转给应用，也不模拟转给手机厂商的消息管理。
> 
> 国内厂商的通知推送不需要后台因为消息并没有发送给应用，而是自己的通知管理的系统APP代收的，只是显示图标和消息出发跳到了真实APP。
> 
> 

可以hook Android原生通知就知道消息的真实发送者是通知管理代发的还是应用自己发出的，然后关闭钉钉发个钉钉消息就能看日志知道了。 @kooritea

**Comment by kooritea** [comment]
> > 推送应用必须在后台运行吗，停止运行不可以收到通知吗
> 
> fcm的机制，或者说Android原生通知本身就是必须应用运行才能有通知显示，所以必须后台运行或者有通知时候能唤醒应用。否则只能用其他应用代理消息，比如thanox的微信代收代理通知。@kooritea 可以参考这个微信代收，fcmfix直接代收fcm通知，不转给应用，也不模拟转给手机厂商的消息管理。
> 
> 国内厂商的通知推送不需要后台因为消息并没有发送给应用，而是自己的通知管理的系统APP代收的，只是显示图标和消息出发跳到了真实APP。

fcm消息不一定带有消息内容本身，也可能是应用在被触发fcm后自己拉取通知的，如果是针对fcm中携带了内容本身的消息进行代发，可能会让应用的状态有异常(重复发送之类的)，因为fcm设计的工作环境就是应用在运行的时候。

**Comment by anysoft** [comment]
> 



> > > 推送应用必须在后台运行吗，停止运行不可以收到通知吗
> > 
> > 
> > fcm的机制，或者说Android原生通知本身就是必须应用运行才能有通知显示，所以必须后台运行或者有通知时候能唤醒应用。否则只能用其他应用代理消息，比如thanox的微信代收代理通知。@kooritea 可以参考这个微信代收，fcmfix直接代收fcm通知，不转给应用，也不模拟转给手机厂商的消息管理。
> > 国内厂商的通知推送不需要后台因为消息并没有发送给应用，而是自己的通知管理的系统APP代收的，只是显示图标和消息出发跳到了真实APP。
> 
> fcm消息不一定带有消息内容本身，也可能是应用在被触发fcm后自己拉取通知的，如果是针对fcm中携带了内容本身的消息进行代发，可能会让应用的状态有异常(重复发送之类的)，因为fcm设计的工作环境就是应用在运行的时候。

是这种机制的话，那应用自己回调的自己消息服务器，确实会导致多次重发。这个确实没有啥好方法了。我目前怕拉不起来，针对im应用，我是借用thanox情景模式检测消息后情景模式来重复一次唤醒和铃声通知。

那fcmfix专注修复gms链接 和系统负优化就好。

**Comment by kooritea** [comment]
> > 
> 
> 
> 
> > > > 推送应用必须在后台运行吗，停止运行不可以收到通知吗
> > > 
> > > 
> > > fcm的机制，或者说Android原生通知本身就是必须应用运行才能有通知显示，所以必须后台运行或者有通知时候能唤醒应用。否则只能用其他应用代理消息，比如thanox的微信代收代理通知。@kooritea 可以参考这个微信代收，fcmfix直接代收fcm通知，不转给应用，也不模拟转给手机厂商的消息管理。
> > > 国内厂商的通知推送不需要后台因为消息并没有发送给应用，而是自己的通知管理的系统APP代收的，只是显示图标和消息出发跳到了真实APP。
> > 
> > fcm消息不一定带有消息内容本身，也可能是应用在被触发fcm后自己拉取通知的，如果是针对fcm中携带了内容本身的消息进行代发，可能会让应用的状态有异常(重复发送之类的)，因为fcm设计的工作环境就是应用在运行的时候。
> 
> 是这种机制的话，那应用自己回调的自己消息服务器，确实会导致多次重发。这个确实没有啥好方法了。我目前怕拉不起来，针对im应用，我是借用thanox情景模式检测消息后情景模式来重复一次唤醒和铃声通知。
> 
> 那fcmfix专注修复gms链接 和系统负优化就好。

而且仔细想了想，除非针对应用适配，否则没办法判断fcm内容是不是消息内容本身

**Comment by anysoft** [comment]
> 仔细想了想，除非针对应用适配，否则没办法判断

或者让用户自己选哪些应用代理通知。总的来说意义都不大，没必要了。
