### ISSUE TITLE
safetynet认证

### ISSUE THREAD

**Issue by Felix-Jung** [kooritea/fcmfix#8]
你好，请问有什么方法能够在使用这个模块的同时，让设备能够通过safetynet认证嘛？

**Comment by kooritea** [comment]
我不太清楚导致过不了safetynet的原因…
不知道你是用什么测试的，我magisk里的测试是有时可以过有时不能过，现在我使用了fcmfix但是magisk那里测试是通过的

**Comment by Felix-Jung** [comment]
哦我找到原因了，只要在lsposed里取消勾选com.google.android.gms，就能通过认证了，谢谢！
