### ISSUE TITLE
最近几天fcm是否都异常了？

### ISSUE THREAD

**Issue by anysoft** [kooritea/fcmfix#87]
我同步升级到了0.5.2 发现无法收到消息，然后一直折腾。发现旧手机fcm也连不上了，之前用hosts直连fcm的。
我看host都是通的，换了n多的全球ip就是连不上，一开梯子立马连上了。你们都怎么样的？

**Comment by kooritea** [comment]
直连能不能连上不在本项目讨论范围之内…建议找技术论坛
