### ISSUE TITLE
建議在軟件加入自動檢測升級

### ISSUE THREAD

**Issue by N2022062** [kooritea/fcmfix#88]
每次來這裏下載升級太費事了

**Comment by kooritea** [comment]
其实用着没问题最好不要升。。因为不考虑向前兼容(

**Comment by TigerBeanst** [comment]
可以给仓库点一个 watch 设置成 release（

**Comment by TigerBeanst** [comment]
> 其实用着没问题最好不要升。。因为不考虑向前兼容(

话说没有打算上架 LSPosed 仓库吗（

**Comment by kooritea** [comment]
> > 其实用着没问题最好不要升。。因为不考虑向前兼容(
> 
> 话说没有打算上架 LSPosed 仓库吗（

懒了

**Comment by David-plz** [comment]
> 其实用着没问题最好不要升。。因为不考虑向前兼容(

这里都是不升不舒服斯基，有更新都是必更的

**Comment by kooritea** [comment]
在lsposed仓库上更新即可
