### ISSUE TITLE
不能读取应用列表，找不到谷歌服务框架com.google.android.gms

### ISSUE THREAD

**Issue by lsjiaowo** [kooritea/fcmfix#9]
作者你好，还是忍不住折腾了一下，遇到了之前一个issue的问题，但是看到后面0.2.0版本已经解决这个问题。我这里还是不能读取应用列表。自启动已开启，fcm也是可以连接上的（Conneted），但是就是收不到推送通知

引用：“但是fcmfix里可勾选的应用依然还是只有com.android.vending（谷歌play商店)，我现在确实存在即使在fcm日志里看到successful broadcast也无通知的问题(app已开自启甚至已有缓存的情况)”

手机配置：Android 11，MIUI12.5.3 稳定版，fcmfix0.2.0

**Comment by kooritea** [comment]
读取应用列表的权限有给fcmfix吗，如果有的话实在想不到什么地方有问题

**Comment by lsjiaowo** [comment]
已经给fcm读取应用列表的权限了，始终允许。
想要推送的app是推特，已经在fcm里勾选了推特，也显示successful，但是好像是变成了chrome浏览器了？fcm里chrome也都勾选了。（fcm里面没有gms）
![Screenshot_2021-06-10-13-15-40-223_com google android gms](https://user-images.githubusercontent.com/49240966/121469203-a73b1a80-c9ee-11eb-886c-881c7e8c7931.jpg)

另：我在edxposed里都设置了作用域。

**Comment by kooritea** [comment]
chrome是没有经过fcmfix被正常唤起的
fcm有作用的话会有[fcmfix]标注的日志

lsposed作用域要勾选安卓系统

如果实在没办法弄出应用列表的话就只能直接编辑配置文件了
/data/data/com.kooritea.fcmfix/shared_prefs/config.xml

配置成这个样子看看
```xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <set name="allowList">
        <string>com.twitter.android</string>
    </set>
</map>

```

**Comment by lsjiaowo** [comment]
可以了！需要以下两点
1. fcmfix只需要勾选目标应用，推特或者chrome
2. lsposed或edxposed需要勾选安卓作用域和gms
![Uploading Screenshot_2021-06-10-14-31-10-980_com.google.android.gms.jpg…]()

我找了半天安卓系统文件名叫啥，还以为com.android.XXX，原来就叫一个android(笑cry)
由于我解锁之后从备份恢复应用所以有点bug，把推特卸载了重新安装就可以了。
感谢作者！😊
