### ISSUE TITLE
怎样卸载干净？

### ISSUE THREAD

**Issue by naniccc** [kooritea/fcmfix#91]
![Screenshot_2022-10-30-11-35-18-600_com android settings-edit](https://user-images.githubusercontent.com/57870281/198861382-2f8ab3ea-4215-45c3-9b87-49cec8e3fca2.jpg)
卸载后，通知里还有fcmfix，怎样卸载干净？

**Comment by kooritea** [comment]
这个通知渠道现在没法主动删除，之后修复

**Comment by kooritea** [comment]
安装0.6.1版本，重启，再卸载fcmfix就能删除这个通知渠道了

**Comment by naniccc** [comment]
> 安装0.6.1版本，重启，再卸载fcmfix就能删除这个通知渠道了

谢谢！🌹🌹🌹🌹🌹
