### ISSUE TITLE
选中的应用里需要包含Google play services吗？

### ISSUE THREAD

**Issue by Yyyoungc** [kooritea/fcmfix#94]
如题，包不包含应该没区别吧？

**Comment by Yyyoungc** [comment]
> lsposed里可选（提供日志和固定心跳间隔功能），fcmfix应用里不需要

感谢！

**Comment by Yyyoungc** [comment]
> lsposed里可选（提供日志和固定心跳间隔功能），fcmfix应用里不需要

噢我还有个问题，用了fcmfix，还需要给gms挂梯子吗？

**Comment by TigerBeanst** [comment]
> > lsposed里可选（提供日志和固定心跳间隔功能），fcmfix应用里不需要
> 
> 噢我还有个问题，用了fcmfix，还需要给gms挂梯子吗？

fcmfix 只负责保证在网络通畅的情况下让 fcm 正常工作，如果你的设备连不上对应的服务器是没用的

**Comment by Yyyoungc** [comment]
> > > lsposed里可选（提供日志和固定心跳间隔功能），fcmfix应用里不需要
> > 
> > 
> > 噢我还有个问题，用了fcmfix，还需要给gms挂梯子吗？
> 
> fcmfix 只负责保证在网络通畅的情况下让 fcm 正常工作，如果你的设备连不上对应的服务器是没用的

我现在没给gms挂梯子，也能正常收到fcm推送，但看诊断，有时会连接失败

**Comment by TigerBeanst** [comment]
> 我现在没给gms挂梯子，也能正常收到fcm推送，但看诊断，有时会连接失败

因为 fcm 的服务器在大陆并非都寄，有一些是可以直连上的

**Comment by Yyyoungc** [comment]
> > 我现在没给gms挂梯子，也能正常收到fcm推送，但看诊断，有时会连接失败
> 
> 因为 fcm 的服务器在大陆并非都寄，有一些是可以直连上的

好的，那我还是把给gms挂梯子吧，感恩
