### ISSUE TITLE
MIUI12.5 微信走fcm会反复推送历史消息

### ISSUE THREAD

**Issue by a994849598** [kooritea/fcmfix#97]
就是会时不时推   曾经发过的信息  不知道怎么办
(无微信后台)

**Comment by kooritea** [comment]
无后台不可能推得出来吧

**Comment by a994849598** [comment]
啊  是一定要有 后台吗？  我是用Thanox软件里面的 ”微信代收“ 功能

**Comment by a994849598** [comment]
![d8fde179ac4e0e7ef39a32a40f8739b](https://user-images.githubusercontent.com/54111756/204831152-3e6c1db9-9818-4064-8e37-8eca675c234f.jpg)

**Comment by kooritea** [comment]
不知道你这个代收是怎么样工作的。
理论上要微信在后台，微信接收到通知，微信服务器把消息标记为已接收，才不会再次推送。

**Comment by a994849598** [comment]
好的 明白了

**Comment by a994849598** [comment]
你好   还有个问题就是  这个显示  连接  但提示:Err_IO_FIN 是因为什么？  (用的是wifi连接)

**Comment by kooritea** [comment]
这是上次连接失败的原因，不用管。现在是已经连接了的。

**Comment by a994849598** [comment]
明白了  谢谢(*^o^*)
